### ISSUE TITLE
spring-cloud-stream-binder-kafka 2.0.0.M1 can't receive event message

### ISSUE THREAD

**Issue by a479159321** [spring-cloud/spring-cloud-stream#1102]
I use `Spring Boot 2.0.0.M3` and `Spring Cloud Finchley.M2`,using `spring-cloud-stream-binder-kafka 2.0.0.M1` to test a simple produce and consume demo ,and find that produce event to `kafka` is OK, but the consumer cann't get the event message.

I change the Spring Boot version to `1.5.6.RELEASE`,Spring Cloud version to `Dalston.SR4`, everything is fine .

Demo projects link: https://github.com/wiselyman/Spring-Cloud-Stream-Kafka-CQRS-ES.

Thanks for all your helps.

**Comment by sobychacko** [comment]
@a479159321 didn't take a closer look at your demo project yet, but spring cloud stream `2.0.0.M1` was released a while back and things have changed since then. Could you update your sample to use the latest snapshots and see if you notice the same problems? That will be very helpful, as we are nearing an M2 release shortly.

**Comment by a479159321** [comment]
@sobychacko Thank you for your answer! I have tried the latest snapshot version `Finchley.BUILD-SNAPSHOT` of `spring-cloud`, But it seems that my sample cann't run. And I get some errors:

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bindingService' defined in org.springframework.cloud.stream.config.BindingServiceConfiguration: Unsatisfied dependency expressed through method 'bindingService' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.stream.config.BinderFactoryConfiguration': Unsatisfied dependency expressed through field 'binderFactoryListeners'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration': Instantiation of bean failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:726) ~[spring-beans-5.0.0.RC3.jar:5.0.0.RC3]`

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.stream.config.BinderFactoryConfiguration': Unsatisfied dependency expressed through field 'binderFactoryListeners'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration': Instantiation of bean failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:570) ~[spring-beans-5.0.0.RC3.jar:5.0.0.RC3]`

`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration': Instantiation of bean failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1242) ~[spring-beans-5.0.0.RC3.jar:5.0.0.RC3]`

`Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724) ~[na:1.8.0_144]
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531) ~[na:1.8.0_144]
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355) ~[na:1.8.0_144]
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286) ~[na:1.8.0_144]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[na:1.8.0_144]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[na:1.8.0_144]
	at java.lang.Class.createAnnotationData(Class.java:3521) ~[na:1.8.0_144]`

**Comment by olegz** [comment]
@a479159321 could you please include the rest of the stack trace you posted. It is most likely triggered by CNFException, so I want to see what that is.

**Comment by sabbyanandan** [comment]
Duplicates spring-cloud/spring-cloud-stream-binder-kafka#229.
