### ISSUE TITLE
Please don’t drag in Spring Boot started Web 

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-stream#1175]
It breaks in a Spring Webflux world 

https://github.com/spring-cloud/spring-cloud-stream/blob/1.3.x/spring-cloud-stream/pom.xml#L21

**Comment by olegz** [comment]
Capturing some of the notes form internal discussion:

- we seem to use Jackson in number of places dependency so probably still need `spring-web`, but not necessarily `spring-boot-starter-web`
- Removing web dependency, will make actuator "optional" but we all seem to agree that it is not a bad thing
- GSON vs Jackson . . .

**Comment by olegz** [comment]
@joshlong @dsyer This may not be as simple as it may seem. While I am still digging things are a bit more intertwined then they appear at the surface.

While switching to `spring-web` does remove tomcat, it does create an issue with what I believe the  actuator annotation parsing during the boot:
```
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724) ~[na:1.8.0_121]
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531) ~[na:1.8.0_121]
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355) ~[na:1.8.0_121]
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286) ~[na:1.8.0_121]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[na:1.8.0_121]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[na:1.8.0_121]
	at java.lang.Class.createAnnotationData(Class.java:3521) ~[na:1.8.0_121]
	at java.lang.Class.annotationData(Class.java:3510) ~[na:1.8.0_121]
	at java.lang.Class.getAnnotations(Class.java:3446) ~[na:1.8.0_121]
	at org.springframework.core.type.StandardAnnotationMetadata.<init>(StandardAnnotationMetadata.java:70) ~[spring-core-5.0.2.RELEASE.jar:5.0.2.RELEASE]
```
Removing the actuator dependency results in compilation errors and so on . . .

**Comment by dsyer** [comment]
Pretty standard stuff, and I don’t think it’s complicated at all, really. Those type not present exceptions are hard to debug, but it’s not unexpected when you make a dependency optional. Normally the fix is just to add a `@Conditional` somewhere.

**Comment by thekalinga** [comment]
This dependency exists even in `2.0.0.M4`

```
+--- org.springframework.cloud:spring-cloud-stream:2.0.0.M4
|    |    +--- org.springframework.boot:spring-boot-starter-actuator:2.0.0.RC1 (*)
|    |    +--- org.springframework.boot:spring-boot-starter-web:2.0.0.RC1
|    |    |    +--- org.springframework.boot:spring-boot-starter:2.0.0.RC1 (*)
|    |    |    +--- org.springframework.boot:spring-boot-starter-json:2.0.0.RC1 (*)
|    |    |    +--- org.springframework.boot:spring-boot-starter-tomcat:2.0.0.RC1
|    |    |    |    +--- javax.annotation:javax.annotation-api:1.3.1
|    |    |    |    +--- org.apache.tomcat.embed:tomcat-embed-core:8.5.27
|    |    |    |    +--- org.apache.tomcat.embed:tomcat-embed-el:8.5.27
|    |    |    |    \--- org.apache.tomcat.embed:tomcat-embed-websocket:8.5.27
|    |    |    |         \--- org.apache.tomcat.embed:tomcat-embed-core:8.5.27
|    |    |    +--- org.hibernate.validator:hibernate-validator:6.0.7.Final (*)
|    |    |    +--- org.springframework:spring-web:5.0.3.RELEASE (*)
|    |    |    \--- org.springframework:spring-webmvc:5.0.3.RELEASE
|    |    |         +--- org.springframework:spring-aop:5.0.3.RELEASE (*)
|    |    |         +--- org.springframework:spring-beans:5.0.3.RELEASE (*)
|    |    |         +--- org.springframework:spring-context:5.0.3.RELEASE (*)
|    |    |         +--- org.springframework:spring-core:5.0.3.RELEASE (*)
|    |    |         +--- org.springframework:spring-expression:5.0.3.RELEASE (*)
|    |    |         \--- org.springframework:spring-web:5.0.3.RELEASE (*)
|    |    +--- org.springframework.boot:spring-boot-starter-validation:2.0.0.RC1 (*)
|    |    +--- org.springframework:spring-messaging:5.0.3.RELEASE
|    |    |    +--- org.springframework:spring-beans:5.0.3.RELEASE (*)
|    |    |    \--- org.springframework:spring-core:5.0.3.RELEASE (*)
|    |    +--- org.springframework.integration:spring-integration-core:5.0.1.RELEASE
|    |    |    +--- org.springframework:spring-core:5.0.3.RELEASE (*)
|    |    |    +--- org.springframework:spring-aop:5.0.3.RELEASE (*)
|    |    |    +--- org.springframework:spring-context:5.0.3.RELEASE (*)
|    |    |    +--- org.springframework:spring-messaging:5.0.3.RELEASE (*)
|    |    |    +--- org.springframework:spring-tx:5.0.3.RELEASE
|    |    |    |    +--- org.springframework:spring-beans:5.0.3.RELEASE (*)
|    |    |    |    \--- org.springframework:spring-core:5.0.3.RELEASE (*)
|    |    |    +--- org.springframework.retry:spring-retry:1.2.2.RELEASE
|    |    |    |    \--- org.springframework:spring-core:4.3.13.RELEASE -> 5.0.3.RELEASE (*)
|    |    |    \--- io.projectreactor:reactor-core:3.1.3.RELEASE (*)
|    |    +--- org.springframework.integration:spring-integration-jmx:5.0.1.RELEASE
|    |    |    \--- org.springframework.integration:spring-integration-core:5.0.1.RELEASE (*)
|    |    +--- org.springframework:spring-tuple:1.0.0.RELEASE
|    |    |    +--- com.esotericsoftware:kryo-shaded:3.0.3
|    |    |    |    +--- com.esotericsoftware:minlog:1.3.0
|    |    |    |    \--- org.objenesis:objenesis:2.1
|    |    |    +--- org.springframework:spring-core:4.2.6.RELEASE -> 5.0.3.RELEASE (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.6.6 -> 2.9.3 (*)
|    |    |    \--- org.springframework:spring-context:4.2.6.RELEASE -> 5.0.3.RELEASE (*)
|    |    +--- org.springframework.integration:spring-integration-tuple:1.0.0.RELEASE
|    |    |    +--- org.springframework:spring-tuple:1.0.0.RELEASE (*)
|    |    |    \--- org.springframework.integration:spring-integration-core:4.2.5.RELEASE -> 5.0.1.RELEASE (*)
|    |    \--- org.springframework.retry:spring-retry:1.2.2.RELEASE (*)
|    \--- org.springframework.integration:spring-integration-core:5.0.1.RELEASE (*)
```

**Comment by olegz** [comment]
That is correct. Please look at "Milestone" and realize that this issue was resolved for RC1 which was release few days ago.

**Comment by thekalinga** [comment]
@olegz Thanks for that letting me know. Must have overlooked at the milestone
