### ISSUE TITLE
Configure Custome AWS Kinesis Binder in SpringBoot 1.5.3Release

### ISSUE THREAD

**Issue by RanjithMohandass** [spring-cloud/spring-cloud-stream#1213]
HI @artembilan ,

This is a little urgent, I would like to know whether it is possible to write our own custom binder implementation for AWS Kinesis stream without upgrading my boot version to 2.0 .

Below are the dependencies i am adding currently ,

```
compile('org.springframework.cloud:spring-cloud-stream:2.0.0.M3')
compile('org.springframework.cloud:spring-cloud-starter-stream-kinesis:1.0.0.BUILD-SNAPSHOT')
compile group: 'com.amazonaws', name: 'aws-java-sdk-core', version: '1.11.270'
```

But while starting the application it fails with the below exception 

```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.jcp.catalog.inbound.pim.MessageSinkApplication]; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.databind.ObjectMapper
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:616) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:548) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:185) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:308) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:92) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at com.jcp.catalog.inbound.pim.MessageSinkApplication.main(MessageSinkApplication.java:20) [classes/:na]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.databind.ObjectMapper
	at com.amazonaws.util.EC2MetadataUtils.<clinit>(EC2MetadataUtils.java:73) ~[aws-java-sdk-core-1.11.270.jar:na]
	at org.springframework.cloud.aws.context.support.env.AwsCloudEnvironmentCheckUtils.isRunningOnCloudEnvironment(AwsCloudEnvironmentCheckUtils.java:36) ~[spring-cloud-aws-context-1.1.0.RELEASE.jar:1.1.0.RELEASE]
	at org.springframework.cloud.aws.context.annotation.OnAwsCloudEnvironmentCondition.matches(OnAwsCloudEnvironmentCondition.java:37) ~[spring-cloud-aws-context-1.1.0.RELEASE.jar:1.1.0.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:217) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:606) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	... 15 common frames omitted
```

Please let me know whether there is any possible way of doing this

**Comment by artembilan** [comment]
Hi, @RanjithMohandass !

1. First of all this is wrong place for such a question. The proper project is here: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis. The people here might just don't know what is the story about.
2. If you would like to get a help, you should study how to comment properly on the GitHub: https://help.github.com/articles/basic-writing-and-formatting-syntax/. Right now your question is a bit not readable. Now I have to spend sometime to polish your comment and only after that I can come back to the understanding what's going on.
3. Looking to the topic of your question it's a bit confusing. You are going to use Kinesis Binder BUILD-SNAPSHOT, but at the same time you can't use Spring Boot 2.0 RC1 and Spring Cloud Stream 2.0.0.M4...

And finally no, there is no way to make the current Kinesis Binder to work with Spring Boot 1.5.3. That's not on our roadmap.

Thank you for understanding.

**Comment by sabbyanandan** [comment]
@RanjithMohandass: To add to @artembilan's comment, the Kinesis-binder is _strictly-only_ compatible with Spring Boot 2.0. To try it out, please download Boot 2.0 RC1 from [Spring Initializr](http://start.spring.io/), build the Kinesis-binder locally (2.0 BUILD-SNAPSHOT), and confirm to [dependent versions](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/master/pom.xml#L18-L21). The rest of the instructions is in the [docs](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/master/spring-cloud-stream-binder-kinesis-docs/src/main/asciidoc/overview.adoc#usage).
