### ISSUE TITLE
NoSuchMethodError due to changes in Binder in Spring Boot

### ISSUE THREAD

**Issue by tambre** [spring-cloud/spring-cloud-stream#1233]
Hi, 

Since today, getting the following error. You guys might already get it as compilation error. link to changes to Spring boot: [https://github.com/spring-projects/spring-boot/commit/20109e27be24da74e884c14a03afc8f9561e4196](url)

`Caused by: java.lang.NoSuchMethodError: org.springframework.boot.context.properties.bind.Binder.<init>(Ljava/lang/Iterable;Lorg/springframework/boot/context/properties/bind/PlaceholdersResolver;Lorg/springframework/core/convert/ConversionService;)V
        at org.springframework.cloud.stream.config.EnvironmentEntryInitializingTreeMap.put(EnvironmentEntryInitializingTreeMap.java:97)
        at org.springframework.cloud.stream.config.EnvironmentEntryInitializingTreeMap.put(EnvironmentEntryInitializingTreeMap.java:48)
        at java.util.AbstractMap.putAll(AbstractMap.java:281)
        at org.springframework.boot.context.properties.bind.MapBinder.merge(MapBinder.java:87)
        at org.springframework.boot.context.properties.bind.MapBinder.merge(MapBinder.java:40)
        at org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:63)
        at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$2(Binder.java:291)
        at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:424)
        at org.springframework.boot.context.properties.bind.Binder$Context.access$100(Binder.java:364)
        at org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:290)
        at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:248)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:206)
        at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$4(Binder.java:316)
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:72)
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:61)
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:53)
        at org.springframework.boot.context.properties.bind.Binder.lambda$null$5(Binder.java:324)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$6(Binder.java:325)
        at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:424)
        at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:410)
        at org.springframework.boot.context.properties.bind.Binder$Context.access$400(Binder.java:364)
        at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:322)
        at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:264)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:206)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:195)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:177)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:78)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:106)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:93)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:423)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583)
        ... 128 common frames omitted
`

**Comment by olegz** [comment]
Yep, we see it

**Comment by olegz** [comment]
@tambre should be all good now

**Comment by tambre** [comment]
thanks. its working now.
