### ISSUE TITLE
Unable to deserialize using contentType protobuf, when only producer is upgraded to newer version of Spring Cloud Stream

### ISSUE THREAD

**Issue by vetrigyan** [spring-cloud/spring-cloud-stream#1376]
I'm encountering an issue on my consumer side, after I upgraded the producer to use Spring-Cloud Finchley.M9 with SCS version ELMHURST.RELEASE, while the consumer is still at older Spring-Cloud Dalston.SR5/Chelsea.SR2.  

The message payload is expected to serialize/deserialize using ProtoBuf enc/decoding. Things used to work fine prior to upgrading the producer's SCS version. 

This issue is seen with the below mentioned headerMode settings:

1. Producer (embeddedHeaders), Consumer (embeddedHeaders)
2. Producer (embeddedHeaders), Consumer (not explicitly set, since default is supposed to be embeddedHeaders)

I've posted on github a small example code for the producer and consumer that exhibits this issue: [Sample code](https://github.com/vetrigyan/scs-issues)

Below is the exception i see on the consumer side. The SerializationFailedException is attributed to a preceding NPE...

`03-05-2018 18:12:46.041 [-L-1] ERROR o.s.k.listener.LoggingErrorHandler.handle - Error while processing: ConsumerRecord(topic = equipment-ms-in-topic, partition = 0, offset = 56, CreateTime = 1525396357018, checksum = 949873240, serialized key size = -1, serialized value size = 85, key = null, value = [B@3792c712)
org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$ReceivingHandler@1671d8cb]; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Unable to deserialize [null] using the contentType [application/protobuf] null; nested exception is java.lang.NullPointerException
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:139) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:70) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:64) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) ~[spring-messaging-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) ~[spring-messaging-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) ~[spring-messaging-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:188) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$000(KafkaMessageDrivenChannelAdapter.java:54) ~[spring-integration-kafka-2.1.0.RELEASE.jar!/:na]
        at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:288) ~[spring-integration-kafka-2.1.0.RELEASE.jar!/:na]
        at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:279) ~[spring-integration-kafka-2.1.0.RELEASE.jar!/:na]
        at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter$1.doWithRetry(RetryingAcknowledgingMessageListenerAdapter.java:79) ~[spring-kafka-1.1.7.RELEASE.jar!/:na]
        at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter$1.doWithRetry(RetryingAcknowledgingMessageListenerAdapter.java:73) ~[spring-kafka-1.1.7.RELEASE.jar!/:na]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) ~[spring-retry-1.2.1.RELEASE.jar!/:na]
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180) ~[spring-retry-1.2.1.RELEASE.jar!/:na]
        at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter.onMessage(RetryingAcknowledgingMessageListenerAdapter.java:73) ~[spring-kafka-1.1.7.RELEASE.jar!/:na]
        at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter.onMessage(RetryingAcknowledgingMessageListenerAdapter.java:39) ~[spring-kafka-1.1.7.RELEASE.jar!/:na]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:792) [spring-kafka-1.1.7.RELEASE.jar!/:na]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:736) [spring-kafka-1.1.7.RELEASE.jar!/:na]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.access$2100(KafkaMessageListenerContainer.java:246) [spring-kafka-1.1.7.RELEASE.jar!/:na]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer$ListenerInvoker.run(KafkaMessageListenerContainer.java:1025) [spring-kafka-1.1.7.RELEASE.jar!/:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Unable to deserialize [null] using the contentType [application/protobuf] null; nested exception is java.lang.NullPointerException
        at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayload(AbstractBinder.java:267) ~[spring-cloud-stream-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayload(AbstractBinder.java:234) ~[spring-cloud-stream-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayloadIfNecessary(AbstractBinder.java:213) ~[spring-cloud-stream-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$ReceivingHandler.handleRequestMessage(AbstractMessageChannelBinder.java:314) ~[spring-cloud-stream-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        ... 22 common frames omitted
Caused by: java.lang.NullPointerException: null
`

**Comment by olegz** [comment]
It is probably related to the fact that we no longer using Kryo (deprecated) to blindly serialize message. However, Kryo is still available as long as content type for the outgoing and incoming message is set to `application/x-java-object`

**Comment by garyrussell** [comment]
Chelsea is too old - I just upgraded your old consumer app to Ditmars (Edgware.SR2 for the cloud deps) and...

```
+++++++++++++++GOT SOMETHING from producer ++++++++++++id: 123
name: "vetrigyan"
```

Elmhurst is compatible with Ditmars, but not Chelsea.

**Comment by vetrigyan** [comment]
@garyrussell - Yes, I see it working after making the change you suggested. 

So as a general guideline, what is a good rule of thumb when it comes to expecting backwards compatibility between SCS release versions, so that we can avoid running into this kind of compatibility issues ?

I really appreciate your help here and your quick response, Gary.

**Comment by sabbyanandan** [comment]
Hi, @vetrigyan. Thanks for the update. Chelsea is little over a year old release. It takes effort (refactor/dev/testing) to retain backward compatibility and we are determined to do that always; however, it is not as easy to retain compatibility in all the minor releases. The recent minor release is our target, and in this case, it is Ditmars. If you see any other anomaly, feel free to open a new issue.
