### ISSUE TITLE
AvroRuntimeException on sending messages to channel

### ISSUE THREAD

**Issue by 4shael** [spring-cloud/spring-cloud-stream#1470]
Message serializing with avro broke, after upgrading from Finchley.RELEASE to .SR1. Getting exception:
```
2018-09-07 12:34:46.173 ERROR 24836 --- [cTaskExecutor-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected error occurred invoking async method 'public void com.example.accounts.events.AccountEventsListener.handleAccountCreated(com.example.accounts.events.model.AccountCreatedEvent)'.

org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'account-created'; nested exception is org.springframework.messaging.converter.MessageConversionException: Could not write JSON: Not a union: {"type":"record","name":"AccountTO","namespace":"com.example.avro","fields":[{"name":"id","type":{"type":"string","avro.java.string":"String"}},{"name":"email","type":{"type":"string","avro.java.string":"String"}}]} (through reference chain: com.example.avro.AccountTO["schema"]->org.apache.avro.Schema$RecordSchema["types"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Not a union: {"type":"record","name":"AccountTO","namespace":"com.example.avro","fields":[{"name":"id","type":{"type":"string","avro.java.string":"String"}},{"name":"email","type":{"type":"string","avro.java.string":"String"}}]} (through reference chain: com.example.avro.AccountTO["schema"]->org.apache.avro.Schema$RecordSchema["types"])
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInDeliveryExceptionIfNecessary(IntegrationUtils.java:163) ~[spring-integration-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:475) ~[spring-integration-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394) ~[spring-integration-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at com.example.accounts.events.AccountEventsListener.handleAccountCreated(AccountEventsListener.java:21) ~[main/:na]
	at com.example.accounts.events.AccountEventsListener$$FastClassBySpringCGLIB$$963bffc.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_172]
Caused by: org.springframework.messaging.converter.MessageConversionException: Could not write JSON: Not a union: {"type":"record","name":"AccountTO","namespace":"com.example.avro","fields":[{"name":"id","type":{"type":"string","avro.java.string":"String"}},{"name":"email","type":{"type":"string","avro.java.string":"String"}}]} (through reference chain: com.example.avro.AccountTO["schema"]->org.apache.avro.Schema$RecordSchema["types"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Not a union: {"type":"record","name":"AccountTO","namespace":"com.example.avro","fields":[{"name":"id","type":{"type":"string","avro.java.string":"String"}},{"name":"email","type":{"type":"string","avro.java.string":"String"}}]} (through reference chain: com.example.platform.avro.AccountTO["schema"]->org.apache.avro.Schema$RecordSchema["types"])
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertToInternal(MappingJackson2MessageConverter.java:284) ~[spring-messaging-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.cloud.stream.converter.ApplicationJsonMessageMarshallingConverter.convertToInternal(ApplicationJsonMessageMarshallingConverter.java:66) ~[spring-cloud-stream-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.messaging.converter.AbstractMessageConverter.toMessage(AbstractMessageConverter.java:201) ~[spring-messaging-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.messaging.converter.AbstractMessageConverter.toMessage(AbstractMessageConverter.java:191) ~[spring-messaging-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.messaging.converter.CompositeMessageConverter.toMessage(CompositeMessageConverter.java:83) ~[spring-messaging-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.cloud.stream.binding.MessageConverterConfigurer$OutboundContentTypeConvertingInterceptor.doPreSend(MessageConverterConfigurer.java:322) ~[spring-cloud-stream-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.cloud.stream.binding.MessageConverterConfigurer$AbstractContentTypeInterceptor.preSend(MessageConverterConfigurer.java:351) ~[spring-cloud-stream-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:589) ~[spring-integration-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:435) ~[spring-integration-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	... 9 common frames omitted
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Not a union: {"type":"record","name":"AccountTO","namespace":"com.example.avro","fields":[{"name":"id","type":{"type":"string","avro.java.string":"String"}},{"name":"email","type":{"type":"string","avro.java.string":"String"}}]} (through reference chain: com.example.avro.AccountTO["schema"]->org.apache.avro.Schema$RecordSchema["types"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2655) ~[jackson-databind-2.9.6.jar:2.9.6]
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertToInternal(MappingJackson2MessageConverter.java:268) ~[spring-messaging-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 17 common frames omitted
Caused by: org.apache.avro.AvroRuntimeException: Not a union: {"type":"record","name":"AccountTO","namespace":"com.example.avro","fields":[{"name":"id","type":{"type":"string","avro.java.string":"String"}},{"name":"email","type":{"type":"string","avro.java.string":"String"}}]}
	at org.apache.avro.Schema.getTypes(Schema.java:299) ~[avro-1.8.2.jar:1.8.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:687) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) ~[jackson-databind-2.9.6.jar:2.9.6]
	... 25 common frames omitted
```

**Comment by olegz** [comment]
What I am observing from your stack trace is that you do not have an appropriate `MessageConverter` doing the conversion. I see `ApplicationJsonMessageMarshallingConverter` instead of one of the sub-classes of `AbstractAvroMessageConverter`. Please provide more details about your application or instruction to reproduce. I suspect the content type of your message is `application/json` which triggers `ApplicationJsonMessageMarshallingConverter`, but then again, it's pure speculation at this point.

**Comment by 4shael** [comment]
Thanks for the answer!
I've created a sample: https://github.com/4shael/spring-cloud-stream-avro-example
Also, I found out, that the problem is in config, with default contentType:
```
spring:
  cloud:
    stream:
      schemaRegistryClient:
        endpoint: http://localhost:9081
      default:
        contentType: application/*+avro
      bindings:
        account-created:
          destination: account-created
      kafka.binder:
        brokers: localhost:9092
      schema.avro.shemaLocations: classpath*:avro/example.avsc
```
If instead of default we define contentType for channel directly, the problem will gone:
```
spring:
  cloud:
    stream:
      schemaRegistryClient:
        endpoint: http://localhost:9081
      bindings:
        account-created:
          destination: account-created
          contentType: application/*+avro
      kafka.binder:
        brokers: localhost:9092
      schema.avro.shemaLocations: classpath*:avro/example.avsc
```
In Finchley.RELEASE default contentType works fine (as described in 
https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_common_binding_properties).

**Comment by olegz** [comment]
So, this issue could be closed, correct?

**Comment by 4shael** [comment]
There is an issue with setting default content-type, that leads to this exception. I'm not sure if we should close this one and open another, or just fix it  here.

**Comment by 4shael** [comment]
@olegz please, look at this comment once again: https://github.com/spring-cloud/spring-cloud-stream/issues/1470#issuecomment-419881168
`spring.cloud.stream.default.contentType` doesn't work as expected in Finchley.SR1.

**Comment by olegz** [comment]
Yep, my bad. . .
I get it now, sorry about it.

**Comment by 4shael** [comment]
np

**Comment by olegz** [comment]
@4shael  The sample app you referenced doesn't compile (missing AccountDTO or something). But that's not relevant. What is relevant is that you're using invalid name identifier for the binding interface as it contains `-` character which is not a valid Java identifier. 
```
@Output("account-created")
```
Change it to `@Output("accountCreated")` or something that is a valid java identifier.

If you still have problems feel free to reopen this issue.

**Comment by matej2** [comment]
>  Could not write JSON: Not a union:
I am getting this error when trying to return a non-avro object. I dont know why it expects object to be compactible with avro schema..
