### ISSUE TITLE
Not able to connect to kafka stream

### ISSUE THREAD

**Issue by bhanu0684** [spring-cloud/spring-cloud-stream#1496]
is my config file
>spring.cloud.stream:
  bindings:
    greetings-in:
      destination: xemx4rje-default
      binder: kafka1
    greetings-out:
      destination: xemx4rje-default
      binder: kafka1
  binders:
    kafka1:
      type: kafka
      environment:
        spring:
          cloud:
            stream:
              kafka:
                binder.brokers: ark-01.srvs.cloudkafka.com:9094,ark-02.srvs.cloudkafka.com:9094,ark-03.srvs.cloudkafka.com:9094
                binder.jaas.loginModule: com.sun.security.auth.module.ScramLoginModule 
                binder.jaas.options.username: uid
                binder.jaas.options.password: pwd
                binder:
                  configuration:
                    security.protocol: SASL_SSL
>                    sasl.mechanism: SCRAM-SHA-256`

I am getting below error

2018-10-09 14:36:45.532 ERROR 19316 --- [sk-scheduler-10] o.s.cloud.stream.binding.BindingService  : Failed to create consumer binding; retrying in 30 seconds

org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:326) ~[spring-cloud-stream-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:77) ~[spring-cloud-stream-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:131) ~[spring-cloud-stream-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.lambda$rescheduleConsumerBinding$0(BindingService.java:154) ~[spring-cloud-stream-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
Caused by: org.apache.kafka.common.KafkaException: Failed create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:336) ~[kafka-clients-1.0.2.jar:na]
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:61) ~[kafka-clients-1.0.2.jar:na]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.createAdminClient(KafkaTopicProvisioner.java:188) ~[spring-cloud-stream-binder-kafka-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionConsumerDestination(KafkaTopicProvisioner.java:164) ~[spring-cloud-stream-binder-kafka-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionConsumerDestination(KafkaTopicProvisioner.java:74) ~[spring-cloud-stream-binder-kafka-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:274) ~[spring-cloud-stream-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	... 10 common frames omitted
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: KrbException: Cannot locate default realm
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:112) ~[kafka-clients-1.0.2.jar:na]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:114) ~[kafka-clients-1.0.2.jar:na]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:61) ~[kafka-clients-1.0.2.jar:na]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:86) ~[kafka-clients-1.0.2.jar:na]
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:312) ~[kafka-clients-1.0.2.jar:na]
	... 15 common frames omitted
Caused by: javax.security.auth.login.LoginException: KrbException: Cannot locate default realm
	at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:781) ~[jdk.security.auth:na]
	at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:592) ~[jdk.security.auth:na]
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:726) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext.access$000(LoginContext.java:194) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574) ~[na:na]
	at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:52) ~[kafka-clients-1.0.2.jar:na]
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:53) ~[kafka-clients-1.0.2.jar:na]
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:82) ~[kafka-clients-1.0.2.jar:na]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:103) ~[kafka-clients-1.0.2.jar:na]
	... 19 common frames omitted
Caused by: sun.security.krb5.RealmException: KrbException: Cannot locate default realm
	at java.security.jgss/sun.security.krb5.Realm.getDefault(Realm.java:67) ~[java.security.jgss:na]
	at java.security.jgss/sun.security.krb5.PrincipalName.<init>(PrincipalName.java:462) ~[java.security.jgss:na]
	at java.security.jgss/sun.security.krb5.PrincipalName.<init>(PrincipalName.java:471) ~[java.security.jgss:na]
	at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:683) ~[jdk.security.auth:na]
	... 31 common frames omitted
Caused by: sun.security.krb5.KrbException: Cannot locate default realm
	at java.security.jgss/sun.security.krb5.Config.getDefaultRealm(Config.java:1155) ~[java.security.jgss:na]
	at java.security.jgss/sun.security.krb5.Realm.getDefault(Realm.java:63) ~[java.security.jgss:na]
	... 34 common frames omitted

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-kafka#460
