### ISSUE TITLE
Binding specific error handler is load balanced with the LoggingHandler

### ISSUE THREAD

**Issue by b-dzoba** [spring-cloud/spring-cloud-stream#1510]
I'm trying to run example from https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_application_error_handling. I expect to get output "Handling ERROR" for every message sent to RabbitMQ exchange "mydestination.mygroup". But the error method is called only for every other message. For example, when I send 2 messages to  "mydestination.mygroup", I get output
```
Handling ERROR
2018-10-17 16:11:52.591 ERROR 107148 --- [ation.mygroup-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessagingException: Exception thrown while invoking com.example.demo.DemoApplication#handle[1 args]; nested exception is java.lang.RuntimeException: BOOM!, failedMessage=GenericMessage [payload=byte[4], headers={amqp_receivedDeliveryMode=NON_PERSISTENT, amqp_receivedExchange=mydestination, amqp_deliveryTag=2, amqp_consumerQueue=mydestination.mygroup, amqp_redelivered=false, id=75628627-fda7-56ce-09de-b129402c9775, amqp_consumerTag=amq.ctag-iQvUOHy5f-KXUXt5d-ZoVg, contentType=application/json, timestamp=1539781912587}]
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:63)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:123)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:165)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:445)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$600(AmqpInboundChannelAdapter.java:58)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.createAndSend(AmqpInboundChannelAdapter.java:237)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.onMessage(AmqpInboundChannelAdapter.java:204)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1477)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1400)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1387)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1366)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:817)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:801)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:77)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1042)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: BOOM!
	at com.example.demo.DemoApplication.handle(DemoApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
	... 25 more
```
Instead of
```
Handling ERROR
Handling ERROR
```

Code and properties:
```
@SpringBootApplication
@EnableBinding(Sink.class)
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	@StreamListener(Sink.INPUT)
	public void handle(Object value) {
		throw new RuntimeException("BOOM!");
	}

	@ServiceActivator(inputChannel = "mydestination.mygroup.errors")
	public void error(Message<?> message) {
		System.out.println("Handling ERROR");
	}
}
```
spring.cloud.stream.bindings.input.destination=mydestination
spring.cloud.stream.bindings.input.group=mygroup
spring.cloud.stream.bindings.input.consumer.max-attempts=1

**Comment by olegz** [comment]
@b-dzoba I was able to reproduce it and we're looking into that. Stay tuned

**Comment by garyrussell** [comment]
This is a known issue; the `@ServiceActivator` defines the input channel as a `DirectChannel` if it doesn't exist.

You need an explicit `@Bean` declaration of `mydestination.mygroup.errors` as a `PublishSubscribeChannel`.

**Comment by garyrussell** [comment]
We should probably add a warning (or throw an `IllegalStateException`) in the abstract binder here, if the existing bean is not pub/sub...

```java
		if (getApplicationContext().containsBean(errorChannelName)) {
			Object errorChannelObject = getApplicationContext().getBean(errorChannelName);
			if (!(errorChannelObject instanceof SubscribableChannel)) {
				throw new IllegalStateException(
						"Error channel '" + errorChannelName + "' must be a SubscribableChannel");
			}
			errorChannel = (SubscribableChannel) errorChannelObject;
		}
		else {
			errorChannel = new BinderErrorChannel();
			this.registerComponentWithBeanFactory(errorChannelName, errorChannel);
			errorChannel = (LastSubscriberAwareChannel) beanFactory.initializeBean(errorChannel, errorChannelName);
		}
```

**Comment by garyrussell** [comment]
The logging handler is not added; we bridge the error channel to the global `errorChannel` so a user can choose a discrete method for each `@StreamListener` or a single error handler method for all inputs. So the round robin is between the user method and the bridge.

So, we either need to enforce the pub/sub channel, or (somehow) force the bindings to be created before any user-defined endpoints.

**Comment by artembilan** [comment]
Can't we *wire-tap* then to the global `errorChannel` instead, when there is already a subscriber to the specific error channel?

**Comment by garyrussell** [comment]
Yes; that would work too.

**Comment by olegz** [comment]
The actual problem is with the BridgeHandler which essentially becomes a second handler, so it load balances between the user provided handler and the bridge handler so the message goes to the global error channel and then to LoggingHandler. So the real bug and the fix is the registration of BridgeHandler which should only be created and subscribed if there are no handlers already subscribed.

**Comment by b-dzoba** [comment]
> You need an explicit @Bean declaration of mydestination.mygroup.errors as a PublishSubscribeChannel.

This fixes load balancing, but does not disable LoggingHandler.

I ended up using IntegrationFlow bean which works exactly as expected.
```
@Bean
public IntegrationFlow errorFlow(@Value("${spring.cloud.stream.bindings.input.destination}.${spring.cloud.stream.bindings.input.group}.errors") String errorChannel) {
    return IntegrationFlows.from(errorChannel, true)
        .handle("demoApplication", "error")
	.get();
}
```

**Comment by artembilan** [comment]
Right, because the `IntegrationFlows.from(errorChannel, true)` is an equivalent for the `FixedSubscriberChannel` and extra subscriber is just ignored:
```
	public boolean subscribe(MessageHandler handler) {
		if (handler != this.handler && this.logger.isDebugEnabled()) {
			this.logger.debug(this.getComponentName() + ": cannot be subscribed to (it has a fixed single subscriber).");
		}
		return false;
	}
```

**Comment by olegz** [comment]
There is actually another issue which we should really think about. If we create `@Input/@Output` as `DirectChannel`s, have we ever intended to allow multiple subscribers?

**Comment by olegz** [comment]
So I am about to push a fix, so here is the summary:

1. If `errorChannel` is a `DirectChannel` then after a first subscription nothing else is going to be subscribed to it. That includes the `BridgeHandler`. In the case of above example this implies that user has taken a full control of error handling.
2. If `errorChannel` is a `PublishSubscribeChannel`, then it's business as usual (as it were)
3. The `#2` can be forced by following suggestion from Gary and to configure `errorChannel` explicitly as `PublishSubscribeChannel`.
