### ISSUE TITLE
Error Handling sometimes is not effective

### ISSUE THREAD

**Issue by dyc87112** [spring-cloud/spring-cloud-stream#1552]
I tried an application to test  error handling with RabbitMQ. 

Application details：

```java
@EnableBinding(TestApplication.TestTopic.class)
@SpringBootApplication
public class TestApplication {

    public static void main(String[] args) {
        SpringApplication.run(TestApplication.class, args);
    }

    @RestController
    static class TestController {

        @Autowired
        private TestTopic testTopic;

        @GetMapping("/sendMessage")
        public String messageWithMQ(@RequestParam String message) {
            testTopic.output().send(MessageBuilder.withPayload(message).build());
            return "ok";
        }

    }

    @Slf4j
    @Component
    static class TestListener {

        @StreamListener(TestTopic.INPUT)
        public void receive(String payload) {
            log.info("Received payload : " + payload);
            throw new RuntimeException("Message consumer failed!");
        }

        @ServiceActivator(inputChannel = "test-topic.stream-exception-handler.errors")
        public void error(Message<?> message) {
            log.info("Message consumer failed, call fallback!");
        }

    }

    interface TestTopic {

        String OUTPUT = "example-topic-output";
        String INPUT = "example-topic-input";

        @Output(OUTPUT)
        MessageChannel output();

        @Input(INPUT)
        SubscribableChannel input();

    }

}
```

when I send a request : `localhost:8080/sendMessage?message=hello`.

first time, error handling is effective：

```
2018-12-12 15:20:54.486  INFO 41646 --- [ption-handler-1] c.d.stream.TestApplication$TestListener  : Received payload : hello
2018-12-12 15:20:54.490  INFO 41646 --- [ption-handler-1] c.d.stream.TestApplication$TestListener  : Message consumer failed, call fallback!
```

second time is not effective，got the exception：

```
2018-12-12 15:21:01.230  INFO 41646 --- [ption-handler-1] c.d.stream.TestApplication$TestListener  : Received payload : hello
2018-12-12 15:21:01.235 ERROR 41646 --- [ption-handler-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessagingException: Exception thrown while invoking com.didispace.stream.TestApplication$TestListener#receive[1 args]; nested exception is java.lang.RuntimeException: Message consumer failed!, failedMessage=GenericMessage [payload=byte[5], headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedRoutingKey=test-topic, amqp_receivedExchange=test-topic, amqp_deliveryTag=2, amqp_consumerQueue=test-topic.stream-exception-handler, amqp_redelivered=false, id=16dd4fb5-aa8d-c7e9-2506-b6aa4f8ab94f, amqp_consumerTag=amq.ctag-TujX8EZehKJDForLo311Mg, contentType=application/json, timestamp=1544599261230}]
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:63)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:158)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:445)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$600(AmqpInboundChannelAdapter.java:60)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.createAndSend(AmqpInboundChannelAdapter.java:240)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.onMessage(AmqpInboundChannelAdapter.java:207)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1414)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1337)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1324)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1303)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:817)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:801)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:77)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1042)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Message consumer failed!
	at com.didispace.stream.TestApplication$TestListener.receive(TestApplication.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
	... 25 more
```

and I found when app started, errors channel subscribe twice

```
2018-12-12 15:02:19.795  INFO 41646 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageHandler testApplication.TestListener.error.serviceActivator
2018-12-12 15:02:19.796  INFO 41646 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Located managed bean 'org.springframework.integration:type=MessageHandler,name=testApplication.TestListener.error.serviceActivator,bean=endpoint': registering with JMX server as MBean [org.springframework.integration:type=MessageHandler,name=testApplication.TestListener.error.serviceActivator,bean=endpoint]
2018-12-12 15:02:19.805  INFO 41646 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase -2147483648
2018-12-12 15:02:19.805  INFO 41646 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {service-activator:testApplication.TestListener.error.serviceActivator} as a subscriber to the 'test-topic.stream-exception-handler.errors' channel
2018-12-12 15:02:19.806  INFO 41646 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'stream-exception-handler-2.test-topic.stream-exception-handler.errors' has 1 subscriber(s).
2018-12-12 15:02:19.806  INFO 41646 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started testApplication.TestListener.error.serviceActivator
2018-12-12 15:02:19.806  INFO 41646 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase -2147482648
2018-12-12 15:02:19.827  INFO 41646 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7c847072: startup date [Wed Dec 12 15:02:19 CST 2018]; parent: org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext@670002
2018-12-12 15:02:19.892  INFO 41646 --- [           main] o.s.c.support.GenericApplicationContext  : Refreshing org.springframework.context.support.GenericApplicationContext@71926a36: startup date [Wed Dec 12 15:02:19 CST 2018]; root of context hierarchy
2018-12-12 15:02:20.014  INFO 41646 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [localhost:5672]
2018-12-12 15:02:20.118  INFO 41646 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Created new connection: rabbitConnectionFactory#22bd2039:0/SimpleConnection@7da31a40 [delegate=amqp://guest@127.0.0.1:5672/, localPort= 57717]
2018-12-12 15:02:20.188  INFO 41646 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'stream-exception-handler-2.example-topic-output' has 1 subscriber(s).
2018-12-12 15:02:20.190  INFO 41646 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2018-12-12 15:02:20.190  INFO 41646 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2018-12-12 15:02:20.190  INFO 41646 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'stream-exception-handler-2.errorChannel' has 1 subscriber(s).
2018-12-12 15:02:20.190  INFO 41646 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started _org.springframework.integration.errorLogger
2018-12-12 15:02:20.190  INFO 41646 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147482647
2018-12-12 15:02:20.203  INFO 41646 --- [           main] c.s.b.r.p.RabbitExchangeQueueProvisioner : declaring queue for inbound: test-topic.stream-exception-handler, bound to: test-topic
2018-12-12 15:02:20.228  INFO 41646 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'stream-exception-handler-2.test-topic.stream-exception-handler.errors' has 2 subscriber(s).
```

Maybe it is a bug ?

**Comment by olegz** [comment]
It was a bug but it was fixed. What version of spring-cloud-stream you are using?

**Comment by dyc87112** [comment]
2.0.1.RELEASE

**Comment by olegz** [comment]
Yeah, you need to upgrade to 2.1.0.RC2 (or RC3 which will be coming out today).

**Comment by dyc87112** [comment]
thanks
