### ISSUE TITLE
AvroSchemaRegistryClientMessageConverter should attempt to create caches, or document them

### ISSUE THREAD

**Issue by dmarmugi** [spring-cloud/spring-cloud-stream#1571]
Spun off from #1566: 
The AvroSchemaRegistryClientMessageConverter uses these caches: 
```java
	public static final String CACHE_PREFIX = "org.springframework.cloud.stream.schema";
	public static final String REFLECTION_CACHE_NAME = CACHE_PREFIX + ".reflectionCache";
	public static final String SCHEMA_CACHE_NAME = CACHE_PREFIX + ".schemaCache";
	public static final String REFERENCE_CACHE_NAME = CACHE_PREFIX + ".referenceCache";
```

I suggest either or both of the following:
* Document that these caches are required 
* Enhance the converter to attempt to auto-create these caches if missing.

**Comment by olegz** [comment]
Given the comment i left on #1556 more feedback is required

**Comment by dmarmugi** [comment]
https://github.com/dmarmugi/schemaregistryclient-redis-sample/tree/caffeine

I'm still seeing this (using caffeine as the cache provider): if I don't declare the caches directly (https://github.com/dmarmugi/schemaregistryclient-redis-sample/blob/caffeine/src/main/resources/application.yml#L3 vs https://github.com/dmarmugi/schemaregistryclient-redis-sample/blob/caffeine/src/main/resources/application.yml#L4) 

then I get an NPE here: https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/avro/AvroSchemaRegistryClientMessageConverter.java#L354-L355: 


```
Caused by: java.lang.NullPointerException: null
	at org.springframework.cloud.stream.schema.avro.AvroSchemaRegistryClientMessageConverter.registerSchema(AvroSchemaRegistryClientMessageConverter.java:355)
	at org.springframework.cloud.stream.schema.avro.AvroSchemaRegistryClientMessageConverter.lambda$afterPropertiesSet$3(AvroSchemaRegistryClientMessageConverter.java:211)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.springframework.cloud.stream.schema.avro.AvroSchemaRegistryClientMessageConverter.afterPropertiesSet(AvroSchemaRegistryClientMessageConverter.java:203)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741)
```

**Comment by olegz** [comment]
What version of spring-cloud-stream you are referring to?  I can't correlate line 355 to anything of significance going back to 2.1.x and 2.0.x didn't even have that many lines.

**Comment by olegz** [comment]
I think I figured out versioning issue. . . anyway

Also, based on the comment I left in #1566 _"...First if you look at implementation of the cache manager (`RedisCacheManager` for your case), they do create caches if they are missing, so I can't reproduce NPE you're referring to..."_
Basically what I am trying to say is that it is the responsibility of the CacheManager to pre-create caches. Some do and some perhaps don't. I do not believe we have to be concerned with that at the stream level. 
I am going to put an assertion to avoid NPE and log a more meaningful message. That's about the best we can do. I'll back port it as well to 2.1.x

**Comment by dmarmugi** [comment]
Thanks @olegz , that assert message is great
