### ISSUE TITLE
Creating EvaluationContext with no beanFactory warning

### ISSUE THREAD

**Issue by Walliee** [spring-cloud/spring-cloud-stream#1621]
Due to a [recent change](https://github.com/spring-projects/spring-integration/commit/d37e6562d8259fb760a5c5a0e3c4f03396673e33#diff-fe353c7d6f819b243595a127bc5916a5) introduced to Spring Integration's [AbstractMessageSource](https://github.com/spring-projects/spring-integration/blob/master/spring-integration-core/src/main/java/org/springframework/integration/endpoint/AbstractMessageSource.java), when using a `PollableMessageSource`, the following warning is logged on startup:

```
2019-02-28 00:58:20.342  WARN 7687 --- [   scheduling-1] o.s.i.expression.ExpressionUtils         : Creating EvaluationContext with no beanFactory

java.lang.RuntimeException: No beanFactory
	at org.springframework.integration.expression.ExpressionUtils.createStandardEvaluationContext(ExpressionUtils.java:86) [spring-integration-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.integration.util.AbstractExpressionEvaluator.getEvaluationContext(AbstractExpressionEvaluator.java:116) [spring-integration-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.integration.util.AbstractExpressionEvaluator.getEvaluationContext(AbstractExpressionEvaluator.java:102) [spring-integration-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.integration.endpoint.AbstractMessageSource.evaluateHeaders(AbstractMessageSource.java:225) [spring-integration-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.integration.endpoint.AbstractMessageSource.buildMessage(AbstractMessageSource.java:166) [spring-integration-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.integration.endpoint.AbstractMessageSource.receive(AbstractMessageSource.java:160) [spring-integration-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) [spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) [spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultPollableMessageSource$1ReceiveAdvice.invoke(DefaultPollableMessageSource.java:110) [spring-cloud-stream-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) [spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at com.sun.proxy.$Proxy91.receive(Unknown Source) [na:na]
	at org.springframework.cloud.stream.binder.DefaultPollableMessageSource.receive(DefaultPollableMessageSource.java:286) [spring-cloud-stream-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultPollableMessageSource.poll(DefaultPollableMessageSource.java:196) [spring-cloud-stream-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultPollableMessageSource.poll(DefaultPollableMessageSource.java:65) [spring-cloud-stream-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at com.example.nobeanfactorywarning.NoBeanFactoryWarningApplication.poller(NoBeanFactoryWarningApplication.java:31) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
```

This happens because the `MessageSource` created for the `PollableMessageSource` is never registered with the Spring's application context and therefore even though `AbstractMessageSource`(via `AbstractExpressionEvaluator`) is `BeanFactoryAware`, bean factory is never set.

Possible solution could be to either register the bean with bean factory or manually set bean factory on  AbstractMessageSource implementation instantiation.

Test demonstrating this can be found [here](https://github.com/Walliee/no-bean-factory-warning).

Creating this here instead of the Kafka Binder repository because I suspect a similar issue would exists for Rabbit Binder too, although I haven't verified it.

SCS + Kafka binder 2.1.0.RELEASE, Spring Integration 5.1.3.RELEASE

**Comment by garyrussell** [comment]
Actually, the problem was always there (non-populated BF); that change, however, exposed the issue because it now always fetches an evaluation context even if there are no header expressions (which is the case here in Stream). So, as well as fixing the property population here, we should fix SI to only get an evaluation context if one is actually needed.
