### ISSUE TITLE
How to support Function<Mono, Mono>?

### ISSUE THREAD

**Issue by hopefulwalker** [spring-cloud/spring-cloud-stream#1622]
I'm a newbie for spring cloud function and not sure whether I should post the issue here or in spring-cloud-stream.

When I define a function as following:
```
@SpringBootApplication
@EnableBinding(Processor.class)
public class ToolApplication {
    public static void main(String[] args) {
        SpringApplication.run(ToolApplication.class, "--spring.cloud.stream.function.definition=echo");
    }
    @Bean
    public Function<Flux<BizLogRecord>, Flux<BizLogRecord>> echo() {
        return flux -> flux.map(value -> value);
    }
}
```
The application.yml file:
```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.X.X:9092
      bindings:
        input:
          destination: bizlogrequest
        output:
          destination: bizlogreply
```
everything works as expected.
But when I change the function definition to the following:
```
    @Bean
    public Function<Mono<BizLogRecord>, Mono<BizLogRecord>> echo() {
        return flux -> flux.map(value -> value);
    }
```
It will report the exception: 
```
java.lang.ClassCastException: reactor.core.publisher.FluxMapFuseable cannot be cast to reactor.core.publisher.Mono
	at org.springframework.cloud.function.core.FluxToMonoFunction.apply(FluxToMonoFunction.java:51) ~[spring-cloud-function-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.function.core.FluxToMonoFunction.apply(FluxToMonoFunction.java:33) ~[spring-cloud-function-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at reactor.core.publisher.Flux.transform(Flux.java:8542) ~[reactor-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.cloud.stream.function.FunctionInvoker.lambda$apply$1(FunctionInvoker.java:108) ~[spring-cloud-stream-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:368) [reactor-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:244) [reactor-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at reactor.core.publisher.FluxRetry$RetrySubscriber.onNext(FluxRetry.java:79) ~[reactor-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) ~[reactor-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at reactor.core.publisher.FluxPublish$PublishSubscriber.drain(FluxPublish.java:465) ~[reactor-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at reactor.core.publisher.FluxPublish$PublishSubscriber.onNext(FluxPublish.java:262) ~[reactor-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:593) ~[reactor-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:151) ~[reactor-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.integration.channel.FluxMessageChannel.doSend(FluxMessageChannel.java:65) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:431) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.doProduceOutput(AbstractMessageProducingHandler.java:284) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:265) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:223) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:129) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:162) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:205) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:369) ~[spring-integration-kafka-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$400(KafkaMessageDrivenChannelAdapter.java:74) ~[spring-integration-kafka-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:431) ~[spring-integration-kafka-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:402) ~[spring-integration-kafka-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.lambda$onMessage$0(RetryingMessageListenerAdapter.java:120) ~[spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) ~[spring-retry-1.2.3.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:211) ~[spring-retry-1.2.3.RELEASE.jar:na]
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:114) ~[spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:40) ~[spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:1220) ~[spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:1213) ~[spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1174) ~[spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1155) ~[spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1096) ~[spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:924) ~[spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:740) ~[spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:689) ~[spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
```

Does it support to defined the function as Function<Mono, Mono>?

**Comment by olegz** [comment]
Actually, now since I got a chance to look into this I wonder what are you gaining via `Function<Mono, Mono>`? 
Let me set the scope a bit. . .
In the context of `Supplier`, `Function` and `Consumer`, all three could be looked at as functions wit the following type signatures: `Function<Mono<Void>, Flux>`, `Function<Flux, Flux>` and `Function<Flux, Mono<Void>>` respectively. 
However, if the generic type of Mono is anything other then `Void` I am wondering what would you gain from it?
For example, what if you have the following:
```
public Function<String, String> fooBar() {
      return foo -> Mono.just(foo).map(v -> v.toUpperCase()).block();
}
```
I mean given the fact that this is a Mono, we would still have to handle it internally as your basic MessageHandler since you would end up with new `Mono` per each `Message`. We can certainly do it with additional `MessageConverter`, but before we do anything I'd love to learn more.

**Comment by hopefulwalker** [comment]
For my case , I define a function to save the message into mongoDB based on reactive stream driver.
the internal interface is 
```
public interface LogRecordSaver {
    Mono<BizLogRecord> save(Mono<BizLogRecord> record);
}
```
and my current work around is 
```
   @Bean
    public Function<Flux<BizLogRecord>, Flux<BizLogRecord>> saver(ReactiveMongoTemplate template) {
        return flux -> LogRecordSaver.save(flux.next()).flux();
    }
```
If it support Function<Mono, Mono>, I can use it directly, something like:
```
return mono ->LogRecordSaver.save(mono);
```
Any suggestion for this scenario would be appreciated.

**Comment by olegz** [comment]
Why do you call it workaround? That is the proper use of reactive API. It is not your typical `MessageHandler` which is invoked on arrival of every `Message`. This is a _declarative_ function that is invoked only once when stream is created.

Anyway, here is a slightly better way of doing it
```
public Function<Flux<BizLogRecord>, Flux<BizLogRecord>> saver(ReactiveMongoTemplate template) {
      return flux -> flux.doOnNext(bizLogRecord ->LogRecordSaver.save(bizLogRecord) );
}
```

**Comment by hopefulwalker** [comment]
Thanks.
The interface should change to the following according to your suggestion.
```
public interface LogRecordSaver {
    Mono<BizLogRecord> save(BizLogRecord record);
}
```
Is it the best practice to define the parameter as Mono/Flux or just the object for this scenerio?

**Comment by olegz** [comment]
I am still trying to understand what are you getting out of `Function<Mono<BizLogRecord>, Mono<BizLogRecord>>`. If you're passing `Mono` you essentially implying singularity - _Mono per invocation_ as there is really no stream of data. If so, why not then `Function<BizLogRecord>, BizLogRecord>`. 
There is no best practice, rather a question what programming model you want to chose - _reactive_ or _imperative_

**Comment by hopefulwalker** [comment]
I am trying to use reactive model.
for `Function<BizLogRecord, BizLogRecord>`, I have to call `block()` to get the `BizLogRecord` .
I'm not sure, but I think it's better to let the framework to subscribe it? 
```
    @Bean
    public Function<BizLogRecord, BizLogRecord> saver(ReactiveMongoTemplate template) {
        return record -> {
            return mongoLogRecordService(template).save(record).block();
        };
    }
```
one more thing, the `Mono `is actually return by `ReactiveMongoTemplate` which retrieved data from mongoDb.

**Comment by olegz** [comment]
I am still not clear. What does Mongo have to do with anything in he context of this question and spring-cloud-stream? 

Function input and output parameters only deal with messages _consumed from_ or _send to_ destinations exposed by the binders (e.g., Rabbit, Kafka etc). So`Function<BizLogRecord, BizLogRecord>` and `Function<Flux<BizLogRecord >, Flux<BizLogRecord>>` gives you two different programming models (imperative or reactive respectively), yet the results are absolutely  ***identical*** when it comes to consuming and/or sending messages to destinations managed by the binders.

**Comment by hopefulwalker** [comment]
Sorry for the late feedback.
I'm just let the framework to handle subscribing works.
When I using reactive driver for  mongo, I need to subscribe it or call block method.  and when I use `Function<Flux<BizLogRecord >, Flux<BizLogRecord>>`， the frame could do this kind of job for me.

I still need to learn more about how to use  reactive programming.

**Comment by olegz** [comment]
Based on the discussion I am going to close this issue as there is no action to be taken at the spring-cloud-stream level. Even if at some point we were to support it it would be in spring-cloud-function.
