### ISSUE TITLE
Implicit function binding detection breaks when Function beans without default constructor are present 

### ISSUE THREAD

**Issue by Walliee** [spring-cloud/spring-cloud-stream#1677]
Looks like implicit function binding detection introduced in 2.2.0.M1 breaks when "functional" bean definitions without a default constructor are present. Basically, `FunctionCatalog` creation fails if a bean like this is present.

```
@Component
public static class StringSuppiler implements Supplier<String> {
	private String field;

	public StringSuppiler(String field) {
		this.field = field;
	}

	@Override
	public String get() {
		return null;
	}
}
```

**Stacktrace:**
```
2019-03-27 00:59:24.457 ERROR 34081 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'implicitFunctionBinder' defined in class path resource [org/springframework/cloud/stream/config/BinderFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'implicitFunctionBinder' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionCatalog' defined in class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'implicitFunctionBinderIssueApplication.StringSuppiler' defined in file [/Users/Walliee/IdeaProjects/OpenSource/implicit-function-binder-issue/target/classes/com/walliee/ImplicitFunctionBinderIssueApplication$StringSuppiler.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.walliee.ImplicitFunctionBinderIssueApplication$StringSuppiler]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.walliee.ImplicitFunctionBinderIssueApplication$StringSuppiler.<init>()
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1305) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1144) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:179) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at com.walliee.ImplicitFunctionBinderIssueApplication.main(ImplicitFunctionBinderIssueApplication.java:15) [classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionCatalog' defined in class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'implicitFunctionBinderIssueApplication.StringSuppiler' defined in file [/Users/Walliee/IdeaProjects/OpenSource/implicit-function-binder-issue/target/classes/com/walliee/ImplicitFunctionBinderIssueApplication$StringSuppiler.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.walliee.ImplicitFunctionBinderIssueApplication$StringSuppiler]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.walliee.ImplicitFunctionBinderIssueApplication$StringSuppiler.<init>()
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 18 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'implicitFunctionBinderIssueApplication.StringSuppiler' defined in file [/Users/Walliee/IdeaProjects/OpenSource/implicit-function-binder-issue/target/classes/com/walliee/ImplicitFunctionBinderIssueApplication$StringSuppiler.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.walliee.ImplicitFunctionBinderIssueApplication$StringSuppiler]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.walliee.ImplicitFunctionBinderIssueApplication$StringSuppiler.<init>()
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1287) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:602) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:590) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$BeanFactoryFunctionCatalog.afterPropertiesSet(ContextFunctionCatalogAutoConfiguration.java:102) ~[spring-cloud-function-context-2.1.0.M1.jar:2.1.0.M1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1821) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 29 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.walliee.ImplicitFunctionBinderIssueApplication$StringSuppiler]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.walliee.ImplicitFunctionBinderIssueApplication$StringSuppiler.<init>()
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:83) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1279) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 41 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.walliee.ImplicitFunctionBinderIssueApplication$StringSuppiler.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_191]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[na:1.8.0_191]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:78) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 42 common frames omitted
```

A sample recreating this issue can be found [here](https://github.com/Walliee/implicit-function-binder-issue).

**Comment by olegz** [comment]
Actually I do not see any issue at all. Actually I'd be surprised if it did not result in exception. . 
Think about it:
```
public StringSuppiler(String field) {...
```
You instructing Spring to create a bean while injecting String parameter during the construction. What should that string be?
Also, look at the stack trace, you'll see that the exception itself is `BeanCreationException` which doesn't have anything to do with either s-c-stream or s-c-function...

**Comment by Walliee** [comment]
@olegz I updated the sample to add the a field bean but the application still fails to start up. 

If you comment out the SCS dependencies and run the app, it will start up.

https://github.com/Walliee/implicit-function-binder-issue/blob/222baa4f9656197d5d41670ace147e377e4a5131/pom.xml#L24-L32

I think the issue is that `ContextFunctionCatalogAutoConfiguration` (during `FunctionCatalog` construction), tries to initialize all Function/Supplier/Consumer bean definitions it can possibly find and the `SimpleInstantiationStrategy` tries to do so using a no-args constructor.

**Comment by olegz** [comment]
I am still not following when you say "_. . .I updated the sample to add a field bean. . ."_
This `public StringSuppiler(String field)` should not work unless there is a bean of type String is available to be injected. Are you saying that it does not work with default constructor  either - `public StringSuppiler()`?

**Comment by Walliee** [comment]
I realize that this is more a s-c-function issue but if someone is using s-c-function directly and has the need to have functional bean definition that don't have default constructors, they can simply provide their own FunctionCatalog to avoid this situation.

However, requiring s-c-stream based applications to do that (especially if they are not using the functional/reactive aspect), seems a bit off. Hence, I created the issue here. 

Happy to move this issue to s-c-function if that's where it belongs.

**Comment by olegz** [comment]
Definitely move to s-c-f, but I am still wondering as I see no symptoms leading to any s-c-f errors in your stack trace.

**Comment by Walliee** [comment]
I was referring to the sample I created [here](https://github.com/Walliee/implicit-function-binder-issue). Are you running this sample?

https://github.com/Walliee/implicit-function-binder-issue/blob/master/src/main/java/com/walliee/ImplicitFunctionBinderIssueApplication.java

**Comment by olegz** [comment]
I'll look at it later today
