### ISSUE TITLE
DefaultBinderFactory breaks when spring.main.web-application-type is set

### ISSUE THREAD

**Issue by Walliee** [spring-cloud/spring-cloud-stream#1708]
The `private <T> Binder<T, ConsumerProperties, ProducerProperties> getBinderInstance(String configurationName)` method in `DefaultBinderFactory`, tries to get an instance of `Binder` by bootstrapping a mini boot application. 
The web-mode is set to NONE. 
https://github.com/spring-cloud/spring-cloud-stream/blob/b5a64eac1406369d21ae2281519caf08404555b5/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java#L257-L261

However, a few lines later the parent application's environment is also added to the mini boot application.
https://github.com/spring-cloud/spring-cloud-stream/blob/b5a64eac1406369d21ae2281519caf08404555b5/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java#L282-L289

If the parent application has the `spring.main.web-application-type` set to REACTIVE, then when the mini boot application is initialized, the web-mode gets set to REACTIVE and the creation of binder and overall the parent application fails with the following exception. A similar issue would happen if the web-application-type was set to SERVLET.

```
2019-05-09 00:18:33.368 ERROR 12983 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing ReactiveWebServerFactory bean.
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:82) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:67) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:291) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:192) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:130) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:337) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:229) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindOutputs(BindableProxyFactory.java:287) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.doStartWithBindable(OutputBindingLifecycle.java:58) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_191]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:48) ~[spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:34) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.finishRefresh(ReactiveWebServerApplicationContext.java:121) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:67) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at com.walliee.scsreactive.ScsReactiveApplication.main(ScsReactiveApplication.java:13) ~[classes/:na]
Caused by: org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing ReactiveWebServerFactory bean.
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.getWebServerFactory(ReactiveWebServerApplicationContext.java:106) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:90) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:79) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	... 31 common frames omitted
```

I've created a sample [here](https://github.com/Walliee/scs-reactive-app-binder-issue) that reproduces the issue. 
The application starts fine when `spring.main.web-application-type=REACTIVE` in the properties file is commented out but fails when it's there.

**Comment by olegz** [comment]
So, what you're saying is we need to completely ignore _any_ web property for child context, correct? I think I agree. . .

**Comment by Walliee** [comment]
Setting the webApplicationType to NONE was supposed to do just that but because the environment for the child application is inherited, it’s possible for it to be  unintentionally overridden to either be REACTIVE or SERVLET.

If it can be ensured that webApplicationType will always be NONE for the child context then, I think, we don’t need to ignore any other web properties?

**Comment by Numbernick** [comment]
I have the same problem as discribed in my wrong addressed issue https://github.com/spring-projects/spring-integration/issues/2933 .
