### ISSUE TITLE
@StreamListener("errorChannel") not working

### ISSUE THREAD

**Issue by mjmunizsa** [spring-cloud/spring-cloud-stream#1737]
I want to handle error with errorChannel subscriber for all channels.

I'm using spring-cloud-stream-binder-aws-kinesis.

I use a particular interface for EnableBinding (StreamProcessor.class):
```
public interface StreamProcessor {

	@Input
	SubscribableChannel inputBar();

	@Input
	SubscribableChannel inputFoo();

```
I have implemented two StreamListeners:
```
@EnableBinding(StreamProcessor.class)
public class FooConsumer {

	@StreamListener("inputFoo")
	public void inputFoo(Message<?> inputMessage) {
              throw new RuntimeException("Boom");
        }
}
```
```
@EnableBinding(StreamProcessor.class)
public class BarConsumer {

	@StreamListener("inputBar")
	public void inputBar(Message<?> inputMessage) {
              throw new RuntimeException("Boom");
        }
}
```
And  finally I have implemented a streamListener for the error channel for the two previous channels. 
```
@EnableBinding(StreamProcessor.class)
public class StreamConsumerError{

	@StreamListener("errorChannel")
	public void error(Message<?> message) {
		System.out.println("Handling ERROR: " + message);
	}

}
```
When I run the application it never goes through the Channel error and an exception is launched with the message:

```
Consider to use 'errorChannel' flow for the compensation logic.
org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Unrecognized token 'org': was expecting ('true', 'false' or 'null')
```

I have reviewed the application boot log and the Channel error subscriber is displayed:
```
Channel 'Events hub consumer-1.errorChannel' has 1 subscriber(s).
Channel 'Events hub consumer-1.inputFoo' has 1 subscriber(s).
Channel 'Events hub consumer-1.inputBar' has 1 subscriber(s).


Registering MessageChannel inputFoo
Registering MessageChannel inputBar
Registering MessageChannel errorChannel
```

This error seems similar to the one reported in the issue: https://github.com/spring-cloud/spring-cloud-stream/issues/1618

I am using kinesis instead of rabbit, specifically version 1.1.0. I have tried 1.2.0 and I also get the same error.

Sorry for my ignorance on this subject, but is that I'm starting with spring cloud stream.

Thanks

**Comment by artembilan** [comment]
Please, share more logs and more stack trace on the matter.

The message `Consider to use 'errorChannel' flow for the compensation logic.` is something what is not possible in Spring Cloud Stream. When binder registers consume endpoint it does:
```

		ErrorInfrastructure errorInfrastructure = registerErrorInfrastructure(destination,
				consumerGroup, properties);
		adapter.setErrorMessageStrategy(ERROR_MESSAGE_STRATEGY);
		adapter.setErrorChannel(errorInfrastructure.getErrorChannel());
		return adapter;
```
That `errorInfrastructure.getErrorChannel()` is definitely not `null` for the logic like:
```
try {
				sendMessage(messageToSend);
			}
			catch (Exception e) {
				logger.info("Got an exception during sending a '" + messageToSend + "'" +
						"\nfor the '" + rawRecord + "'.\n" +
						"Consider to use 'errorChannel' flow for the compensation logic.", e);
			}
...
	protected void sendMessage(Message<?> messageArg) {
		Message<?> message = messageArg;
		if (message == null) {
			throw new MessagingException("cannot send a null message");
		}
		if (this.shouldTrack) {
			message = MessageHistory.write(message, this, this.getMessageBuilderFactory());
		}
		try {
			this.messagingTemplate.send(getOutputChannel(), message);
		}
		catch (RuntimeException e) {
			if (!sendErrorMessageIfNecessary(message, e)) {
				throw e;
			}
		}
	}
...
protected final boolean sendErrorMessageIfNecessary(Message<?> message, RuntimeException exception) {
		MessageChannel channel = getErrorChannel();
		if (channel != null) {
			this.messagingTemplate.send(channel, buildErrorMessage(message, exception));
			return true;
		}
		return false;
	}
```

Please, share with us very simple sample to let us to reproduce and play with.

Thank you for understanding!

**Comment by mjmunizsa** [comment]
This is trace log complete:
```
2019-06-19 16:33:14.787  INFO [Events hub consumer,,,] 19908 --- [esis-consumer-1] a.i.k.KinesisMessageDrivenChannelAdapter : Got an exception during sending a 'GenericMessage [payload=byte[3], headers={aws_shard=shardId-000000000000, id=11e38755-4ed2-3a10-653c-71ede04e66b3, contentType=application/json, aws_receivedPartitionKey=1, aws_receivedStream=melia-aws-dev-dl-eventshub-local1, aws_receivedSequenceNumber=49596646103146062311772753519108014660237444044684263426, timestamp=1560954777719}]'
for the '{SequenceNumber: 49596646103146062311772753519108014660237444044684263426,ApproximateArrivalTimestamp: Wed Jun 19 16:32:55 CEST 2019,Data: java.nio.HeapByteBuffer[pos=0 lim=3 cap=3],PartitionKey: 1,}'.
Consider to use 'errorChannel' flow for the compensation logic.

org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Unrecognized token 'org': was expecting ('true', 'false' or 'null')
 at [Source: (String)"org.springframework.messaging.MessagingException: Exception thrown while invoking com.melia.events.hub.consumer.service.consumer.FooConsumer#inputFoo[1 args]; nested exception is java.lang.RuntimeException: Boom, failedMessage=GenericMessage [payload=byte[3], headers={spanTraceId=46d364fb9468debd, spanId=46d364fb9468debd, nativeHeaders={spanTraceId=[46d364fb9468debd], spanId=[279c1eb2d3d0c46b], spanSampled=[1], spanParentSpanId=[641f56b3d374fd5c], X-B3-TraceId=[46d364fb9468debd], X-B3-SpanId=[27"[truncated 461 chars]; line: 1, column: 4]; nested exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'org': was expecting ('true', 'false' or 'null')
 at [Source: (String)"org.springframework.messaging.MessagingException: Exception thrown while invoking com.melia.events.hub.consumer.service.consumer.FooConsumer#inputFoo[1 args]; nested exception is java.lang.RuntimeException: Boom, failedMessage=GenericMessage [payload=byte[3], headers={spanTraceId=46d364fb9468debd, spanId=46d364fb9468debd, nativeHeaders={spanTraceId=[46d364fb9468debd], spanId=[279c1eb2d3d0c46b], spanSampled=[1], spanParentSpanId=[641f56b3d374fd5c], X-B3-TraceId=[46d364fb9468debd], X-B3-SpanId=[27"[truncated 461 chars]; line: 1, column: 4]
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:234)
	at org.springframework.cloud.stream.converter.ApplicationJsonMessageMarshallingConverter.convertFromInternal(ApplicationJsonMessageMarshallingConverter.java:97)
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:181)
	at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:70)
	at org.springframework.cloud.stream.config.SmartMessageMethodArgumentResolver.convertPayload(SmartMessageMethodArgumentResolver.java:110)
	at org.springframework.cloud.stream.config.SmartMessageMethodArgumentResolver.resolveArgument(SmartMessageMethodArgumentResolver.java:81)
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:117)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:147)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:116)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:123)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:162)
	at org.springframework.integration.dispatcher.BroadcastingDispatcher.invokeHandler(BroadcastingDispatcher.java:224)
	at org.springframework.integration.dispatcher.BroadcastingDispatcher.dispatch(BroadcastingDispatcher.java:180)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:431)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.doProduceOutput(AbstractMessageProducingHandler.java:284)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:265)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:223)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:129)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:162)
	at org.springframework.integration.dispatcher.BroadcastingDispatcher.invokeHandler(BroadcastingDispatcher.java:224)
	at org.springframework.integration.dispatcher.BroadcastingDispatcher.dispatch(BroadcastingDispatcher.java:180)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendErrorMessageIfNecessary(MessageProducerSupport.java:224)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
	at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter.access$4000(KinesisMessageDrivenChannelAdapter.java:91)
	at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.performSend(KinesisMessageDrivenChannelAdapter.java:1071)
	at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.processRecords(KinesisMessageDrivenChannelAdapter.java:969)
	at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.lambda$processTask$1(KinesisMessageDrivenChannelAdapter.java:896)
	at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ConsumerInvoker.run(KinesisMessageDrivenChannelAdapter.java:1139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'org': was expecting ('true', 'false' or 'null')
 at [Source: (String)"org.springframework.messaging.MessagingException: Exception thrown while invoking com.melia.events.hub.consumer.service.consumer.FooConsumer#inputFoo[1 args]; nested exception is java.lang.RuntimeException: Boom, failedMessage=GenericMessage [payload=byte[3], headers={spanTraceId=46d364fb9468debd, spanId=46d364fb9468debd, nativeHeaders={spanTraceId=[46d364fb9468debd], spanId=[279c1eb2d3d0c46b], spanSampled=[1], spanParentSpanId=[641f56b3d374fd5c], X-B3-TraceId=[46d364fb9468debd], X-B3-SpanId=[27"[truncated 461 chars]; line: 1, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1899)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042)
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:229)
	... 45 common frames omitted
```

I'm going to try to create a small project to test it.
I remind you that I'm using the Kinesis binder, I guess you'll have an AWS account.

Thanks for taking care of my request.

**Comment by olegz** [comment]
Well, this is a conversion exception which means it happens way before the listener method is invoked, hence it is not the type of message that would end up in errorChannel

**Comment by artembilan** [comment]
Well, sounds like you do have a send into the error channel:
```
at org.springframework.integration.endpoint.MessageProducerSupport.sendErrorMessageIfNecessary(MessageProducerSupport.java:224)
```
And that deserialization error is exactly about an attempt to deserialize an `Exception` object as a JSON:
```
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'org': was expecting ('true', 'false' or 'null')
 at [Source: (String)"org.springframework.messaging.MessagingException: Exception thrown while invoking com.melia.events.hub.consumer.service.consumer.FooConsumer#inputFoo[1 args]; nested exception is java.lang.RuntimeException: Boom, failedMessage=GenericMessage [payload=byte[3], headers={spanTraceId=46d364fb9468debd, spanId=46d364fb9468debd, nativeHeaders={spanTraceId=[46d364fb9468debd], spanId=[279c1eb2d3d0c46b], spanSampled=[1], spanParentSpanId=[641f56b3d374fd5c], X-B3-TraceId=[46d364fb9468debd], X-B3-SpanId=[27"[truncated 461 chars]; line: 1, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1899)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042)
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:229)
```

Not sure what is going on, but there is definitely something wrong in the:
```
at org.springframework.cloud.stream.config.SmartMessageMethodArgumentResolver.convertPayload(SmartMessageMethodArgumentResolver.java:110)
at org.springframework.cloud.stream.config.SmartMessageMethodArgumentResolver.resolveArgument(SmartMessageMethodArgumentResolver.java:81)
```

I don't think the issue is related to Kinesis at all. Such a problem may simple has a place independently of the binder.
Anyway, please, share a simple sample: I'm going to test it against `kinesalite`. I'm curious at what point an exception is converted into `toString()`, so the conversion fails meanwhile we really would like to have there an `ErrorMessage` as is.

**Comment by olegz** [comment]
The above error simply means that `MappingJackson2MessageConverter` has been selected but the actual payload is not of the correct type. As Artem said, something is a miss here and we need a way to reproduce it. And yes it is pretty clear that it has nothing to do with Kinesis binder since message conversion happens in core logic

**Comment by mjmunizsa** [comment]
You can close the issue. I have mounted a small project and it seems that it works correctly. 
Clearly there is no problem with the kinesis binder. 

I tried sending a string and an object, and in both cases launching the RuntimeException has gone to the Channel error.

What I don't understand is why in my real project it doesn't work. I guess there's something I don't understand. I will continue to investigate what the problem is ...

Anyway thanks for everything!

**Comment by mjmunizsa** [comment]
I found the problem!
If I change the version of spring-cloud-dependencies to Greenwich.SR1, it works correctly. On the other hand with the version Greenwich.RELEASE gives the error.

I understand that it is an error of the version, is not?

Thanks!
