### ISSUE TITLE
reactor.core.scheduler.Scheduler identified as a Supplier in FunctionTypeUtils

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-stream#1794]
This surfaced in `spring-cloud-gcp`: [this sample](https://github.com/spring-cloud/spring-cloud-gcp/tree/ba20b7cf238d5aced47830a11059024100f95399/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample) started failing at startup with the following stack trace:
```
Caused by: java.lang.IllegalArgumentException: Must be one of Supplier, Function, Consumer or FunctionRegistration. Was interface reactor.core.Disposable
at org.springframework.util.Assert.isTrue(Assert.java:118)
at org.springframework.cloud.function.context.catalog.FunctionTypeUtils.assertSupportedTypes(FunctionTypeUtils.java:362)
at org.springframework.cloud.function.context.catalog.FunctionTypeUtils.getInputType(FunctionTypeUtils.java:176)
at org.springframework.cloud.stream.function.FunctionConfiguration.integrationFlowFromProvidedSupplier(FunctionConfiguration.java:119)
at org.springframework.cloud.stream.function.FunctionConfiguration.standAloneSupplierFlow(FunctionConfiguration.java:105)
```

`spring-cloud-stream version` used is `3.0.0.BUILD-SNAPSHOT`.

The old behavior of `functionCatalog.lookup(functionProperties.getDefinition())` was to return `null`. But with the latest changes in `spring-cloud-stream`/`spring-cloud-function`, the lookup is returning a `spring-cloud-gcp` [scheduler bean](https://github.com/spring-cloud/spring-cloud-gcp/blob/c9107a110b04217cabfde4cdc2c06f4aa888c992/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/pubsub/GcpPubSubReactiveAutoConfiguration.java#L48).

**Comment by olegz** [comment]
Basically at the core of the issue is spring-cloud-function mechanism for discovering default function for cases when name is not provided. While experimental feature to introduce extra convenience to the developers it obviously has side-effects
