### ISSUE TITLE
Functional model ignoring useNativeDecoding in ConsumerProperties

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream#1808]
When setting `useNativeDecoding` to true, it seems that the functional model is ignoring it and trying to use the message converters. 

```
@Bean
public Consumer<Sensor> process()  {
   return input -> logger.info("input: " + input);
}

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: sensor-topic
          consumer:
            useNativeDecoding: true
```

Getting this exception:

```
at [Source: (String)"{"id": "96b6a74b-6d95-4079-85c6-35dfa479a815-v1", "temperature": 1.0866851, "acceleration": 1.4816451, "velocity": 12.7104225}"; line: 1, column: 75] (through reference chain: com.example.Sensor["temperature"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "temperature" (class com.example.Sensor), not marked as
    at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:236)
    at org.springframework.cloud.stream.converter.ApplicationJsonMessageMarshallingConverter.convertFromInternal(ApplicationJsonMessageMarshallingConverter.java:111)
    at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:181)
    at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:172)
    at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:57)
    at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.convertInputValueIfNecessary(BeanFactoryAwareFunctionRegistry.java:644)
    at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.doApply(BeanFactoryAwareFunctionRegistry.java:538)
    at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.apply(BeanFactoryAwareFunctionRegistry.java:442)
    at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:493)
```

**Comment by olegz** [comment]
Addressed with 4c94974261ce16afec79e631efd656c3f948eccb
