### ISSUE TITLE
spring-integration and spring-cloud-stream Greenwich.SR2+ => MessageHandlingException: nested exception is java.lang.ClassCastException: java.util.LinkedHashMap

### ISSUE THREAD

**Issue by guilloume** [spring-cloud/spring-cloud-stream#1832]
### Context

We are using spring-integration for 2 different instances, a producer and a consumer, and spring-cloud-stream is between them.
We use a single exchange topic (in the broker) to send different payload object types between the two instances.

### We experienced the issue when we tried to upgrade from Greenwich.SR1 to SR2/SR3.

```shell
2019-10-25 16:15:01.198  INFO 88619 --- [           main] o.s.i.h.s.MessagingMethodInvokerHelper   : Overriding default instance of MessageHandlerMethodFactory with provided one.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.532 s <<< FAILURE! - in com.skow.common.test.integration.ProducerToConsumerTest
[ERROR] test(com.skow.common.test.integration.ProducerToConsumerTest)  Time elapsed: 0.313 s  <<< ERROR!
org.springframework.integration.transformer.MessageTransformationException: Failed to transform Message; nested exception is org.springframework.messaging.MessageHandlingException: nested exception is java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.skow.common.module.model.DTO, failedMessage=GenericMessage [payload={name=name, property={property=property}}, headers={replyChannel=transform.channel, id=346999f9-ee12-4185-211d-a3a74178d77e, REDO_BEAN=replayTransformer, contentType=application/json, REDO_PAYLOAD={name=name, property={property=property}}, timestamp=1572012901198}]
        at com.skow.common.test.integration.ProducerToConsumerTest.test(ProducerToConsumerTest.java:9)
Caused by: org.springframework.messaging.MessageHandlingException: nested exception is java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.skow.common.module.model.DTO
        at com.skow.common.test.integration.ProducerToConsumerTest.test(ProducerToConsumerTest.java:9)
Caused by: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.skow.common.module.model.DTO
        at com.skow.common.test.integration.ProducerToConsumerTest.test(ProducerToConsumerTest.java:9)
```

### After analyzing code history, we found the below commit is responsible 

```shell
diff --git a/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BinderFactoryConfiguration.java b/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BinderFactoryConfiguration.java
index f76535aa..47acf7c4 100644
 
-       @Bean
+       @Bean(IntegrationContextUtils.MESSAGE_HANDLER_FACTORY_BEAN_NAME)
        public static MessageHandlerMethodFactory messageHandlerMethodFactory(
                        CompositeMessageConverterFactory compositeMessageConverterFactory,
                        @Qualifier(IntegrationContextUtils.ARGUMENT_RESOLVERS_BEAN_NAME) HandlerMethodArgumentResolversHolder ahmar,
```

### Sample project demoing the issue

```shell
git clone https://gitlab.com/n3ur0ns/spring-cloud-stream-integration.git
cd spring-cloud-stream-integration
./mvnw clean verify -P IT -fn 
```

### We found a trick as shown in submodule greenwich-sr3-trick

```java
@Component
public class OnStartup implements ApplicationListener<ContextRefreshedEvent> {

    private final DefaultListableBeanFactory context;

    @Autowired
    public OnStartup(DefaultListableBeanFactory context) {
        this.context = context;
    }

    @Override
    public void onApplicationEvent(ContextRefreshedEvent event) {
        if (context != null && context
            .containsBean(IntegrationContextUtils.MESSAGE_HANDLER_FACTORY_BEAN_NAME)) {
            context.removeBeanDefinition(IntegrationContextUtils.MESSAGE_HANDLER_FACTORY_BEAN_NAME);
        }
    }
}
```

**Comment by sabbyanandan** [comment]
@guilloume: Thank you for the thorough write-up and the reproducible sample! I can locally also see this breaking, as well. I'm going to request @olegz to have a look at the change when he's back from the PTO next week.

In the meantime, perhaps you could switch to Hoxton/Horsham RC1 (RC2 later this week, even).  Please give it a go on this release baseline, and let us know what you find out.

**Comment by olegz** [comment]
I would suggest to try it with 3.0.0.RC2 as I believe that has been addressed albeit indirectly.

**Comment by sabbyanandan** [comment]
Closing this due to no activity.

**Comment by dotw** [comment]
@sabbyanandan I have a similar issue using Hoxton.SR8(3.0.8.RELEASE)

I have 2 instances and one is a producer, another is a consumer.

I'm using `EmiiterProcess<Message<?>>` to send a message like below in the producer
```java
    @Override
    public Product createProduct(Product body) {
        LOG.debug(" Sending create product message for product {}", body.getProductId());
        Message<?> message = MessageBuilder.withPayload(new Event(CREATE, body.getProductId(), body)).setHeader(HEADER_DESTINATION, QUEUE_PRODUCT).build();
        processor.onNext(message);
        return body;
    }
```

In the consumer instance, I'm using the following code to process the message.  The code is broken at the comment line.

```java
@Bean
    public Function<Event<String, Product>, String> handleProductMessage(){
        return message -> {
            LOG.info("Process product message created at {}...", message.getEventCreatedAt());
            switch (message.getEventType()) {

                case CREATE:
                    Product product  = message.getData(); // <--the code is broken here. I can see message.getData is a LinkedHashMap with debugger. It's not a type of Product? why???
                    LOG.info("Create product with ID: {}", product.getProductId());
                    productService.createProduct(product);
                    break;

                case DELETE:
                    String productId = message.getKey();
                    LOG.info("Delete product with ProductID: {}", productId);
                    productService.deleteProduct(productId);
                    break;

                default:
                    String errorMessage = "Incorrect event type: " + message.getEventType() + ", expected a CREATE or DELETE event";
                    LOG.warn(errorMessage);
                    throw new EventProcessingException(errorMessage);
            }

            LOG.info("Message product processing done!");
            return message.getKey();
        };
    }
```
![image](https://user-images.githubusercontent.com/1314173/93983207-d7854f00-fdb4-11ea-8354-ebbc3a5bad96.png)

**Comment by olegz** [comment]
This issue is closed (almost a year ago). If you believe you have a problem, create new issue providing all the necessary details
