### ISSUE TITLE
Backpressure Support in Reactive Consumers

### ISSUE THREAD

**Issue by kschlesselmann** [spring-cloud/spring-cloud-stream#1835]
Currently we're facing some issues because we've got a really fast producing service and some slower consuming services.

If we just specify a
```
Function<Flux<Input>, Flux<Output>>
```
in our consuming services they are immediately overwhelmed with messages which results in direct service failures (OOM, no free database connections, you name it).

We came up with some kind of batch polling solution with
```
private val logger = KotlinLogging.logger {}

object BatchPollingFlux {

    fun <T> fromPollableMessageSource(
            input: PollableMessageSource,
            batchSize: Int = 100,
            delayAfterEmpty: Duration = Duration.ofSeconds(10),
            typeReference: ParameterizedTypeReference<T>
    ): Flux<T> = Flux.create<List<T>> { batchEmitter(it, input, batchSize, typeReference) }
            .limitRate(1)
            .delayUntil { delayForEmptyBatch(it, delayAfterEmpty) }
            .flatMapIterable { it }

    private fun <T> batchEmitter(
            sink: FluxSink<List<T>>,
            input: PollableMessageSource,
            batchSize: Int,
            typeReference: ParameterizedTypeReference<T>
    ) {
        sink.onRequest {
            logger.trace { "Processing new request" }

            val messages: MutableList<T> = mutableListOf()

            var counter = 0
            while (counter < batchSize && readMessage(messages, input, typeReference)) {
                counter++
            }

            logger.trace { "Polled ${messages.size} messages" }
            sink.next(messages)
        }
    }

    private fun <T> readMessage(
            messages: MutableList<T>,
            input: PollableMessageSource,
            typeReference: ParameterizedTypeReference<T>
    ): Boolean {
        val handler = MessageHandler { message ->
            val payload: T = message.payload as T
            messages.add(payload)
        }

        return input.poll(handler, typeReference)
    }

    private fun delayForEmptyBatch(batch: List<Any?>, delay: Duration): Mono<Void> = batch.toMono()
            .filter { it.isEmpty() }
            .doOnNext { logger.debug { "Polled empty batch from stream. Delaying next element by $delay" } }
            .delayElement(delay)
            .then()

}
```
which has some downsides though:

1. It has no support for the Spring Cloud Function Programming model
2. It's not very good if you look at the performance

It would be great if there would be some kind of backpressure support in reactive functions which would enable a client to specify that there should be no more than `X` messages "inside" the consuming service at all times.

**Comment by kschlesselmann** [comment]
A little update after some discussion with @olegz in the gitter channel.

It seems the problem just arises if you add Spring Data MongoDB Reactive to the mix. I wrote a little sample application 
```
data class Input(val id: String)

data class Output(val id: String) {
    val consumeMemory = id.repeat(1000000)
}

interface InputRepository : ReactiveCrudRepository<Input, String>

@SpringBootApplication
class DemoApplication {

    @Bean
    fun processor(inputRepository: InputRepository): Function<Flux<Message<Any>>, Flux<Message<String>>> = Function { inputs ->
        inputs
                .concatMap { inputRepository.save(Input(Instant.now().toString())) }
                .map { Output(it.id) }
                .map { MessageBuilder.withPayload(it.id).build() }
    }

}

fun main(args: Array<String>) {
    runApplication<DemoApplication>(*args)
}
```
which runs quite fine with `-Xmx96M` and 1.000.000 messages on the input topic until(!) you add the repo save to the stream. After that it fails with
```
2019-10-30 09:21:17.719 ERROR 127775 --- [      Thread-10] org.mongodb.driver.client                : Calling onNext threw an exception

reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$OverflowException: Queue is full: Reactive Streams source doesn't respect backpressure
Caused by: reactor.core.Exceptions$OverflowException: Queue is full: Reactive Streams source doesn't respect backpressure
        at reactor.core.Exceptions.failWithOverflow(Exceptions.java:215) ~[reactor-core-3.3.0.RELEASE.jar!/:3.3.0.RELEASE]
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:238) ~[reactor-core-3.3.0.RELEASE.jar!/:3.3.0.RELEASE]
        at reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:618) ~[reactor-core-3.3.0.RELEASE.jar!/:3.3.0.RELEASE]
        at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) ~[reactor-core-3.3.0.RELEASE.jar!/:3.3.0.RELEASE]
        at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453) ~[spring-integration-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403) ~[spring-integration-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:198) ~[spring-integration-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:384) ~[spring-integration-kafka-3.2.0.RELEASE.jar!/:3.2.0.RELEASE]
        at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:75) ~[spring-integration-kafka-3.2.0.RELEASE.jar!/:3.2.0.RELEASE]
        at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:443) ~[spring-integration-kafka-3.2.0.RELEASE.jar!/:3.2.0.RELEASE]
        at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:417) ~[spring-integration-kafka-3.2.0.RELEASE.jar!/:3.2.0.RELEASE]
        at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.lambda$onMessage$0(RetryingMessageListenerAdapter.java:120) ~[spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) ~[spring-retry-1.2.
...
```

**Comment by artembilan** [comment]
See related work-in-progress on Spring Integration side: https://github.com/spring-projects/spring-integration/pull/3100

**Comment by artembilan** [comment]
The fix has been merged into Spring Integration, so I guess this one can be resolved after upgrading and confirmation from end-user.

Thanks

**Comment by garyrussell** [comment]
I will be upgrading to SIK 3.2.1 and SI 5.2.1 for https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/790

**Comment by kschlesselmann** [comment]
> The fix has been merged into Spring Integration, so I guess this one can be resolved after upgrading and confirmation from end-user.

Looks great. My sample service runs fine now.

After the official release I'm going to update our "real" services and will come back with further insights (if there are any).

Thanks!
