### ISSUE TITLE
Getting error in configuring default binder while configuring with Multiple binders

### ISSUE THREAD

**Issue by muhammad-usman-confiz** [spring-cloud/spring-cloud-stream#1839]
Using `spring cloud stream` binders, I am trying to connect with multiple azure event hub namespaces. This configuration works fine with single namespace but for multiple namespaces, I am getting following exception on startup.

```
Caused by: java.lang.IllegalStateException: A default binder has been requested, but there is more than one binder available for 'org.springframework.cloud.stream.messaging.DirectWithAttributesChannel' : kafka2,kafka1, and no default binder has been set.
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:181) ~[spring-cloud-stream-3.0.0.RC1.jar:3.0.0.RC1]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:132) ~[spring-cloud-stream-3.0.0.RC1.jar:3.0.0.RC1]
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:339) ~[spring-cloud-stream-3.0.0.RC1.jar:3.0.0.RC1]
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:234) ~[spring-cloud-stream-3.0.0.RC1.jar:3.0.0.RC1]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindOutputs(AbstractBindableProxyFactory.java:136) ~[spring-cloud-stream-3.0.0.RC1.jar:3.0.0.RC1]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.doStartWithBindable(OutputBindingLifecycle.java:58) ~[spring-cloud-stream-3.0.0.RC1.jar:3.0.0.RC1]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_221]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57) ~[spring-cloud-stream-3.0.0.RC1.jar:3.0.0.RC1]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:34) ~[spring-cloud-stream-3.0.0.RC1.jar:3.0.0.RC1]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	... 14 common frames omitted
```

Here is my .yml configuration

```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: broker1.servicebus.windows.net:9093
          configuration:
            sasl.jaas.config: "..."
            sasl.mechanism: PLAIN
            security.protocol: SASL_SSL
      dynamicDestinations: dev-event-hub,prod-event-hub
      bindings:
        input-1:
          destination: dev-event-hub,prod-event-hub
          binder: kafka1
          group: $Default
        input-2:
          destination: dev-event-hub,prod-event-hub
          binder: kafka2
          group: $Default
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  Kafka:
                    binder:
                      brokers: broker2.servicebus.windows.net:9093
                      configuration:
                        sasl.jaas.config: "..."
                        sasl.mechanism: PLAIN
                        security.protocol: SASL_SSL
                  dynamicDestinations: dev-event-hub,prod-event-hub
        kafka2:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  Kafka:
                    binder:
                      brokers: broker3.servicebus.windows.net:9093
                      configuration:
                        sasl.jaas.config: "..."
                        sasl.mechanism: PLAIN
                        security.protocol: SASL_SSL
                  dynamicDestinations: dev-event-hub,prod-event-hub
```

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-stream-binder-kafka #793](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/793) via [**ZenHub**](https://www.zenhub.com/)
