### ISSUE TITLE
An error occurred between Stream 3.0.0.RC2 and Swagger 3.0.0.SNAPSHOT

### ISSUE THREAD

**Issue by gtpark** [spring-cloud/spring-cloud-stream#1845]
## Problem
Bean creation failed error while springboot is starting. Casting error occurs while supplierInitializer scan InMemorySwaggerResourcesProvider and registers it as a bean. This happens in the newly added FunctionConfiguration class. ScannedGenericBeanDefinition cannot be cast to Root bean definition.

#### spring cloud stream 3.0.0.RC2
* org.springframework.cloud:spring-cloud-stream
* org.springframework.cloud:spring-cloud-starter-stream-rabbit

#### springfox swagger 3.0.0.SNAPSHOT 
* io.springfox:springfox-swagger2
* io.springfox:springfox-spring-webmvc
* io.springfox:springfox-spring-integration-webmvc
* io.springfox:springfox-swagger-ui

## Location
* FunctionConfiguration.java :: 234 line
* FunctionConfiguration.supplierInitializer > extractPollableAnnotation
```java
RootBeanDefinition bd = (RootBeanDefinition) context.getBeanDefinition(supplierFunctionName);
```

## Error log
```log
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'supplierInitializer' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ClassCastException: class org.springframework.context.annotation.ScannedGenericBeanDefinition cannot be cast to class org.springframework.beans.factory.support.RootBeanDefinition (org.springframework.context.annotation.ScannedGenericBeanDefinition and org.springframework.beans.factory.support.RootBeanDefinition are in unnamed module of loader 'app')
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at com.kakao.stella.user.UserApplication.main(UserApplication.java:15) ~[main/:na]
Caused by: java.lang.ClassCastException: class org.springframework.context.annotation.ScannedGenericBeanDefinition cannot be cast to class org.springframework.beans.factory.support.RootBeanDefinition (org.springframework.context.annotation.ScannedGenericBeanDefinition and org.springframework.beans.factory.support.RootBeanDefinition are in unnamed module of loader 'app')
	at org.springframework.cloud.stream.function.FunctionConfiguration.extractPollableAnnotation(FunctionConfiguration.java:246) ~[spring-cloud-stream-3.0.0.RC2.jar:3.0.0.RC2]
	at org.springframework.cloud.stream.function.FunctionConfiguration.access$100(FunctionConfiguration.java:114) ~[spring-cloud-stream-3.0.0.RC2.jar:3.0.0.RC2]
	at org.springframework.cloud.stream.function.FunctionConfiguration$1.afterPropertiesSet(FunctionConfiguration.java:175) ~[spring-cloud-stream-3.0.0.RC2.jar:3.0.0.RC2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	... 16 common frames omitted

```

**Comment by olegz** [comment]
Can you provide example that reproduces the error

**Comment by chli1** [comment]
I have exactly the same issue after upgrading to spring-cloud Hoxton.RC2.

**Comment by ciscoo** [comment]
Posting relevant debug logs here right before exception is thrown, we are also facing same issue. 

```
2019-11-15 12:18:08.193 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'functionBindingRegistrar' via factory method to bean named 'environment'
2019-11-15 12:18:08.193 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'functionBindingRegistrar' via factory method to bean named 'functionCatalog'
2019-11-15 12:18:08.193 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'functionBindingRegistrar' via factory method to bean named 'spring.cloud.stream.function-org.springframework.cloud.stream.function.StreamFunctionProperties'
2019-11-15 12:18:08.193 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'functionBindingRegistrar' via factory method to bean named 'binderTypeRegistry'
2019-11-15 12:18:08.200 [main] []: INFO  o.s.c.f.c.c.BeanFactoryAwareFunctionRegistry 256 - Looking up function '' with acceptedOutputTypes: []
2019-11-15 12:18:08.205 [main] []: INFO  o.s.c.f.c.c.BeanFactoryAwareFunctionRegistry 256 - Looking up function 'inMemorySwaggerResourcesProvider' with acceptedOutputTypes: []
2019-11-15 12:18:08.206 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 213 - Creating shared instance of singleton bean 'functionInitializer'
2019-11-15 12:18:08.208 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 213 - Creating shared instance of singleton bean 'inMemorySwaggerResourcesProvider_binding'
2019-11-15 12:18:08.221 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 213 - Creating shared instance of singleton bean 'binderAwareChannelResolver'
2019-11-15 12:18:08.224 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'binderAwareChannelResolver' via factory method to bean named 'bindingService'
2019-11-15 12:18:08.224 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'binderAwareChannelResolver' via factory method to bean named 'channelFactory'
2019-11-15 12:18:08.224 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'binderAwareChannelResolver' via factory method to bean named 'dynamicDestinationsBindable'
2019-11-15 12:18:08.225 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'functionInitializer' via factory method to bean named 'functionCatalog'
2019-11-15 12:18:08.225 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'functionInitializer' via factory method to bean named 'spring.cloud.stream.function-org.springframework.cloud.stream.function.StreamFunctionProperties'
2019-11-15 12:18:08.225 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'functionInitializer' via factory method to bean named '&inMemorySwaggerResourcesProvider_binding'
2019-11-15 12:18:08.225 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'functionInitializer' via factory method to bean named 'spring.cloud.stream-org.springframework.cloud.stream.config.BindingServiceProperties'
2019-11-15 12:18:08.226 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'functionInitializer' via factory method to bean named 'org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@14c01636'
2019-11-15 12:18:08.226 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'functionInitializer' via factory method to bean named 'functionBindingRegistrar'
2019-11-15 12:18:08.226 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'functionInitializer' via factory method to bean named 'binderAwareChannelResolver'
2019-11-15 12:18:08.230 [main] []: INFO  o.s.c.f.c.c.BeanFactoryAwareFunctionRegistry 256 - Looking up function 'inMemorySwaggerResourcesProvider' with acceptedOutputTypes: []
2019-11-15 12:18:08.231 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 213 - Creating shared instance of singleton bean 'supplierInitializer'
2019-11-15 12:18:08.232 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'supplierInitializer' via factory method to bean named 'functionCatalog'
2019-11-15 12:18:08.232 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'supplierInitializer' via factory method to bean named 'spring.cloud.stream.function-org.springframework.cloud.stream.function.StreamFunctionProperties'
2019-11-15 12:18:08.232 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'supplierInitializer' via factory method to bean named 'org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@14c01636'
2019-11-15 12:18:08.232 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'supplierInitializer' via factory method to bean named 'spring.cloud.stream-org.springframework.cloud.stream.config.BindingServiceProperties'
2019-11-15 12:18:08.232 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'supplierInitializer' via factory method to bean named '&inMemorySwaggerResourcesProvider_binding'
2019-11-15 12:18:08.232 [main] []: DEBUG o.s.b.f.s.DefaultListableBeanFactory 795 - Autowiring by type from bean name 'supplierInitializer' via factory method to bean named 'binderAwareChannelResolver'
2019-11-15 12:18:08.239 [main] []: INFO  o.s.c.f.c.c.BeanFactoryAwareFunctionRegistry 256 - Looking up function 'inMemorySwaggerResourcesProvider' with acceptedOutputTypes: []
2019-11-15 12:18:08.239 [main] []: INFO  o.s.c.f.c.c.BeanFactoryAwareFunctionRegistry 256 - Looking up function 'inMemorySwaggerResourcesProvider' with acceptedOutputTypes: [application/json]
2019-11-15 12:18:08.244 [main] []: WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext 558 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'supplierInitializer' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ClassCastException: org.springframework.context.annotation.ScannedGenericBeanDefinition cannot be cast to org.springframework.beans.factory.support.RootBeanDefinition
```

Trying to create an example applications that produces this.
