### ISSUE TITLE
A component required a bean named 'output' that could not be found.

### ISSUE THREAD

**Issue by ruinshe** [spring-cloud/spring-cloud-stream#1852]
*I opened this bug here not in the `kubernetes-discovery project` because I think it's caused by the framework code in `spring-cloud-stream`, not `kubernetes-discovery`.*

The issue I met is my **spring boot 2.2.1 + spring cloud Hoxton.RC2** application crashes when adding the package `org.springframework.cloud:spring-cloud-kubernetes-discovery` as my project's dependency, and `FunctionChannelBindingInitializer` scans a function defined in that package and reports the java bean `output` (default binder I think?) is missing.

Besides, I tried the latest snapshot version of spring, and it also can be reproduced.

I have a [simple demo project](https://github.com/ruinshe/spring-cloud-stream-crashed) hosted in GitHub, please take a look if you want to do deep investigation.

There are some investigations about the sample project I already did:

### About the dependencies
The breakage is invoked when I add `org.springframework.cloud:spring-cloud-kubernetes-discovery` to my `build.gradle`, on the other hand, I think the root caused is exactly the package itself and not the dependencies of it, because I exclude all the dependencies of it and only keep
`org.springframework.cloud:spring-cloud-kubernetes-core`, and when I manually include the
`org.springframework.cloud:spring-cloud-kubernetes-core` without discovery dependencies,
the application also starts normally.

### About the application logs

When I remove the kubernetes related packages, I can find a log entry indicating 
the `springCloudBusOutput` is bind as the spring cloud bus output.
``` log
Binding :interface org.springframework.cloud.bus.SpringCloudBusClient:springCloudBusOutput
```

But when I added them back, this log entry is missing and the configuration process shows java 
bean `output` is not found.

### Dig into the spring code

When I debug on the issue, I figure out that the method
 `FunctionConfiguration.FunctionChannelBindingInitializer#afterPropertiesSet` maps each
 inputs and outputs together, and the only function wrapper is:
 
 ```
java.util.function.Function<io.fabric8.kubernetes.client.KubernetesClient, io.fabric8.kubernetes.client.dsl.FilterWatchListDeletable<io.fabric8.kubernetes.api.model.Service, io.fabric8.kubernetes.api.model.ServiceList, java.lang.Boolean, io.fabric8.kubernetes.client.Watch, io.fabric8.kubernetes.client.Watcher<io.fabric8.kubernetes.api.model.Service>>>
```

And I found a class named `KubernetesClientServicesFunction` in that package which causes the bug.

**Comment by JBertaux** [comment]
Same issue with: spring boot 2.2.1 + spring cloud Hoxton.RELEASE

**Comment by davidmelia** [comment]
Hi, I have the same issue with Spring Cloud Function + Function AWS Adapter + Spring Cloud Stream Kafka (spring boot 2.2.1 + spring cloud Hoxton.RELEASE).  

See https://github.com/davidmelia/spring-cloud-stream3-bug 

I have found the following options as a hacky fix:

1) Define a bean output which doesn't do anything
```
  @Bean
  public Supplier<Flux<String>> output() {
    return () -> {
      log.info("**** WHAT IS OUTPUT FOR?? WHY DO I NEED TO DEFINE THIS??? ****");
      return Flux.just("OK");
    };
  }
```
2) Or Exclude FunctionConfiguration
 `@SpringBootApplication(exclude = FunctionConfiguration.class)`

**Comment by olegz** [comment]
Could you please provide a stack trace? The second fix is not really a hack, rather standard boot option to exclude a particular auto-config. That said, we still need a stack trace to diagnose it properly

**Comment by olegz** [comment]
Also please upgrade to Hoxton.RELEASE as there were few improvements in that area in several projects

**Comment by davidmelia** [comment]
> Could you please provide a stack trace? The second fix is not really a hack, rather standard boot option to exclude a particular auto-config. That said, we still need a stack trace to diagnose it properly

Here we go @olegz :
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionInitializer' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'output' available
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.initialize(AbstractSpringFunctionAdapterInitializer.java:118)
	at org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.handleRequest(SpringBootRequestHandler.java:49)
	at uk.co.dave.fxrate.AwsLambdaRequestHandlerTest.test(AwsLambdaRequestHandlerTest.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:71)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'output' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:805)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1278)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:297)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1114)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionChannelBindingInitializer.determineChannelToSubscribeTo(FunctionConfiguration.java:345)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionChannelBindingInitializer.lambda$afterPropertiesSet$0(FunctionConfiguration.java:315)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionChannelBindingInitializer.afterPropertiesSet(FunctionConfiguration.java:307)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)
	... 58 more

```

**Comment by olegz** [comment]
And just to confirm, you are not using any functions explicitly as a message handlers. Basically can you say a few words about yoru app or if it's possible on github somewhere. Just trying to understand the context

**Comment by olegz** [comment]
Actually never mind, there is a demo project link

**Comment by ruinshe** [comment]
FYI, as I mentioned in the gitter and already added some description in the demo project, I think it's caused by the class `KubernetesClientServicesFunction` scanned by the framework.

Besides, currently I upgrades the spring version and use `EnableBinding(Source.class)` to a temporary fix (although I think it may be a trick solution).

For the question mentioned above, I'm not using any functions explicitly as a message handlers, at least in the demo project ;-)

**Comment by olegz** [comment]
Actually for temp fix you can either disable function configuration all together as before or define `spring.cloud.function.definition=blahblah` property where `blahblah` something that doesn't exist. 
The issue's been identified so it will be fixed for SR1

**Comment by ruinshe** [comment]
Thanks for the information for solution, because using binding doesn't break my current project, I keep it in my code.

Looking forward for the fix!
