### ISSUE TITLE
doBindConsumer will retry endless and fail forever when consumerEndpoint starting failed

### ISSUE THREAD

**Issue by chang-chao** [spring-cloud/spring-cloud-stream#1858]
I'm using `spring-cloud-stream` and `spring-cloud-stream-binder-kafka-core:` `2.1.0.RELEASE`

I faced the issue described in the title, after some code analysis, it seems the cause lies in 
 `AbstractMessageChannelBinder.doBindConsumer()`.
https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L403

The method has the following 2 steps.
1. `step 1` :  create consumerEndpoint
creating the beans needed..
https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L417

2. `step 2` :  start consumerEndpoint
https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L424

when `BindingService.doBindConsumer` which calls the above method detects failure in `binder.bindConsumer` , it will retry every 30 seconds(by default), but in case of error that happened in `step 2` above , retrying will necessarily fail because all of the beans are already created , so it will retry endlessly and never recover.

here are my stack traces when this issue reproduced.

1. the stack of failure in the above step2(starting consumer failed)
```

org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:402)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:93)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:132)
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:140)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:121)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindInputs(BindableProxyFactory.java:234)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:54)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:47)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:33)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at foo.bar.MyApplication.main(MyApplication.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
```

2. the stack trace of retrying binding, which continues forever.
```
org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:402)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:93)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:132)
	at org.springframework.cloud.stream.binding.BindingService.lambda$rescheduleConsumerBinding$0(BindingService.java:160)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Failed to register bean with name 'foo.bar.errors.recoverer', since bean with the same name already exists. Possible reason: You may have multiple bindings with the same 'destination' and 'group' name (consumer side) and multiple bindings with the same 'destination' name (producer side). Solution: ensure each binding uses different group name (consumer side) or 'destination' name (producer side).
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerComponentWithBeanFactory(AbstractMessageChannelBinder.java:803)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:595)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:554)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:493)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:132)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:355)
	... 11 more
```

**Comment by olegz** [comment]
Have you tried it with 3.0.0.RELEASE or at least 2.2.1.RELEASE?
The 2.1 is rather old and nearing EOL

**Comment by chang-chao** [comment]
@olegz 
basically, this issue happened if exceptions are thrown in start consumerEndpoint.

https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L424

This issue does not reproduce in  `3.0.0.RELEASE` because it uses spring-kafka 2.3.4, and in this version, `missingTopicsFatal` is set to false by default in the following commit, hence topic meta(partition ) info will not be fetched in starting ,thus there is almost impossible that Exceptions are thrown in starting consumerEndpoint.

https://github.com/spring-projects/spring-kafka/commit/29403eb23001eb9bd485ad3fdc55eb9888ddf4b0#diff-7121e19c8f33f6bddfd42b749f0bddb0

As for `2.2.1.RELEASE` , yes, the issue reproduces,  and the reason is the same as 2.1.0.

**Comment by olegz** [comment]
Given that the `createConsumerEndpoint(..)` is actually implemented by the binder that call must not throw an exception and instead return valid MessageSource regardless if it was just created or  cached from the previous call in the case of retry. So from my angle I do not believe there is anything that we should do in the core especially since the issue no linger exists with 3.0.0.RELEASE. 

Feel free to open an issue against spring-cloud-stream-kafka-binder, or see if you can upgrade to 3.0.0.RELEASE.
