### ISSUE TITLE
No keep alive threads to support reactive Supplier

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#1863]
### Edit

Actually this issue is not about timing, rather about the fact that there is no default keep-alive thread for cases when there is a reactive Supplier. The fact that it may actually work with some binders (e.g, Rabbit) is actually a lucky coincidence since such binders may have some keep-alive threads for their own benefit. 

Basically to address this issue we need a default mechanism to keep application alive when reactive Suppliers are used.

### Original
Basically when you have something like this
```
@Bean
    public Supplier<Flux<String>> emit() {
        return () -> Flux.interval(Duration.ofMillis(10))
                         .map(aLong -> aLong+"")
                         .log();
    }
```
we go through `((Flux) publisher).delaySubscription(beginPublishingTrigger).map(this::wrapToMessageIfNecessary);` effectively delaying subscription until binding is created. This is probably too clever and unnecessary and  presents a timing issue where application may actually exit if binding event does not appear on time.
The workaround for now is to add 
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
</dependency>```

**Comment by msshitole** [comment]
@olegz Additional info, with the current workaround (`spring-boot-starter-web`), during shutdown it loses some messages due to the subscription issue. No graceful shutdown happens. Here is the stacktrace for the same:

> org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'emit_integrationflow.channel#0'; nested exception is java.lang.IllegalStateException: The [bean 'emit_integrationflow.channel#0'] doesn't have subscribers to accept messages
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInDeliveryExceptionIfNecessary(IntegrationUtils.java:166) ~[spring-integration-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:483) ~[spring-integration-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403) ~[spring-integration-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]

> Caused by: java.lang.IllegalStateException: The [bean 'emit_integrationflow.channel#0'] doesn't have subscribers to accept messages
	at org.springframework.util.Assert.state(Assert.java:94) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.integration.channel.FluxMessageChannel.doSend(FluxMessageChannel.java:63) ~[spring-integration-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]

> org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'emit_integrationflow.channel#0'; nested exception is java.lang.IllegalStateException: The [bean 'emit_integrationflow.channel#0'] doesn't have subscribers to accept messages
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInDeliveryExceptionIfNecessary(IntegrationUtils.java:166) ~[spring-integration-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:483) ~[spring-integration-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403) ~[spring-integration-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
