### ISSUE TITLE
Per-binding error handler causes application shutdown problems

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-stream#1870]
This issue turned up in spring-cloud/spring-cloud-gcp#2032, but I believe it's not specific to the Pub/Sub binder. When setting up a binder-specific error handler with `@ServiceActivator` ([docs](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#spring-cloud-stream-overview-error-handling), [sample code](https://github.com/spring-cloud/spring-cloud-gcp/blob/c7b545c9971241661234e2c0cacd981db318ed43/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/java/com/example/SinkExample.java#L51)), the error handling logic itself works as expected. However, application context shutdown has errors and eventually times out:
```
 WARN 11871 --- [extShutdownHook] o.s.c.support.DefaultLifecycleProcessor  : Failed to stop bean 'inputBindingLifecycle'

org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'my-topic.my-group.errors' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.removeBeanDefinition(DefaultListableBeanFactory.java:988) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.support.GenericApplicationContext.removeBeanDefinition(GenericApplicationContext.java:328) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.destroyBean(AbstractMessageChannelBinder.java:831) ~[spring-cloud-stream-3.0.1.BUILD-SNAPSHOT.jar:3.0.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.destroyErrorInfrastructure(AbstractMessageChannelBinder.java:818) ~[spring-cloud-stream-3.0.1.BUILD-SNAPSHOT.jar:3.0.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.access$300(AbstractMessageChannelBinder.java:90) ~[spring-cloud-stream-3.0.1.BUILD-SNAPSHOT.jar:3.0.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$2.afterUnbind(AbstractMessageChannelBinder.java:453) ~[spring-cloud-stream-3.0.1.BUILD-SNAPSHOT.jar:3.0.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.DefaultBinding.unbind(DefaultBinding.java:168) ~[spring-cloud-stream-3.0.1.BUILD-SNAPSHOT.jar:3.0.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.BindingService.unbindConsumers(BindingService.java:334) ~[spring-cloud-stream-3.0.1.BUILD-SNAPSHOT.jar:3.0.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.unbindInputs(AbstractBindableProxyFactory.java:156) ~[spring-cloud-stream-3.0.1.BUILD-SNAPSHOT.jar:3.0.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStopWithBindable(InputBindingLifecycle.java:66) ~[spring-cloud-stream-3.0.1.BUILD-SNAPSHOT.jar:3.0.1.BUILD-SNAPSHOT]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_181-google-v7]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:68) ~[spring-cloud-stream-3.0.1.BUILD-SNAPSHOT.jar:3.0.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.0.1.BUILD-SNAPSHOT.jar:3.0.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:85) ~[spring-cloud-stream-3.0.1.BUILD-SNAPSHOT.jar:3.0.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.0.1.BUILD-SNAPSHOT.jar:3.0.1.BUILD-SNAPSHOT]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:238) [spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:53) [spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:377) [spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:210) [spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128) [spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1021) [spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948) [spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]

^C2019-12-10 17:25:06.325  INFO 11871 --- [extShutdownHook] o.s.c.support.DefaultLifecycleProcessor  : Failed to shut down 1 bean with phase value 2147482647 within timeout of 30000: [inputBindingLifecycle]
``` 

I believe this happens because the channel bean is created in Spring Integration as a [singleton without bean definition](https://github.com/spring-projects/spring-integration/blob/ebbcb9df4812a54931536cde361949679106865e/spring-integration-core/src/main/java/org/springframework/integration/config/annotation/AbstractMethodAnnotationPostProcessor.java#L340), then Spring Cloud Stream uses the existing bean (but if it did not exist, Spring Cloud Stream [would create it with a definition](https://github.com/spring-cloud/spring-cloud-stream/blob/0d9982fddb483f721ab4395b783242a4b146d2f5/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L625)). Then at context destruction time, [removing bean definition](https://github.com/spring-cloud/spring-cloud-stream/blob/0d9982fddb483f721ab4395b783242a4b146d2f5/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L830) fails because one does not exist.

Would it make sense to gate bean definition destruction with `.containsBeanDefinition()`?

**Comment by Stexxen** [comment]
I'm seeing a very similar issue in v3.1.1 but now effecting the `errors.recoverer` bean, but unfortunately I don't known what the .recoverer bean is.....

```
2021-03-11 23:01:58.086  WARN 79972 --- [extShutdownHook] o.s.c.s.DefaultLifecycleProcessor        : Failed to stop bean 'inputBindingLifecycle'

org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'tibgenericevents.roar-dev-group.errors.recoverer' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.removeBeanDefinition(DefaultListableBeanFactory.java:1059) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.context.support.GenericApplicationContext.removeBeanDefinition(GenericApplicationContext.java:335) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.destroyBean(AbstractMessageChannelBinder.java:827) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.destroyErrorInfrastructure(AbstractMessageChannelBinder.java:786) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.access$300(AbstractMessageChannelBinder.java:91) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$2.afterUnbind(AbstractMessageChannelBinder.java:444) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binder.DefaultBinding.unbind(DefaultBinding.java:174) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.BindingService.unbindConsumers(BindingService.java:351) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.unbindInputs(AbstractBindableProxyFactory.java:156) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStopWithBindable(InputBindingLifecycle.java:66) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:68) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:85) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:234) [spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:54) [spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:373) [spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:206) [spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:129) [spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1072) [spring-context-5.3.3.jar:5.3.3]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:171) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:996) [spring-context-5.3.3.jar:5.3.3]

2021-03-11 23:01:58.086  WARN 79972 --- [extShutdownHook] o.s.c.s.DefaultLifecycleProcessor        : Failed to stop bean 'inputBindingLifecycle'

```
