### ISSUE TITLE
Exception when testing functional message handlers with Spock

### ISSUE THREAD

**Issue by krzysztof1980** [spring-cloud/spring-cloud-stream#1882]
Hi,
my current project uses [Spock Framework](http://spockframework.org/) for testing. This is a test from the documentation of SCS v. 3.0.1.RELEASE, rewritten in Spock:
```groovy
@SpringBootTest(args = "--spring.cloud.stream.function.definition=uppercase")
class CloudStreamBindingsSpec extends Specification {

    @Autowired
    private InputDestination source

    @Autowired
    private OutputDestination target

    def sampleTest() {
        when:
        source.send(new GenericMessage<byte[]>("hello".getBytes()))

        then:
        target.receive().getPayload() == "HELLO".getBytes()
    }

    @SpringBootApplication
    @Import(TestChannelBinderConfiguration)
    static class MyTestConfiguration {
        @Bean
        Function<String, String> uppercase() {
            return { v -> v.toUpperCase() }
        }
    }
}
```
When I run it, I get following exception:
```
Error creating bean with name 'uppercase_binding': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalArgumentException: Interface must not be null
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'uppercase_binding': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalArgumentException: Interface must not be null
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:178)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1817)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1266)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:260)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
	at org.spockframework.spring.SpringMockTestExecutionListener.beforeTestMethod(SpringMockTestExecutionListener.java:79)
       ...
Caused by: java.lang.IllegalArgumentException: Interface must not be null
	at org.springframework.util.Assert.notNull(Assert.java:198)
	at org.springframework.aop.framework.AdvisedSupport.addInterface(AdvisedSupport.java:208)
	at org.springframework.aop.framework.ProxyFactory.<init>(ProxyFactory.java:72)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.getObject(BindableProxyFactory.java:146)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
	... 53 more
```
In short, before every test method, Spock iterates through BeanDefinitions and for each one that is not abstract or lazy initialized, it instantiates corresponding bean and checks if it is a mock. I think this is not a problem with Spock, but with current implementation of BindableFunctionProxyFactory: calling getObject() on it will always cause an exception, because BindableFunctionProxyFactory calls the super constructor with null as argument (that is then used by getObject() without checking, if it is null). In my opinion, a better solution would be to overwrite this method for it to return null. My workaround as of now is to use a custom TestExecutionListener:
```java
@Order(1)
class MyTestExecutionListener extends SpringMockTestExecutionListener {

    @Override
    void beforeTestClass(SpringTestContext testContext) throws Exception {
        super.beforeTestClass(testContext)
        def registry = (BeanDefinitionRegistry) testContext.getApplicationContext()
        registry.getBeanDefinitionNames()
                .findAll { it.endsWith('_binding') }
                .each { registry.removeBeanDefinition(it) }
    }
}
```
I created a simple project, so that you can reproduce it easily: https://github.com/krzysztof1980/spring-cloud-stream-spock.git. The tests run, but if you remove the annotation TestExecutionListeners from CloudStreamBindingsSpec, then they don't. I created the project with Spring Initializer and it uses Spring Cloud in the version Hoxton.SR1.
Could you please investigate this issue?

**Comment by olegz** [comment]
@krzysztof1980 I hear you but can't seem to come around. Having `getObject(..)` to return null just doesn't seem right. Also, given that your pure java test works just fine, this is clearly an issue isolated to only when testing with Spock and the expectations it may have. But I can't possibly be motivated to have framework fit the expectations of testing. I believe in the opposite actually, so unless some other convincing argument comes about I am perfectly fine with your custom solution as is.

**Comment by krzysztof1980** [comment]
@olegz I understand your point about how changing the framework for tests to work is generally wrong. On the other hand, it seems strange to me, that getObject() called on BindableFunctionProxyFactory always throws an exception. Doesn't it breaks the contract of this method by doing this? Its javadoc says: "Return an instance (possibly shared or independent) of the object managed by this factory" - but it is never fulfilled. To the return value, the javadoc says: "an instance of the bean (can be {@code null})" - so null seems to be a valid return value, that the callers need to count with. The implementation of getObject() provided by BindableProxyFactory just doesn't make sense for BindableFunctionProxyFactory.

**Comment by olegz** [comment]
@krzysztof1980 I hear you
