### ISSUE TITLE
Unable to pass empty binder properties in multibinder setup

### ISSUE THREAD

**Issue by robwruck** [spring-cloud/spring-cloud-stream#1887]
As of Kafka 2.0.0, `ssl.endpoint.identification.algorithm` defaults to `https` and you have to set it to an empty string to disable host name verification.
For a single binder, this can be achieved via
```
spring.cloud.stream.kafka.binder.configuration.ssl.endpoint.identification.algorithm=
```
But if you want to configure it for a single binder in a multibinder setup, binder creation fails:
```
spring.cloud.stream.binders.first-binder.environment.spring.cloud.stream.kafka.binder.configuration.ssl.endpoint.identification.algorithm=https
spring.cloud.stream.binders.second-binder.environment.spring.cloud.stream.kafka.binder.configuration.ssl.endpoint.identification.algorithm=
```
Stack trace:
```
java.lang.IllegalArgumentException: Invalid argument syntax: --spring.cloud.stream.kafka.binder.configuration.ssl.endpoint.identification.algorithm=
	at org.springframework.core.env.SimpleCommandLineArgsParser.parse(SimpleCommandLineArgsParser.java:75) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.core.env.SimpleCommandLinePropertySource.<init>(SimpleCommandLinePropertySource.java:90) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.boot.DefaultApplicationArguments$Source.<init>(DefaultApplicationArguments.java:76) ~[spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.DefaultApplicationArguments.<init>(DefaultApplicationArguments.java:42) ~[spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) ~[spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:303) ~[spring-cloud-stream-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:194) ~[spring-cloud-stream-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:132) ~[spring-cloud-stream-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:362) ~[spring-cloud-stream-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:257) ~[spring-cloud-stream-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindOutputs(AbstractBindableProxyFactory.java:136) ~[spring-cloud-stream-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.doStartWithBindable(OutputBindingLifecycle.java:58) ~[spring-cloud-stream-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57) ~[spring-cloud-stream-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:34) ~[spring-cloud-stream-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
```
Spring Cloud Stream: 3.0.1 (Hoxton.SR1)

**Comment by olegz** [comment]
@robwruck I a not sure there is anything we can do on the stream side. As you can see from the stack trace we are simply passing it to Spring Boot, so I would suggest ask question on Spring Boot forums. 

However, personally I consider it a Kafka issue first and foremost. They should  not be requiring user to provide a property with no value, so consider raising an issue with them.

That said, have you tries providing an empty string as a value?

**Comment by robwruck** [comment]
I agree that using an empty value to mean "none" should be fixed by Kafka and that SimpleCommandLineArgsParser maybe should support empty values - but I didn't take a closer look at it.

The properties syntax for an empty string is
```
spring.cloud.stream.binders.second-binder.environment.spring.cloud.stream.kafka.binder.configuration.ssl.endpoint.identification.algorithm=
```
which doesn't work (rejected by SimpleCommandLineArgsParser). Neither do these:
```
spring.cloud.stream.binders.second-binder.environment.spring.cloud.stream.kafka.binder.configuration.ssl.endpoint.identification.algorithm=''
spring.cloud.stream.binders.second-binder.environment.spring.cloud.stream.kafka.binder.configuration.ssl.endpoint.identification.algorithm=""
```
(rejected by Kafka).

**Comment by olegz** [comment]
So, I am assuming I can close his and you can raise he issue with Kafka, correct?

**Comment by robwruck** [comment]
Yeah, I'll give it a try.

**Comment by sbrannen** [comment]
For anyone who runs into this issue, please note that you can omit the `=` sign as a workaround.

See https://github.com/spring-projects/spring-framework/issues/24464 for details.
