### ISSUE TITLE
ClassCastException casting to String

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#1934]
@naushadamin commented on [Fri Mar 06 2020](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/859)

I am attempting to test spring cloud stream event routing where the destination/binder is kafka based on https://spring.io/blog/2019/10/31/spring-cloud-stream-event-routing. 

i have two Consumer functions even and odd. i would like to set a message header to route to a function. so i invoke the following in kafkacat:

> echo 9 | kafkacat -b localhost:31095 -t functionRouter-in-0 -P -H spring.cloud.function.routing-expression=odd. 

I get the following error on my stacktrace what it looks like the message is still coming through as raw byte array and String conversion is failing. 
Stacktrace is below:
```
2020-03-06 15:01:41.847 ERROR 31216 --- [container-0-C-1] o.s.kafka.listener.LoggingErrorHandler   : Error while processing: ConsumerRecord(topic = functionRouter-in-0, partition = 0, leaderEpoch = 0, offset = 39, CreateTime = 1583524898730, serialized key size = -1, serialized value size = 1, headers = RecordHeaders(headers = [RecordHeader(key = spring.cloud.function.definition, value = [101, 118, 101, 110])], isReadOnly = false), key = null, value = [B@4235447d)

org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageHandlingException: error occurred during processing message in 'MethodInvokingMessageProcessor' [org.springframework.integration.handler.MethodInvokingMessageProcessor@42cd4f2]; nested exception is java.lang.ClassCastException: [B cannot be cast to java.lang.String, failedMessage=GenericMessage [payload=byte[1], headers={kafka_offset=39, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@ba9e861, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, spring.cloud.function.definition=[B@d2bd25d, kafka_receivedMessageKey=null, kafka_receivedPartitionId=0, kafka_receivedTopic=functionRouter-in-0, kafka_receivedTimestamp=1583524898730, kafka_groupId=anonymous.28b33eba-37e1-409a-95c6-134a98a947eb}]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:1644) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:1630) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1546) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1487) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1401) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1165) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:949) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:884) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
Caused by: org.springframework.messaging.MessageHandlingException: error occurred during processing message in 'MethodInvokingMessageProcessor' [org.springframework.integration.handler.MethodInvokingMessageProcessor@42cd4f2]; nested exception is java.lang.ClassCastException: [B cannot be cast to java.lang.String
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:191) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:111) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:95) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:127) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:177) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:198) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:384) ~[spring-integration-kafka-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:75) ~[spring-integration-kafka-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:443) ~[spring-integration-kafka-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:417) ~[spring-integration-kafka-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.lambda$onMessage$0(RetryingMessageListenerAdapter.java:120) ~[spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) ~[spring-retry-1.2.4.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:211) ~[spring-retry-1.2.4.RELEASE.jar:na]
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:114) ~[spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:40) ~[spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:1592) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:1575) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1534) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	... 8 common frames omitted
Caused by: java.lang.ClassCastException: [B cannot be cast to java.lang.String
	at org.springframework.cloud.function.context.config.RoutingFunction.route(RoutingFunction.java:94) ~[spring-cloud-function-context-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.cloud.function.context.config.RoutingFunction.apply(RoutingFunction.java:77) ~[spring-cloud-function-context-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.invokeFunction(BeanFactoryAwareFunctionRegistry.java:497) ~[spring-cloud-function-context-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.doApply(BeanFactoryAwareFunctionRegistry.java:560) ~[spring-cloud-function-context-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.apply(BeanFactoryAwareFunctionRegistry.java:465) ~[spring-cloud-function-context-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:602) ~[spring-cloud-stream-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper$HandlerMethod.invoke(MessagingMethodInvokerHelper.java:1096) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.invokeHandlerMethod(MessagingMethodInvokerHelper.java:580) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:476) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:355) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:108) ~[spring-integration-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	... 34 common frames omitted

[hello-streams-application.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/4300207/hello-streams-application.zip)
```

---

@garyrussell commented on [Wed Mar 11 2020](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/859#issuecomment-597147761)

This is the code:

```
			if (StringUtils.hasText((String) message.getHeaders().get("spring.cloud.function.definition"))) {
				function = functionFromDefinition((String) message.getHeaders().get("spring.cloud.function.definition"));
				Type functionType = functionInspector.getRegistration(function).getType().getType();
				if (FunctionTypeUtils.isReactive(FunctionTypeUtils.getInputType(functionType, 0))) {
					this.assertOriginalInputIsNotPublisher(originalInputIsPublisher);
				}
			}
			else if (StringUtils.hasText((String) message.getHeaders().get("spring.cloud.function.routing-expression"))) {
				function = this.functionFromExpression((String) message.getHeaders().get("spring.cloud.function.routing-expression"), message);
				Type functionType = functionInspector.getRegistration(function).getType().getType();
				if (FunctionTypeUtils.isReactive(FunctionTypeUtils.getInputType(functionType, 0))) {
					this.assertOriginalInputIsNotPublisher(originalInputIsPublisher);
				}
			}
```
You are getting a class cast on the header named `spring.cloud.function.definition` (line 94).

But you claim you are getting it on 

>-H spring.cloud.function.routing-expression=odd

So I suspect you have an "old" message with a header `spring.cloud.function.definition`.

As I explained on gitter, you need to convert the `byte[]` to String, unless you set the property on the app itself (instead of setting it in a header) and use `new String(headers([myHeader])` in the expression.

To send the expression in a header, you need two headers. You should purge your topic. Then use the following:

>>-H spring.cloud.function.routing-expression=new String(headers.myHeader) -H myHeader=odd

@olegz @sabbyanandan For convenience, we should test for `byte[]` in these headers to handle the case when the message is generated by a non-SCSt app.

---

@naushadamin commented on [Wed Mar 11 2020](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/859#issuecomment-597825107)

Thanks @garyrussell ! I am able to route based on header value successfully now.

**Comment by olegz** [comment]
Assuming this is resolved. Feel free to reopen it if you think otherwise
