### ISSUE TITLE
IllegalArgumentException: Unknown type for contentType header value: class [B

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream#1941]
See this issue for more details: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/863

Here is the stack trace:
```
Caused by: java.lang.IllegalArgumentException: Unknown type for contentType header value: class [B at org.springframework.messaging.converter.DefaultContentTypeResolver.resolve(DefaultContentTypeResolver.java:76)
at org.springframework.messaging.converter.AbstractMessageConverter.getMimeType(AbstractMessageConverter.java:265)
at org.springframework.messaging.converter.AbstractMessageConverter.supportsMimeType(AbstractMessageConverter.java:251)
at org.springframework.cloud.stream.schema.avro.AvroSchemaRegistryClientMessageConverter.supportsMimeType(AvroSchemaRegistryClientMessageConverter.java:285)
at org.springframework.messaging.converter.AbstractMessageConverter.canConvertFrom(AbstractMessageConverter.java:201)
at org.springframework.cloud.stream.schema.avro.AbstractAvroMessageConverter.canConvertFrom(AbstractAvroMessageConverter.java:84)
at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:194)
at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:70)
```

**Comment by olegz** [comment]
Related to https://github.com/spring-cloud/spring-cloud-stream/issues/1902
