### ISSUE TITLE
MessageChannel send method is returning true if brokers are down. 

### ISSUE THREAD

**Issue by DevD08** [spring-cloud/spring-cloud-stream#1976]
MessageChannel send method is returning true evwn if the brokers are down as kafka publishes to the buffer at first. 

Tried to set the acknowledgement property to all with the below properties
spring.kafka.producer.acks = all/-1
and
spring.cloud.stream.kafka.binder.requiredAcks = - 1
 We are opting to get the acknowledgement from the broker, but the kafka publisher is still returni g true when the brokers are down

**Comment by garyrussell** [comment]
You can also get the error asynchronously, by setting the `errorChannelEnabled` [common producer binding property](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.4.RELEASE/reference/html/spring-cloud-stream.html#_producer_properties).

**Comment by DevD08** [comment]
Hi @garyrussell thanks for the early reply. Will test with the property you suggested and reply back asap

**Comment by DevD08** [comment]
Hi @garyrussell i tried setting the ync propert to true, still messagechannel.send is returning true on brokers being down
spring:
  cloud:
    stream:
      default:
        content-type : avro/bytes
      kafka:b
        default:
          producer:
            sync: true
        binder:
          requiredAcks: -1
          brokers: localhost:9092,localhost:9093
          zkNodes: localhost:2181
          autoCreateTopics: false
          zkConnectionTimeout: 36000
          configuration:
            security.protocol: protocol
            ssl.truststore.location: truststoreLocn
            ssl.truststore.password: truststorePass
            ssl.endpoint.identification.algorithm:

I connected to brokers running in my local machine.

**Comment by garyrussell** [comment]
I just tested it and it works as expected:

```java
@SpringBootApplication
@EnableBinding(Source.class)
public class Kbgh1976Application {

	public static void main(String[] args) {
		SpringApplication.run(Kbgh1976Application.class, args);
	}


	@Bean
	public ApplicationRunner runner(MessageChannel output) {
		return args -> {
			try {
				System.out.println("Hit enter after stopping broker");
				System.in.read();
				output.send(new GenericMessage<>("foo"));
			}
			catch (Exception e) {
				e.printStackTrace();
			}
		};
	}

}
```
```properrties
spring.cloud.stream.kafka.default.producer.sync=true
spring.cloud.stream.kafka.default.producer.configuration.max.block.ms=5000
```

```
org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder$ProducerConfigurationMessageHandler@de88ac6]; nested exception is org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Topic output not present in metadata after 5000 ms., failedMessage=GenericMessage [payload=byte[3], headers={contentType=application/json, id=7ebab7f9-1816-63de-2fd3-a1cccdb2faa6, timestamp=1591106421784}]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:79)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:1035)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:69)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520)
	at com.example.demo.Kbgh1976Application.lambda$0(Kbgh1976Application.java:26)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.example.demo.Kbgh1976Application.main(Kbgh1976Application.java:17)
Caused by: org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Topic output not present in metadata after 5000 ms.
	at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:570)
	at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:385)
	at org.springframework.integration.kafka.outbound.KafkaProducerMessageHandler.handleRequestMessage(KafkaProducerMessageHandler.java:410)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:134)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:69)
	... 15 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Topic output not present in metadata after 5000 ms.
```

**Comment by DevD08** [comment]
Hi @garyrussell, just wanted to check if it has something to do with the springboot and springcloud version.
The version i am using is
Springboot  - - 1.5.19.RELEASE
spring-cloud - - Edgware.SR4

**Comment by olegz** [comment]
@DevD08 you are using very old and no longer supported version of both boot and cloud dependencies. 
he most current release of spring-cloud is Hoxton.SR5

**Comment by DevD08** [comment]
Hi @garyrussell, i know the versions are very old, but sadly I am not in a position to change the versions.
Is there anyways out to implement acknowledgement in kafka with these versions

**Comment by garyrussell** [comment]
I don't know what you mean by

>implement acknowledgement

but the `sync` property was supported in those old versions too. You should use a debugger to figure out why the property is not being set.

**Comment by sabbyanandan** [comment]
Closing due to no activity.

**Comment by devaraj1111** [comment]
Why do we need to set sync Kafka producer binding property when spring.kafka.producer.acks = all/-1 is already defined. Will this property being ignored then? The primary task of acks = all is same as sync=true right? Is this the expected behaviour?

And also if i use kafka clients without cloud stream where did I need to do both acks= all and also future.get() to achieve sync send?

**Comment by garyrussell** [comment]
They are different - `acks=all` means we don't get the async ack until all replicas have received the record.

`sync` simply means to block the sending thread until the async ack is received.

If sync is false, you can receive the ack asynchronously instead.
