### ISSUE TITLE
Unable to create multiple publishers using funtions

### ISSUE THREAD

**Issue by juliuskrah** [spring-cloud/spring-cloud-stream#1980]
Unable to create more than one `Supplier` for functional publisher

**Describe the issue**
Using a functional publisher with Apache Kafka, only the first registered publisher gets a subscriber

**To Reproduce**

1. 
  I created three Supplier functions
  ```java
@SpringBootApplication
public class Application {
    // -- Main method omitted

    @Bean
    Supplier<Flux<Foo>> foo1() {
		return () -> Event.foo1Processor;
	}
	
	@Bean
	Supplier<Flux<Foo>> foo2() {
		return () -> Event.foo2Processor;
	}
	
	@Bean
	Supplier<Flux<Foo>> foo3() {
		return () -> Event.foo3Processor;
	}

    // ------------
    @Bean
	public SchemaRegistryClient schemaRegistryClient(SchemaRegistryClientProperties properties) {
		ConfluentSchemaRegistryClient client = new ConfluentSchemaRegistryClient();
		client.setEndpoint(properties.getEndpoint());
		return client;
	}

    static interface Event {
          EmitterProcessor<Foo> foo1Processor= EmitterProcessor.create();
	      EmitterProcessor<Foo> foo2Processor= EmitterProcessor.create();
	      EmitterProcessor<Foo> foo3Processor= EmitterProcessor.create();
    }
}
  ```
2. 
    The functions are registered
  ```yaml
 spring:
    cloud:
      function:
        definition: foo1;foo2;foo3
      stream:
        default:
          content-type: application/*+avro
        bindings:
          foo1-out-0:
            destination: foo1_topic
          foo2-out-0:
            destination: foo2_topic 
          foo3-out-0:
            destination: foo3_topic
        schema:
          avro:
            dynamic-schema-generation-enabled: true
        schema-registry-client:
          endpoint: http://localhost:8081
          cached: true
        kafka:
          binder:
            brokers: localhost
 ```  

3. 
  I'm testing it with some post-construct
  
  ```java
@Component
  class SomeBeanClass {
    @PostConstruct
	void produceFoo1() {
		var foo= ...;
		Event.foo1Processor.onNext(foo);
	}

    @PostConstruct
	void produceFoo2() {
		var foo= ...;
		Event.foo2Processor.onNext(foo);
	}

    @PostConstruct
	void produceFoo3() {
		var foo= ...;
		Event.foo3Processor.onNext(foo);
	}
}
  ```

4. 

  When the application starts up only the first registered producer succeeds - below is the stacktrace

```bash
2020-06-04 12:25:18.507 ERROR 16040 --- [oundedElastic-3] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'app.foo2-out-0'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[63], headers={contentType=application/vnd.foo.v1+avro, id=d46d54c7-54cc-a8f5-c8c6-a9b8e41e2e34, timestamp=1591273518496}], failedMessage=GenericMessage [payload=byte[63], headers={contentType=application/vnd.foo.v1+avro, id=d46d54c7-54cc-a8f5-c8c6-a9b8e41e2e34, timestamp=1591273518496}]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:76)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.router.AbstractMessageRouter.doSend(AbstractMessageRouter.java:213)
	at org.springframework.integration.router.AbstractMessageRouter.handleMessageInternal(AbstractMessageRouter.java:195)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:62)
	at org.springframework.integration.handler.AbstractMessageHandler.onNext(AbstractMessageHandler.java:102)
	at org.springframework.integration.handler.AbstractMessageHandler.onNext(AbstractMessageHandler.java:37)
	at org.springframework.integration.endpoint.ReactiveStreamsConsumer.lambda$doStart$1(ReactiveStreamsConsumer.java:177)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:426)
	at reactor.core.publisher.EmitterProcessor.onNext(EmitterProcessor.java:268)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153)
	at org.springframework.integration.channel.FluxMessageChannel.doSend(FluxMessageChannel.java:63)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520)
	at org.springframework.integration.channel.FluxMessageChannel.lambda$subscribeTo$2(FluxMessageChannel.java:83)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:189)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:439)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:526)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[63], headers={contentType=application/vnd.foo.v1+avro, id=d46d54c7-54cc-a8f5-c8c6-a9b8e41e2e34, timestamp=1591273518496}]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:139)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	... 33 more

2020-06-04 12:25:18.509 ERROR 16040 --- [oundedElastic-2] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'app.foo3-out-0'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[63], headers={contentType=application/vnd.foo.v1+avro, id=12494b77-5cfe-da9b-eae3-09463fa12d74, timestamp=1591273518496}], failedMessage=GenericMessage [payload=byte[63], headers={contentType=application/vnd.foo.v1+avro, id=12494b77-5cfe-da9b-eae3-09463fa12d74, timestamp=1591273518496}]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:76)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.router.AbstractMessageRouter.doSend(AbstractMessageRouter.java:213)
	at org.springframework.integration.router.AbstractMessageRouter.handleMessageInternal(AbstractMessageRouter.java:195)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:62)
	at org.springframework.integration.handler.AbstractMessageHandler.onNext(AbstractMessageHandler.java:102)
	at org.springframework.integration.handler.AbstractMessageHandler.onNext(AbstractMessageHandler.java:37)
	at org.springframework.integration.endpoint.ReactiveStreamsConsumer.lambda$doStart$1(ReactiveStreamsConsumer.java:177)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:426)
	at reactor.core.publisher.EmitterProcessor.onNext(EmitterProcessor.java:268)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153)
	at org.springframework.integration.channel.FluxMessageChannel.doSend(FluxMessageChannel.java:63)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520)
	at org.springframework.integration.channel.FluxMessageChannel.lambda$subscribeTo$2(FluxMessageChannel.java:83)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:189)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:439)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:526)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[63], headers={contentType=application/vnd.foo.v1+avro, id=12494b77-5cfe-da9b-eae3-09463fa12d74, timestamp=1591273518496}]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:139)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
```

**Version of the framework**
- [x] Spring Boot: 2.3.0.RELEASE
- [x] Spring Cloud: Hoxton.SR5
- [x] Spring Cloud Stream: 3.0.5.RELEASE
- [x] Spring Cloud Stream Schema: 2.2.1.RELEASE

**Expected behavior**
I should be able to publish to the three topics independently

**Screenshots**
N/A

**Additional context**
I am migrating from the Legacy annotation based approach

**Comment by garyrussell** [comment]
`@PostConstruct` is too early in the application context lifecycle to start sending messages; try using an `ApplicationRunner` instead.

**Comment by juliuskrah** [comment]
@garyrussell moving the publication to an `ApplicationRunner` solves this problem
