### ISSUE TITLE
Hoxton.SR3 upgrade to Hoxton.SR7 , Unable to start properly

### ISSUE THREAD

**Issue by tangdelong** [spring-cloud/spring-cloud-stream#2013]
application.yml
```
server:
  port: 8004

spring:
  application:
    name: spring-cloud-rabbit-service-4
  cloud:
    stream:
      binders:
        local_rabbit:
          type: rabbit
          environment: 
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      function.definition: myQueue;
      bindings:
        myQueue-in-0:
          destination: myExchange
          group: myQueue
      rabbit:
        bindings:
          myQueue-in-0:
            consumer:
              bindingRoutingKey: 1
              queueNameGroupOnly: true 
              exchangeType: direct 
```

Java Code
```

@Service
public class MessageListener {


    @Bean
    public Consumer<Flux<String>> myQueue() {
        return flux -> {
            flux.subscribe(data ->{
                System.out.println("rabbit-server-4 消费："+ data);
            });
        };
    }

}

```

Project start exception
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-08-07 13:34:03.493 ERROR 62946 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionInitializer' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/integration/util/IntegrationReactiveUtils
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at spring.cloud.stream.rabbit.RunningService4.main(RunningService4.java:20) [classes/:na]
Caused by: java.lang.NoClassDefFoundError: org/springframework/integration/util/IntegrationReactiveUtils
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder.lambda$bindFunctionToDestinations$3(FunctionConfiguration.java:383) ~[spring-cloud-stream-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_151]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[na:1.8.0_151]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438) ~[na:1.8.0_151]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder.bindFunctionToDestinations(FunctionConfiguration.java:384) ~[spring-cloud-stream-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder.afterPropertiesSet(FunctionConfiguration.java:339) ~[spring-cloud-stream-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 16 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.integration.util.IntegrationReactiveUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_151]
	... 29 common frames omitted

```

**Comment by olegz** [comment]
There is a very good chance you are overriding some versions of certain dependencies. In this case Spring Integration dependency is not matching up to what is expected. 
You can also have some issues with your local maven repo, refreshing i would help

**Comment by sakthidurai** [comment]
Looks like the release train Hoxton.SR7 does not contain latest spring-integration-core dependency. I faced a same error and adding the latest spring integration core(5.3.1 or 5.3.2) to the pom fixed the issue.
< dependency >
    < groupId >org.springframework.integration< /groupId >
    < artifactId >spring-integration-core< /artifactId >
    < version >5.3.1.RELEASE< /version >
< /dependency >

**Comment by tangdelong** [comment]
> There is a very good chance you are overriding some versions of certain dependencies. In this case Spring Integration dependency is not matching up to what is expected.
> You can also have some issues with your local maven repo, refreshing it would help
> 
> 很有可能您正在覆盖某些依赖关系的版本。在这种情况下，Spring Integration 依赖项不符合预期。您也可以有一些问题与您的当地专家回购，刷新它会有所帮助


> There is a very good chance you are overriding some versions of certain dependencies. In this case Spring Integration dependency is not matching up to what is expected.
> You can also have some issues with your local maven repo, refreshing it would help

thank you , I use the question. My Spring Boot version is 2.2.6, so upgrading to the latest 2.3.2 is fine

**Comment by tangdelong** [comment]
> There is a very good chance you are overriding some versions of certain dependencies. In this case Spring Integration dependency is not matching up to what is expected.
> You can also have some issues with your local maven repo, refreshing it would help

thank you , I use the question. My Spring Boot version is 2.2.6, so upgrading to the latest 2.3.2 is fine

**Comment by tangdelong** [comment]
> Looks like the release train Hoxton.SR7 does not contain latest spring-integration-core dependency. I faced a same error and adding the latest spring integration core(5.3.1 or 5.3.2) to the pom fixed the issue.
> < dependency >
> < groupId >org.springframework.integration< /groupId >
> < artifactId >spring-integration-core< /artifactId >
> < version >5.3.1.RELEASE< /version >
> < /dependency >

thank you , I use the question. My Spring Boot version is 2.2.6, so upgrading to the latest 2.3.2 is fine
