### ISSUE TITLE
The FunctionConfiguration createFunctionHandler method's FunctionWrapper prevents proper argument resolution 

### ISSUE THREAD

**Issue by zergeborg** [spring-cloud/spring-cloud-stream#2019]
**Describe the issue**
When I define a message handler as a type of `Function<ClassWhichImplementsSpecificRecord, ClassWhichImplementsSpecificRecord>` and I try to use it with Kafka binding to consume messages of `application/avro` content-type, the framework throws `java.lang.ClassCastException`

Stacktrace:
```java
Caused by: java.lang.ClassCastException: class java.lang.Object cannot be cast to class some.package.ClassWhichImplementsSpecificRecord (java.lang.Object is in module java.base of loader 'bootstrap'; some.package.ClassWhichImplementsSpecificRecord is in unnamed module of loader 'app')
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunction(SimpleFunctionRegistry.java:511) ~[spring-cloud-function-context-3.0.10.RELEASE.jar:3.0.10.RELEASE]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:599) ~[spring-cloud-function-context-3.0.10.RELEASE.jar:3.0.10.RELEASE]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:453) ~[spring-cloud-function-context-3.0.10.RELEASE.jar:3.0.10.RELEASE]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:441) ~[spring-cloud-function-context-3.0.10.RELEASE.jar:3.0.10.RELEASE]
	at org.springframework.cloud.stream.function.PartitionAwareFunctionWrapper.apply(PartitionAwareFunctionWrapper.java:71) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:609) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper$HandlerMethod.invoke(MessagingMethodInvokerHelper.java:1104) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.invokeHandlerMethod(MessagingMethodInvokerHelper.java:582) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:477) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:355) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:108) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	... 35 common frames omitted
```

**To Reproduce**
1. Create a producer which sends Avro messages
2. Consume the message with the message handler defined above

**Version of the framework**
Hoxton.SR8

**Expected behavior**
I expect that the framework honors the type arguments in the `Function` declaration

**Screenshots**
N/A

**Additional context**
The framework wraps the actual function into a `FunctionWrapper` when the `createFunctionHandler` method is called inside the `FunctionConfiguration`. This has a completely different method signature with an apply method which returns an `Object`. This wrapper is used in all the subsequent argument resolvers instead of the actual wrapped function which prevents all and every conversion attempts to succeed.

By the way, everything works fine with annotations. This only happens if I try to use the functional programming style.

**Comment by zergeborg** [comment]
I have some more info. I saw that someone reported a similar `ClassCastException` and that issue also references an old ticket. In that [old ticket](https://github.com/spring-cloud/spring-cloud-stream/issues/1832) there is a proposed workaround, namely the following:
```java
	@Component
	public class OnStartup implements ApplicationListener<ContextRefreshedEvent> {

		private final DefaultListableBeanFactory context;

		@Autowired
		public OnStartup(DefaultListableBeanFactory context) {
			this.context = context;
		}

		@Override
		public void onApplicationEvent(ContextRefreshedEvent event) {
			if (context != null && context
					.containsBean(IntegrationContextUtils.MESSAGE_HANDLER_FACTORY_BEAN_NAME)) {
				context.removeBeanDefinition(IntegrationContextUtils.MESSAGE_HANDLER_FACTORY_BEAN_NAME);
			}
		}
	}
```

This seems to make the class cast exception go away. I don't know what might be the side effects of this workaround though.

**Comment by olegz** [comment]
Spring Cloud Stream core does not support `application/avro`. Did you add custom avro Message Converter or are you using schema registry? IN any event it would be nice if you can provide a link to a sample project so we can reproduce it

**Comment by samragu** [comment]
This issue looks similar to the one I submitted (#2045) and I have attached a complete project to reproduce it. I am using a schema registry and the builit-in AvroRegistrySchemaMessageConverter. Please mark my ticket a duplicate if these issues are the same. Thanks

**Comment by olegz** [comment]
Duplicate to #2045
