### ISSUE TITLE
spring cloud stream[Hoxton.SR8]: Caused by: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.example.demo.util.Product

### ISSUE THREAD

**Issue by dotw** [spring-cloud/spring-cloud-stream#2020]
**Describe the issue**
I have 2 instances and one is a producer, another is a consumer.

I'm using EmiiterProcess<Message<?>> to send a message like below in the producer
```java
    @RequestMapping(path = "/", method = POST, consumes = "*/*")
    @ResponseStatus(HttpStatus.ACCEPTED)
    public void handleRequest(@RequestBody Product body, @RequestHeader(HttpHeaders.CONTENT_TYPE) Object contentType) throws Exception {
        Event<String, Product> event = new Event(Event.Type.CREATE,body.getId(), body);
        Message<?> message = MessageBuilder.withPayload(event)
                .setHeader("spring.cloud.stream.sendto.destination", body.getId()).build();
        processor.onNext(message);
    }
```
In the consumer instance, I'm using the following code to process the message. The code is broken at the comment line.
```java
        @Bean
        public Consumer<Event<String, Product>> receive1() {
            return data -> {
                logger.info("Data received from customer-1..." + data);
                Product product = data.getData(); // <-- the code is broken here.
                logger.info(" product id is " + product.getId());
            };
        }

        @Bean
        public Consumer<Event<String, Product>> receive2() {
            return data -> {
                logger.info("Data received from customer-2..." + data);
                Product product = data.getData();
                logger.info(" product id is " + product.getId());
            };
        }
```
the stack details:
```
2020-09-24 14:19:10.715 ERROR 47557 --- [d-1.customers-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred during processing message in 'MethodInvokingMessageProcessor' [org.springframework.integration.handler.MethodInvokingMessageProcessor@1d7e41cf]; nested exception is java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.example.demo.util.Product, failedMessage=GenericMessage [payload=byte[157], headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedExchange=customerId-1, amqp_deliveryTag=1, deliveryAttempt=3, amqp_consumerQueue=customerId-1.customers, amqp_redelivered=false, accept=application/json, amqp_receivedRoutingKey=customerId-1, spring.cloud.stream.sendto.destination=customerId-1, amqp_timestamp=Thu Sep 24 14:19:07 CST 2020, amqp_messageId=337ba98c-7b16-aeca-780b-588c4786cdb8, id=82a9745a-fb3f-ed77-4541-c8b20807ee41, amqp_consumerTag=amq.ctag-kwUIzCJO2gVWb5SOJJMDMA, sourceData=(Body:'{"eventType":"CREATE","key":"customerId-1","data":{"id":"customerId-1","name":"100","category":null,"target":null},"eventCreatedAt":"2020-09-24T14:19:07.51"}' MessageProperties [headers={spring.cloud.stream.sendto.destination=customerId-1, accept=application/json}, timestamp=Thu Sep 24 14:19:07 CST 2020, messageId=337ba98c-7b16-aeca-780b-588c4786cdb8, contentType=application/json, contentLength=0, receivedDeliveryMode=PERSISTENT, priority=0, redelivered=false, receivedExchange=customerId-1, receivedRoutingKey=customerId-1, deliveryTag=1, consumerTag=amq.ctag-kwUIzCJO2gVWb5SOJJMDMA, consumerQueue=customerId-1.customers]), contentType=application/json, timestamp=1600928347611}]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:111)
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:104)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:134)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:69)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$1300(AmqpInboundChannelAdapter.java:65)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.lambda$onMessage$0(AmqpInboundChannelAdapter.java:294)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.onMessage(AmqpInboundChannelAdapter.java:290)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1585)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1504)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1492)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1483)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1427)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:970)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:916)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:83)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1291)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1197)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.example.demo.util.Product
	at com.example.demo.consumer.ConsumerApplication$TestSink.lambda$receive1$0(ConsumerApplication.java:29)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunction(SimpleFunctionRegistry.java:530)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:599)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:453)
```

**To Reproduce**
1. clone https://github.com/dotw/spring-cloud-stream-demo.git
2. run `ProducerApplication.java` and `ConsumerApplication.java`
3. run `curl -H "Content-Type: application/json" -X POST -d '{"id":"customerId-1","name":"100"}' http://localhost:9091`
4. check error for `ConsumerApplication`

**Version of the framework**
Hoxton.SR8
**Expected behavior**
Message payload can be converted to `Product` type automatically.

**Comment by dotw** [comment]
refer to #1832 and @olegz suggests opening a new issue.

**Comment by olegz** [comment]
This issue needs to be addressed at Spring Cloud Function, so I'll transfer it
