### ISSUE TITLE
NPE when using mixed reactive kafka/streams bindings in spring boot 2.3.4

### ISSUE THREAD

**Issue by rgonciarz** [spring-cloud/spring-cloud-stream#2028]
**Describe the issue**
Kafka consumer cannot be created, NPE is thrown when starting the app (KafkaMessageListenerContainer)

Setup:
topic1 -> topologyA (kafka streams binding) -> topic2 
topic2 -> topologyRconsumer (kafka flux binding) -> processor (sink)
topologyRsupplier (processor/sink) -> topologyB

**To Reproduce**
I created a small project that may help to reproduce the issue:
[https://github.com/rgonciarz/reactive-topology-chain/tree/master](https://github.com/rgonciarz/reactive-topology-chain/tree/master) - working version 2.3.3

1. Just change branch master -> 2.3.4 or update Spring Boot from 2.3.3 to 2.3.4 or snapshot

[https://github.com/rgonciarz/reactive-topology-chain/tree/2.3.4](https://github.com/rgonciarz/reactive-topology-chain/tree/2.3.4) - updated spring boot to 2.3.4

Affected versions: 2.3.4+ (including snapshot)

```
2020-10-08 17:07:42.262 ERROR 20487 --- [           main] o.s.cloud.stream.binding.BindingService  : Failed to create consumer binding; retrying in 30 seconds

org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:461) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:90) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:176) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:133) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:112) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:62) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at wr.reactive.ApplicationKt.main(Application.kt:14) ~[main/:na]
Caused by: java.lang.NullPointerException: null
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.checkDeserializer(KafkaMessageListenerContainer.java:940) ~[spring-kafka-2.5.6.RELEASE.jar:2.5.6.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.<init>(KafkaMessageListenerContainer.java:668) ~[spring-kafka-2.5.6.RELEASE.jar:2.5.6.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer.doStart(KafkaMessageListenerContainer.java:302) ~[spring-kafka-2.5.6.RELEASE.jar:2.5.6.RELEASE]
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:338) ~[spring-kafka-2.5.6.RELEASE.jar:2.5.6.RELEASE]
	at org.springframework.kafka.listener.ConcurrentMessageListenerContainer.doStart(ConcurrentMessageListenerContainer.java:204) ~[spring-kafka-2.5.6.RELEASE.jar:2.5.6.RELEASE]
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:338) ~[spring-kafka-2.5.6.RELEASE.jar:2.5.6.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.doStart(KafkaMessageDrivenChannelAdapter.java:317) ~[spring-integration-kafka-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.integration.endpoint.AbstractEndpoint.start(AbstractEndpoint.java:156) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:414) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	... 24 common frames omitted
```

**Comment by rgonciarz** [comment]
I was able to recreate this NPE with a bit simpler setup with just one reactive topology. Please take a look here as well:
https://github.com/spring-cloud/spring-cloud-stream/issues/2029
