### ISSUE TITLE
NullPointerException when starting KafkaMessageListenerContainer with Spring Boot 2.2.10.RELEASE

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream#2033]
When updating spring-boot to version 2.2.10.RELEASE is giving an exception while starting consumer:

```
org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:461) ~[spring-cloud-stream-3.0.6.RELEASE.jar:3.0.6.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:90) ~[spring-cloud-stream-3.0.6.RELEASE.jar:3.0.6.RELEASE]
...
Caused by: java.lang.NullPointerException: null
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.checkDeserializer(KafkaMessageListenerContainer.java:900) ~[spring-kafka-2.3.11.RELEASE.jar:2.3.11.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.<init>(KafkaMessageListenerContainer.java:681) ~[spring-kafka-2.3.11.RELEASE.jar:2.3.11.RELEASE]
```

The problem is related to the establishment of consumer-properties 'key.deserializer' and 'value.deserializer':

```
spring.cloud.stream.binders.kafka-demo.environment.spring.cloud.stream.kafka.binder.consumer-properties.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.cloud.stream.binders.kafka-demo.environment.spring.cloud.stream.kafka.binder.consumer-properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
```

and this other issue with Spring kafka: https://github.com/spring-projects/spring-kafka/issues/1597#issuecomment-704986725

Attached is a demo application that reproduces the error.
[demo-streams.zip](https://github.com/spring-cloud/spring-cloud-stream/files/5378406/demo-streams.zip)

Version of the framework:
- Spring Boot 2.2.10.RELEASE
- Spring Cloud Hoxton.SR6
- Spring Kafka 2.3.11.RELEASE

**Comment by garyrussell** [comment]
This is already fixed. https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/970
