### ISSUE TITLE
Bind a function bean only if there's an existing definition in the configuration

### ISSUE THREAD

**Issue by Chr3is** [spring-cloud/spring-cloud-stream#2035]
**Describe the issue**
We have a configuration which uses `@EnableBinding` and can be enabled conditionally on property. In some tests we have disabled this config to speed up the whole thing. Due to an external dependency which autoconfigures a function-bean spring cloud stream tries to connect to a kafka topic matching the bean name now. The test context can't start because the topic does not exist. This is due to an exception how function beans get registered. If there's only a single function-bean you don't have to define `spring.cloud.function.definition` to bind the function. There's also no possibility to disable the function-scanning. In my opinion there's no reason to skip the registration part via the definition property since it is already considered as best practice (https://github.com/spring-cloud/spring-cloud-stream/blob/master/docs/src/main/asciidoc/spring-cloud-stream.adoc#spring_cloud_function). 

`spring.cloud.function.scan.enabled=false` has no effect on this behavior. E.g. the property name is misleading.

**Quick hack for us**
Define a second function bean in the test context to avoid the binding. This is ugly.

**To Reproduce**
See [demo.zip](https://github.com/spring-cloud/spring-cloud-stream/files/5402880/demo.zip)

**Version of the framework**
Hoxton.SR8

**Expected behavior**
It is always required to define the function-beans via `spring.cloud.function.definition` and/or there should be an option to disable the whole function-bean scanning.

**Comment by olegz** [comment]
Auto-discovery of functions (not requiring `spring.cloud.function.definition`) is one of the features of spring-cloud-stream and its integration with spring-cloud-function. 
If in your test you would like to disable functional configuration you can simply exclude `ContextFunctionCatalogAutoConfiguration` using standard boot mechanism.

Please let us know if you still have issue, otherwise I do not foresee any action on this other then may be some additional documentation.

**Comment by Chr3is** [comment]
I've already tried to exclude the whole autoconfiguration. But if this configuration is missing the inputBindingLifecycle cannot be created due to an exception when the consumer is started (NPE while checking the deserializer, we use confluent KafkaAvroDeserializer) 

`org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)
	at org.spockframework.spring.SpringTestContextManager.prepareTestInstance(SpringTestContextManager.java:56)
	at org.spockframework.spring.SpringInterceptor.interceptInitializerMethod(SpringInterceptor.java:43)
	at org.spockframework.runtime.extension.AbstractMethodInterceptor.intercept(AbstractMethodInterceptor.java:24)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:97)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:475)
	at org.spockframework.runtime.BaseSpecRunner.runInitializer(BaseSpecRunner.java:341)
	at org.spockframework.runtime.BaseSpecRunner.runInitializer(BaseSpecRunner.java:336)
	at org.spockframework.runtime.BaseSpecRunner.initializeAndRunIteration(BaseSpecRunner.java:274)
	at org.spockframework.runtime.BaseSpecRunner.runSimpleFeature(BaseSpecRunner.java:266)
	at org.spockframework.runtime.BaseSpecRunner.doRunFeature(BaseSpecRunner.java:260)
	at org.spockframework.runtime.BaseSpecRunner$5.invoke(BaseSpecRunner.java:243)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
	at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:235)
	at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:185)
	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:95)
	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:81)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:73)
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:64)
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:461)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:90)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143)
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:170)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:133)
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:112)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	... 63 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.checkDeserializer(KafkaMessageListenerContainer.java:940)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.<init>(KafkaMessageListenerContainer.java:668)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer.doStart(KafkaMessageListenerContainer.java:302)
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:338)
	at org.springframework.kafka.listener.ConcurrentMessageListenerContainer.doStart(ConcurrentMessageListenerContainer.java:204)
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:338)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.doStart(KafkaMessageDrivenChannelAdapter.java:317)
	at org.springframework.integration.endpoint.AbstractEndpoint.start(AbstractEndpoint.java:156)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:414)
	... 73 common frames omitted`

**Comment by olegz** [comment]
Actually, try to disable `org.springframework.cloud.stream.function.FunctionConfiguration` instead

**Comment by Chr3is** [comment]
Unfortunately this leads to the same NPE

**Comment by olegz** [comment]
ok, i'l look, but what you can try as workaround for now is provide `spring.cloud.function.definition` property and point to non-existing name. For example `spring.cloud.function.definition=blahblah` or `spring.cloud.function.definition=foo|bar` (note the composition). That would put a log message in the console that function can't be found, but no bindings would be created.

Let me know

**Comment by leonard84** [comment]
How about adding an explicit property to disable this behavior? IMHO this would be a cleaner solution than excluding auto-configurations or defining non-existent bindings.

**Comment by Chr3is** [comment]
ApplicationIT = integration test with **disabled** configuration which annotates and configures @EnableBinding
EventbusIT = integration test with **enabled** configuration which annotates and configures @EnableBinding


`spring.cloud.stream.function.definition=foo` -> ApplicationIT starts, EventbusIT does not start
`exclude org.springframework.cloud.stream.function.FunctionConfiguration` -> ApplicationIT starts, EventbusIT does not start
`exclude org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration` -> ApplicationIT starts, EventbusIT does not start
no changes ->  ApplicationIT failes due to unkown kafka topic (single function bean from external dependency), EventbusIT starts


EventbusIT fails **always** with the mentioned approaches because of NPE 
`deserializer = ClassUtils.forName((String) deser, getApplicationContext().getClassLoader());` in `org.springframework.kafka.listener.KafkaMessageListenerContainer#940`

This is due to the applicationContext in `org.springframework.kafka.listener.AbstractMessageListenerContainer` which is **null** 

Adding TestConfiguration to test context with no other changes results in successful ApplicationIT and EventbusIT:
```
    @TestConfiguration
    static class TestConfig {

        @Bean
        Supplier<String> testSupplier() {
            return { -> "Test" }; //groovy
        }
    }
```

because:

ApplicationIT has no @EnableBinding configuration due to disabled config but NOW two supplier -> without a function definition in the configuration nothing is binded
EventbusIT has @EnableBinding configuration -> function binding does not apply at all due to the annotation

**Comment by Chr3is** [comment]
With the exclusion of `org.springframework.cloud.stream.function.FunctionConfiguration` (and pinning Spring Boot to 2.3.3.Release) everything works now. 

However we should provide a property which can be  be used to enable/disable the exceptional behavior which applies only to a context with a single function bean instead of excluding autoconfigurations.

I think the NPE with Hoxton.SR8 and Spring Boot 2.3.4.RELEASE is a new issue .. I can open a ticket for that. The NPE can be reproduced with the provided demo app (test4)

**Comment by garyrussell** [comment]
The NPE is already fixed in spring-kafka as well as the binder.

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/968

**Comment by garyrussell** [comment]
The NPE is already fixed in spring-kafka as well as the binder.

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/968

The work around is to use a snapshot of s-k until it is released next week.

**Comment by Chr3is** [comment]
@garyrussell test4 in the demo project works with  spring-kafka 2.5.7.BUILD-SNAPSHOT and Spring Boot 2.3.4.RELEASE now (y)

**Comment by Chr3is** [comment]
The fix with excluding the autoconfiguration works but I've closed the issue by mistake. The real request was: see "Expected behavior"
