### ISSUE TITLE
Fix Routing expression with Spring cloud stream

### ISSUE THREAD

**Issue by ahmed-boucetta** [spring-cloud/spring-cloud-stream#2087]
Hello,

I try to use this routing expression : 

 routing-expression : 'payload.get('type').equals('PURGE_REQUESTED') ? 'purgeRequestedReceived' : null'

 but i have exception when i try use routing-expression with null Caused by: org.springframework.messaging.MessageHandlingException: error occurred during processing message in 'MethodInvokingMessageProcessor' [org.springframework.integration.handler.MethodInvokingMessageProcessor@65206d1f]; nested exception is java.lang.IllegalArgumentException: Failed to resolve function name based on routing expression

thanks.

**Comment by olegz** [comment]
Please include full stack trace when you are reporting an issue. What you have posted is not enough to triage.
Also, keep in mind that executing expression on the payload is highly discouraged since at the time the expression is evaluated the payload is in its raw form.

**Comment by ahmed-boucetta** [comment]
Thank you for your answer,

we try to ignore all messages that do not have the payload with the type PURGE_REQUESTED please found  stack trace:

Caused by: java.lang.IllegalArgumentException: Failed to resolve function name based on routing expression 'payload.get('type').equals('PURGE_REQUESTED') ? 'purgeRequestedReceived' : null'
        at org.springframework.util.Assert.hasText(Assert.java:289)
        at org.springframework.cloud.function.context.config.RoutingFunction.functionFromExpression(RoutingFunction.java:174)
        at org.springframework.cloud.function.context.config.RoutingFunction.route(RoutingFunction.java:109)
        at org.springframework.cloud.function.context.config.RoutingFunction.apply(RoutingFunction.java:77)
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunction(SimpleFunctionRegistry.java:543)
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:631)
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:485)
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:473)
        at org.springframework.cloud.stream.function.PartitionAwareFunctionWrapper.apply(PartitionAwareFunctionWrapper.java:71)
        at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:653)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:129)
        at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:112)
        at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:55)
        at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:387)
        at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:92)
        at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:117)
        at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:375)
        at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:169)
        at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:154)
        at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.invokeExpression(MessagingMethodInvokerHelper.java:638)
        at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.fallbackToInvokeExpression(MessagingMethodInvokerHelper.java:631)
        at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.processInvokeExceptionAndFallbackToExpressionIfAny(MessagingMethodInvokerHelper.java:615)
        at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.invokeHandlerMethod(MessagingMethodInvokerHelper.java:586)
        at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:478)
        at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:356)
        at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:108)
        ... 34 more

**Comment by olegz** [comment]
As I said before, you are executing expression on payload which you assume is converted to some POJO and it is not. 
We (at the framework level) do not know what your expression may be. So imagine you have two functions with different POJOs each (for input). We need to know which POJO type we need to use for type conversion. But to do that we need to know which function to invoke. And we expect that from the routing expression. That is why unless you're prepared to operate on raw data (byte[]), you should structure your expression based on message headers. 

Another analogy is post office. The mailman does not open the envelope to read its payload to determine who it is need to be delivered to. It uses headers (things written on envelope)

**Comment by LouisB83** [comment]
Hello Olegz,
I'm with @ahmed-boucetta 
Thank you for your answer.

We are connected to a Kafka topics, where there is different messages incoming.
We want to manage only one type of message. And dismiss the other when we consume them.
So, we think to use the routing-expression.
The problem is the use of the null value in the routing-expression.
We tried this : 
routing-expression: "T(java.lang.System).nanoTime() % 2 == 0 ? null : null"
(to be sure he go on the null).

And when we receive a msg, we got this error : 
Caused by: java.lang.IllegalArgumentException: Failed to resolve function name based on routing expression 'T(java.lang.System).nanoTime() % 2 == 0 ? null : null'
	at org.springframework.util.Assert.hasText(Assert.java:289) ~[spring-core-5.3.2.jar:5.3.2]
	at org.springframework.cloud.function.context.config.RoutingFunction.functionFromExpression(RoutingFunction.java:165) ~[spring-cloud-function-context-3.1.0.jar:3.1.0]

Is it possible to dismiss message, without create a Consumer for them ?

(in an old app, we used SCSt with StreamListener and condition on it. It worked. We want to do similar thing with SCSt and Spring Function).

Thanks.

**Comment by LouisB83** [comment]
For the use of the null in the routing-expression, to dismiss msg, we saw your example here : 
https://gitter.im/spring-cloud/spring-cloud-stream?at=5e63d0c4f046a30bbe4bed18
where you wrote : 
"It is supported
here is an example expression from one of our tests that is based on header --spring.cloud.function.routing-expression=headers.contentType.toString().equals('text/plain') ? 'echo' : null

the above will route all messages with content type text/plain to function called echo, the rest will be dismissed. But of course you can change the expression and route to many functions.
"

**Comment by olegz** [comment]
Indeed this is a regression which we'll fix and backport so you can have it after January 26.
Meanwhile you can do a workaround. Instead of sending it to `null`, you can create an empty Consumer
```
@Bean
public Consumer<?> devNull() {
}
```
And have expression be something like: `--spring.cloud.function.routing-expression=headers.contentType.toString().equals('text/plain') ? 'echo' : 'devNull'`

**Comment by LouisB83** [comment]
Thanks Olegz.
We will try the workaround.

**Comment by olegz** [comment]
The more I think about it the more I realize that while you may be seeking this behavior it is not really a common expectation. So the workaround I suggested is actually the right way of handling it since it will also allow you to log it or do something else with it before you actually ignore it. 
So, what I'll do instead is update documentation with this scenario and suggested approach before I close this issue
