### ISSUE TITLE
Automatically send null values at startup the project .Producer from Consumer

### ISSUE THREAD

**Issue by DimitarChikalanov** [spring-cloud/spring-cloud-stream#2095]
My code Producer
 @Bean
    public Supplier<Mono<RegisterUserModel>> publishUser() {
        return () ->{
            System.out.println(1233);
            return Mono.just(new RegisterUserModel());
        };
    }
My code Consumer

  @Bean
    @Override
    public Consumer<KStream<String, RegisterUserModel>> onUserRegistered() {

        return input -> input.foreach((EmptyString, InputProfileModel) -> {

            User user = new User();
            user.setId(InputProfileModel.getId());
            user.setFirstName(InputProfileModel.getFirstName());
            user.setLastName(InputProfileModel.getLastName());
            user.setBornOn(InputProfileModel.getBornOn());
            logger.info("{} {} is registered successfully in Database!", InputProfileModel.getFirstName(), InputProfileModel.getLastName());
            this.userRepository.saveAndFlush(user);
        });
    }

1.Start the app from producer
2.Start the app from consumer
3.Error from consumer
Exception in thread "profile-1b3ad9c9-2323-457e-8891-8930c60ecd10-StreamThread-1" org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000000, topic=USER_HAS_BEEN_REGISTERED1, partition=0, offset=0, stacktrace=org.springframework.orm.jpa.JpaSystemException: ids for this class must be manually assigned before calling save(): bg.codexio.ungamified.profile.domain.entity.User; nested exception is org.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save(): bg.codexio.ungamified.profile.domain.entity.User
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:331)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
4.Log kafka 

root@dimitar-Vostro-5490:/opt/kafka# bin/kafka-console-consumer.sh --topic USER_HAS_BEEN_REGISTERED1  --from-beginning --bootstrap-server localhost:9092
{"id":null,"firstName":null,"lastName":null,"bornOn":null}

**Comment by olegz** [comment]
I am not sure what does this have to do with spring-cloud-stream. The root of your exception is somewhere in `org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)`

**Comment by olegz** [comment]
Closing due to lack of follow up from the reporter
