### ISSUE TITLE
ClassCastException when returning a plain object with the binding function

### ISSUE THREAD

**Issue by Chr3is** [spring-cloud/spring-cloud-stream#2113]
In https://github.com/spring-cloud/spring-cloud-stream/commit/cedacc8b17e6121342f4945b8c9b3593dbaa550e#diff-7b481e6af9ca6e4b2759e2f498434346fd0882918f80c6adc2a95538cd33b6ebR585 the logic was changed how the message is send. 

This introduces a ClassCastException when using something like this:

```
@Nullable
public R handleIncomingMessage(Message<T> eventMessage) {
  T event = eventMessage.getPayload();
  ...
  return handleEvent(event, topic, partitionId, consumer, acknowledgment);
}
```

When wrapping the result as message this exception does not appear eg:

```
  @Nullable
  public Message<R> handleIncomingMessage(Message<T> eventMessage) {
      T event = eventMessage.getPayload();
      ...
      R result = handleEvent(event, topic, partitionId, consumer, acknowledgment);
      return result != null ? MessageBuilder.withPayload(result).build() : null; //<--- convert if not null
  }
```

Exception:
```
2021-02-09 19:36:48.055 ERROR 2040 --- [container-0-C-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@33d8b388]; nested exception is java.lang.ClassCastException: class ...MyEvent cannot be cast to class org.springframework.messaging.Message (...MyEvent and org.springframework.messaging.Message are in unnamed module of loader 'app'), failedMessage=GenericMessage [payload={***}), kafka_groupId=***, target-protocol=kafka}]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:396)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:78)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:455)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:429)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2065)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2047)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1984)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1924)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1812)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1531)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1178)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1075)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class ...MyEvent cannot be cast to class org.springframework.messaging.Message (...MyEvent and org.springframework.messaging.Message are in unnamed module of loader 'app')
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.doSendMessage(FunctionConfiguration.java:589)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:575)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	... 26 more

2021-02-09 19:36:48.084 ERROR 2040 --- [container-0-C-1] o.s.k.l.SeekToCurrentErrorHandler        : Backoff none exhausted for ConsumerRecord(***)

org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@33d8b388]; nested exception is java.lang.ClassCastException: class ...MyEvent cannot be cast to class org.springframework.messaging.Message (...MyEvent and org.springframework.messaging.Message are in unnamed module of loader 'app'), failedMessage=GenericMessage [payload={***}]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:2113)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:2098)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1997)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1924)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1812)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1531)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1178)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1075)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@33d8b388]; nested exception is java.lang.ClassCastException: class ...MyEvent cannot be cast to class org.springframework.messaging.Message (...MyEvent and org.springframework.messaging.Message are in unnamed module of loader 'app')
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:396)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:78)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:455)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:429)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2065)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2047)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1984)
	... 8 common frames omitted
Caused by: java.lang.ClassCastException: class ...MyEvent cannot be cast to class org.springframework.messaging.Message (...MyEvent and org.springframework.messaging.Message are in unnamed module of loader 'app')
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.doSendMessage(FunctionConfiguration.java:589)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:575)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	... 26 common frames omitted
```

This behaviour appears with the current master (org.springframework.cloud:spring-cloud-stream:jar:3.1.2-SNAPSHOT)
```
[INFO] +- org.springframework.cloud:spring-cloud-starter-stream-kafka:jar:3.1.0:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-stream-binder-kafka:jar:3.1.0:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-stream-binder-kafka-core:jar:3.1.0:compile
[INFO] |     |  \- org.springframework.integration:spring-integration-kafka:jar:5.4.3:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-stream:jar:3.1.2-SNAPSHOT:compile
[INFO] |     +- org.apache.kafka:kafka-clients:jar:2.6.0:compile
[INFO] |     |  +- com.github.luben:zstd-jni:jar:1.4.4-7:compile
[INFO] |     |  +- org.lz4:lz4-java:jar:1.7.1:compile
[INFO] |     |  \- org.xerial.snappy:snappy-java:jar:1.1.7.3:compile
[INFO] |     \- org.springframework.kafka:spring-kafka:jar:2.6.5:compile
[INFO] +- org.springframework.cloud:spring-cloud-schema-registry-client:jar:1.1.0:compile
[INFO] |  +- org.springframework:spring-messaging:jar:5.3.3:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.4:compile
[INFO] |  \- org.apache.avro:avro:jar:1.9.2:compile
[INFO] +- io.confluent:kafka-streams-avro-serde:jar:6.0.1:compile
[INFO] |  +- io.confluent:kafka-avro-serializer:jar:6.0.1:compile
[INFO] |  |  \- io.confluent:kafka-schema-serializer:jar:6.0.1:compile
[INFO] |  +- io.confluent:kafka-schema-registry-client:jar:6.0.1:compile
[INFO] |  |  +- jakarta.ws.rs:jakarta.ws.rs-api:jar:2.1.6:compile
[INFO] |  |  \- io.swagger:swagger-annotations:jar:1.6.2:compile
[INFO] |  \- io.confluent:common-utils:jar:6.0.1:compile
[INFO] +- org.springframework.cloud:spring-cloud-stream:test-jar:test-binder:3.1.0:test
[INFO] |  +- org.springframework.integration:spring-integration-core:jar:5.4.3:compile
[INFO] |  |  \- io.projectreactor:reactor-core:jar:3.4.2:compile
[INFO] |  +- org.springframework.integration:spring-integration-jmx:jar:5.4.3:compile
[INFO] |  +- org.springframework.retry:spring-retry:jar:1.3.1:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-function-context:jar:3.1.0:compile
[INFO] |     +- net.jodah:typetools:jar:0.6.2:compile
[INFO] |     \- org.springframework.cloud:spring-cloud-function-core:jar:3.1.0:compile
```

Reason: The result object is not always a message and therefore it has to be checked before casting it.

**Comment by olegz** [comment]
As I said before, I can not reproduce it. And I asked you for a sample project or test case with bare minimum that does.  . .
Anyway, I added (just for sanity) another test (with the above commit) which to the best of my understanding reproduces your scenario. 

Also, keep in mind that regardless of what you are returning from the function (Message or POJO) it will be wrapped in Message anyway, so it's always a Message. So the code in FunctionConfiguration that your are pointing to may need to be improved, but that's a different discussion. My point is that by the time it gets there the value could not be non-Message.

Also, I noticed you have `spring-cloud-function-core - 3.1.0`; The s-c-stream master is using 3.1.2-SNAPSHOT

**Comment by Chr3is** [comment]
@olegz I was able to reproduce the issue in a demo application (see attached file) - Seems to be appear if avro is used.

See the comments in the test cases & the method signatures of the functions & imperative methods.
[demo.zip](https://github.com/spring-cloud/spring-cloud-stream/files/5964535/demo.zip)

**Comment by Chr3is** [comment]
Hey @olegz , I don't want to be impolite or annoying, I'm just asking for an ack so that I know you've seen the demo application in the comment above which reproduces the ClassCastException. Maybe you want to reopen this issue if you had time to look into the demo.

Current fix for us is to wrap the input and output param as message eg. `Function<Message<Foo>, Message<Bar>>` which is okay but the imperative and functional approach such behave in the same way in my opinion.

**Comment by olegz** [comment]
@Chr3is no problem, actually thank you for reminding me. We generally don't monitor closed issues, so in the future especially if you have a demo to share your issue feel free to open a new one. That will get our attention ;)
Cheers
