### ISSUE TITLE
Non-retryable binding creation due to BeanDefinitionOverrideExceptions if a runtime exception is thrown by a BindingCreatedEvent listener

### ISSUE THREAD

**Issue by stephaneseng** [spring-cloud/spring-cloud-stream#2118]
**Describe the issue**

I've implemented a custom [BindingCreatedEvent](https://github.com/spring-cloud/spring-cloud-stream/blob/v3.1.1/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/BindingCreatedEvent.java) listener to execute some actions after each binding creation.
Unfortunately executing these actions may trigger runtime exceptions.

When that is the case, a problem occurs as:

* The first binding creation attempt fails as expected, because of the exception thrown by the event listener
* But subsequent binding creation attempts also fail due to BeanDefinitionOverrideExceptions, unrelated to the custom event listener

**To Reproduce**

This problem can be reproduced by using the https://github.com/stephaneseng/spring-cloud-stream-2118 project:

1. Start a RabbitMQ instance locally: `docker run --net host --rm rabbitmq:3.8.11-management`
2. Run the project: `mvn spring-boot:run`

The first binding creation attempt fails as expected, as the event listener is intentionally always throwing a runtime exception. 
But after every 30 seconds, other binding creation attempts also fail, with this error:

```
2021-02-16 21:32:29.898 ERROR 4987 --- [ask-scheduler-1] o.s.cloud.stream.binding.BindingService  : Failed to create consumer binding; retrying in 30 seconds

org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:462) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:91) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.BindingService.lambda$rescheduleConsumerBinding$1(BindingService.java:201) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.3.jar:5.3.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'exchange.queue.errors.recoverer' defined in null: Cannot register bean definition [Generic bean: class [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'exchange.queue.errors.recoverer': There is already [Generic bean: class [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:995) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.context.support.GenericApplicationContext.registerBeanDefinition(GenericApplicationContext.java:330) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.BeanDefinitionReaderUtils.registerBeanDefinition(BeanDefinitionReaderUtils.java:164) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.doRegisterBean(AnnotatedBeanDefinitionReader.java:285) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:233) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.registerBean(AnnotationConfigApplicationContext.java:198) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:687) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:639) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stBeanDefinitionReaderUtilseam.binder.rabbit.RabbitMessageChannelBinder.createConsumerEndpoint(RabbitMessageChannelBinder.java:519) ~[spring-cloud-stream-binder-rabbit-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.createConsumerEndpoint(RabbitMessageChannelBinder.java:130) ~[spring-cloud-stream-binder-rabbit-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:408) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	... 11 common frames omitted
```

**Cause**

As indicated by the stack trace, the BeanDefinitionOverrideException occurs in [AbstractMessageChannelBinder#registerErrorInfrastructure(ConsumerDestination, String, C, boolean)](https://github.com/spring-cloud/spring-cloud-stream/blob/803c253810105066cb985bc4d7a3ac7d5773fc7f/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L676-L688), where an ErrorMessageSendingRecoverer bean is registered.

This operation fails if a bean already exists with the same name, which is the case here as each binding creation attempt causes the registration of an ErrorMessageSendingRecoverer bean, see [RabbitMessageChannelBinder#createConsumerEndpoint(ConsumerDestination, String, ExtendedConsumerProperties<RabbitConsumerProperties>)](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/e85d361126f3ecbba6537bb8357d8f6f83899364/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/RabbitMessageChannelBinder.java#L519-L520) in spring-cloud-stream-binder-rabbit.

Should this behavior be fixed so that binding creations can be retried in case of runtime exceptions?
Or should BindingCreatedEvent event listeners avoid throwing such exceptions?

**Version of the framework**

* spring-cloud-stream@3.1.1
* spring-cloud-stream-binder-rabbit@3.1.1

**Comment by garyrussell** [comment]
>Or should BindingCreatedEvent event listeners avoid throwing such exceptions?

I think this one; but the framework should really try/catch around the event publishing to protect itself.
