### ISSUE TITLE
If I use spring.main.web -application-type: servlet,  Failed to start！

### ISSUE THREAD

**Issue by yangle94** [spring-cloud/spring-cloud-stream#2122]
If I use spring.main.web -application-type: servlet,

Failed to start！

'org.springframework.boot' version '2.0.3.RELEASE'
'io.spring.dependency-management' version '1.0.11.RELEASE'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-stream-kafka'

error message:

Caused by: org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing HttpHandler bean.
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.getHttpHandler(ReactiveWebServerApplicationContext.java:147) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:99) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:73) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	... 8 common frames omitted

**Comment by olegz** [comment]
The provided  stack trace is incomplete. The information you sharing is also very limited and provides no way for us to reproduce and diagnose the issue. The best thing you can do is create a small app with only relevant parts in it to reproduce the issue and push it to your github repo and send us a link, so we can use it to diagnose the issue.

**Comment by yangle94** [comment]
> 提供的堆栈跟踪不完整。您共享的信息也非常有限，无法让我们重现和诊断问题。最好的办法是创建一个仅包含相关部分的小型应用程序，以重现问题并将其推送到您的github仓库中，并向我们发送链接，以便我们可以使用它来诊断问题。

https://github.com/yangle94/stream-kafka

**Comment by yangle94** [comment]
> The provided stack trace is incomplete. The information you sharing is also very limited and provides no way for us to reproduce and diagnose the issue. The best thing you can do is create a small app with only relevant parts in it to reproduce the issue and push it to your github repo and send us a link, so we can use it to diagnose the issue.

https://github.com/yangle94/stream-kafka

**Comment by olegz** [comment]
I looked at your project, and you are using vey old version of s-c-stream (2.0.0.RELEASE) with incompatible version of s-boot. Please use [Spring Initializr](https://start.spring.io/) to generate new project which will ensure the correct versions
