### ISSUE TITLE
IllegalStateException on App start when using actuator wildcard include along with sleuth with kafka binder

### ISSUE THREAD

**Issue by bbdick** [spring-cloud/spring-cloud-stream#2127]
Springboot version 2.3.9.RELEASE
SpringCloud: Hoxton.SR10
Kafka server: 5.2.1
spring and spring cloud modules used: actuator, prometheus, sleuth, kafka

**Describe the bug**
When using the following application.yml, 
```management.endpoints.enabled-by-default: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "shutdown"
spring:
  application.name: "kafkaBinderDemo"
  cloud.stream:
    defaultBinder: scl
    binders:
      scl:
        type: kafka
        environment.spring.cloud.stream:
          kafka.binder.brokers: "localhost:9092"
      scl1:
        type: kafka
        environment.spring.cloud.stream:
          kafka.binder.brokers: "localhost:9092"
    bindings:
      testOutput:
        destination: "testOutputDev"
        binder: scl1
      testInput:
        destination: "testInputDev"
        group: "demoGroup"
    kafka.binder.autoAddPartitions: true
```
The application fails to start up with the following exception:
```
2021-03-04 16:14:55.614  INFO [kafkaBinderDemo,,,] 24277 --- [           main] o.s.c.s.binder.DefaultBinderFactory      : Creating binder: scl1
2021-03-04 16:14:55.929 ERROR [kafkaBinderDemo,,,] 24277 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@334ebcaa has not been refreshed yet
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1096) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBeanProvider(AbstractApplicationContext.java:1138) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.cloud.context.restart.RestartEndpoint.onApplicationEvent(RestartEndpoint.java:95) ~[spring-cloud-context-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.cloud.context.restart.RestartEndpoint.onApplicationEvent(RestartEndpoint.java:53) ~[spring-cloud-context-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory$1.onApplicationEvent(DefaultBinderFactory.java:288) ~[spring-cloud-stream-3.0.11.RELEASE.jar!/:3.0.11.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.contextLoaded(EventPublishingRunListener.java:97) ~[spring-boot-2.3.9.RELEASE.jar!/:2.3.9.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:65) ~[spring-boot-2.3.9.RELEASE.jar!/:2.3.9.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:393) ~[spring-boot-2.3.9.RELEASE.jar!/:2.3.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.3.9.RELEASE.jar!/:2.3.9.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) ~[spring-boot-2.3.9.RELEASE.jar!/:2.3.9.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:320) ~[spring-cloud-stream-3.0.11.RELEASE.jar!/:3.0.11.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:209) ~[spring-cloud-stream-3.0.11.RELEASE.jar!/:3.0.11.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:140) ~[spring-cloud-stream-3.0.11.RELEASE.jar!/:3.0.11.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:379) ~[spring-cloud-stream-3.0.11.RELEASE.jar!/:3.0.11.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:268) ~[spring-cloud-stream-3.0.11.RELEASE.jar!/:3.0.11.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:291) ~[spring-cloud-stream-3.0.11.RELEASE.jar!/:3.0.11.RELEASE]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindOutputs(AbstractBindableProxyFactory.java:136) ~[spring-cloud-stream-3.0.11.RELEASE.jar!/:3.0.11.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.doStartWithBindable(OutputBindingLifecycle.java:58) ~[spring-cloud-stream-3.0.11.RELEASE.jar!/:3.0.11.RELEASE]
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57) ~[spring-cloud-stream-3.0.11.RELEASE.jar!/:3.0.11.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:34) ~[spring-cloud-stream-3.0.11.RELEASE.jar!/:3.0.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.13.RELEASE.jar!/:5.2.13.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.9.RELEASE.jar!/:2.3.9.RELEASE]
```

It is observed that the following three combination causes this:
1. ```spring.cloud.stream.binders``` are configured.
2. wild card, *, is used in ``` management.endpoints.web.exposure.include=*```
3. spring cloud sleuth is on the classpath

Removing either one of the three allows the application to start up, in my case we explicitly list the actuator endpoints rather than using "*".

**Sample**
Please see https://github.com/bbdick/kafkaBinderDemo/, run the develop branch to duplicate the issue. 
( I have also added another branch, https://github.com/bbdick/kafkaBinderDemo/tree/demo/nokafkaBinder, that demonstrate when no kafka binder is used then the app starts successfully.)

**Comment by olegz** [comment]
There seem to be an issue with publishing event in `DefaultBinderFactory`. I'll try to investigate it further but the event is not really used by anything so wrapping it in try/catch and logging a warning seems like a good idea for the time being
