### ISSUE TITLE
Random exception on application shutdown (using a RabbitMQ binder)

### ISSUE THREAD

**Issue by gimby** [spring-cloud/spring-cloud-stream#2171]
Java: 11
Spring Boot 2.4.5
Spring Cloud: 2020.0.2 (but also observed with 2020.0.0)

Although the application functions and it can consume messages just fine, upon application _shutdown_ the application randomly produces an exception stemming from the shutdown cycle. A minimalistic reproduction program can be found in github here:

https://github.com/gimby/br_scloudmsg_shutdownerrors

This example program will setup a single consumer for an exchange 'helloWorld', a queue 'helloworld' in group 'helloworld' in RabbitMQ. Since the problem happens on application shutdown, it is not necessary to actually queue any message to reproduce the problem.

What has been noticed is that setting the 'spring.cloud.stream.default.consumer.concurrency' property to say a value of 5 increases the likelihood that an exception occurs on application shutdown. This is set in the example program to make it easier to reproduce the problem.

A local rabbitmq instance with a helloworld virtualhost is required for that application to work, a docker-compose.yml has been provided which sets that up.

The reproduce steps:

- download or fork the code of the above github repository (https://github.com/gimby/br_scloudmsg_shutdownerrors)
- start the dockerized rabbitmq instance using docker-compose up -d
  - alternatively create a virtualhost 'helloword' in an existing local rabbitmq instance; the src/main/resources/application.yml assumes the dockerized rabbitmq will be used when it comes to configured ports
- build and start the application; it doesn't matter if that is from a shell or an IDE
- shut the application down again
- repeat starting it up and shutting it down a couple of times, you should witness varying exceptions and sometimes no exception at all.

So as said the behaviour on shutdown is random. If it does not fail in any way, try starting it up and shutting it down a couple of times, sometimes it takes a few tries before the first failure is tripped.

There are three permutations I have witnessed:

1. No error, shutdown completes without a hiccup
2. OR the following exception is thrown:

```
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'helloworld.helloworld.errors.bridge': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1160) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.destroyErrorInfrastructure(AbstractMessageChannelBinder.java:795) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.access$300(AbstractMessageChannelBinder.java:91) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$2.afterUnbind(AbstractMessageChannelBinder.java:444) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binder.DefaultBinding.unbind(DefaultBinding.java:175) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.BindingService.unbindConsumers(BindingService.java:351) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.unbindInputs(AbstractBindableProxyFactory.java:156) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStopWithBindable(InputBindingLifecycle.java:66) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:68) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:85) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:234) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:373) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:206) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor.stop(DefaultLifecycleProcessor.java:117) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.stop(AbstractApplicationContext.java:1427) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:247) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:373) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:206) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:129) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1067) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:991) ~[spring-context-5.3.6.jar:5.3.6]
```

3. OR the following exception is thrown:

```
	org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'helloworld.helloworld.errors.recoverer' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.removeBeanDefinition(DefaultListableBeanFactory.java:1059) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.context.support.GenericApplicationContext.removeBeanDefinition(GenericApplicationContext.java:335) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.destroyBean(AbstractMessageChannelBinder.java:827) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.destroyErrorInfrastructure(AbstractMessageChannelBinder.java:786) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.access$300(AbstractMessageChannelBinder.java:91) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$2.afterUnbind(AbstractMessageChannelBinder.java:444) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binder.DefaultBinding.unbind(DefaultBinding.java:175) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.BindingService.unbindConsumers(BindingService.java:351) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.unbindInputs(AbstractBindableProxyFactory.java:156) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStopWithBindable(InputBindingLifecycle.java:66) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:68) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:85) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:234) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:373) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:206) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:129) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1067) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:171) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:991) ~[spring-context-5.3.6.jar:5.3.6]
```

Any exception will cause the shutdown to hang until a 30 second timeout forces the application to quit.

**Comment by olegz** [comment]
Given the age for this issue I am going to close it. If you still see the issue please follow a new one with an updated version of the framework
