### ISSUE TITLE
3.1.2 regression: message delivered multiple times + Stackoverflow error when consuming 

### ISSUE THREAD

**Issue by jonenst** [spring-cloud/spring-cloud-stream#2175]
**Describe the issue**
When publishing to a queue and consuming from this queue in the same app, the message is delivered mulitple times. Also a stackOverflowError is visible in the logs. This problem happens with 3.1.2, but with 3.1.1 everything works as expected (message delivered once and no errors).

**To Reproduce**
src/test/java/com/mycompany/app/SampleStreamTest.java
```java
package com.mycompany.app;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Supplier;
import java.util.logging.Level;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.stream.binder.test.TestChannelBinderConfiguration;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.messaging.Message;
import org.springframework.messaging.support.GenericMessage;
import org.springframework.test.context.junit4.SpringRunner;

import reactor.core.publisher.EmitterProcessor;
import reactor.core.publisher.Flux;

@SpringBootTest
@RunWith(SpringRunner.class)
public class SampleStreamTest {

    @SpringBootApplication
    @Import(TestChannelBinderConfiguration.class)
    public static class SampleConfiguration {
        
        List<Message> receivedMessages = new ArrayList<>();
        
        @Bean
        public Consumer<Message<String>> consume() {
            return message -> {
                receivedMessages.add(message);
            };
        }

        private final EmitterProcessor<Message<String>> runMessagePublisher = EmitterProcessor.create();

        @Bean
        public Supplier<Flux<Message<String>>> publish() {
            return () -> runMessagePublisher;
        }

        public void dopublish() {
            runMessagePublisher.onNext(new GenericMessage<String>("hello"));
        }

    }
    
    
    @Test
    public void sampleTest() throws InterruptedException {
        try (ConfigurableApplicationContext context = new SpringApplicationBuilder(
                    TestChannelBinderConfiguration.getCompleteConfiguration(
                            SampleConfiguration.class))
                                .run("--spring.cloud.function.definition=consume;publish",
                                     "--spring.cloud.stream.bindings.consume-in-0.destination=dest",
                                     "--spring.cloud.stream.bindings.publish-out-0.destination=dest"
                            )) {
            SampleConfiguration source = context.getBean(SampleConfiguration.class);
            source.dopublish();
            Thread.sleep(1000);
            assertThat(source.receivedMessages.get(0).getPayload()).isEqualTo("hello");
            assertThat(source.receivedMessages.size()).isEqualTo(1);
        }
    }
}
```

pom.xml for easy setup if you want:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app4</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>my-app4</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <scope>test</scope>
    </dependency>

  <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
  </dependency>

    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-stream</artifactId>
    </dependency>

    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-stream</artifactId>
        <type>test-jar</type>
        <scope>test</scope>
        <classifier>test-binder</classifier>
    </dependency>
  </dependencies>

  <dependencyManagement>
       <dependencies>
          <dependency>
              <!-- Import dependency management from Spring Boot -->
              <groupId>org.springframework.boot</groupId>
              <artifactId>spring-boot-dependencies</artifactId>
              <version>2.4.5</version>
              <type>pom</type>
              <scope>import</scope>
          </dependency>
          <dependency>
              <groupId>org.springframework.cloud</groupId>
              <artifactId>spring-cloud-dependencies</artifactId>
              <version>2020.0.2</version> <!--change this to 2020.0.1 and it works -->
              <type>pom</type>
              <scope>import</scope>
          </dependency>
      </dependencies>
  </dependencyManagement>
</project>
```

**Version of the framework** 3.1.2 (from 2020.0.2)
**Expected behavior**
3.1.2 should behave like 3.1.1

assert:
```
org.opentest4j.AssertionFailedError: 
Expecting:
 <200>
to be equal to:
 <1>
```

Bonus: stackOverflowError in reactor bounded elastic threadpool
```
2021-05-18 13:05:10.644 ERROR 18067 --- [oundedElastic-1] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception

java.lang.StackOverflowError: null
	at java.base/java.lang.reflect.Field.get(Field.java:418) ~[na:na]
	at org.springframework.util.ReflectionUtils.getField(ReflectionUtils.java:654) ~[spring-core-5.3.6.jar:5.3.6]
	at org.springframework.cloud.stream.binding.MessageConverterConfigurer$InboundContentTypeEnhancingInterceptor.doPreSend(MessageConverterConfigurer.java:197) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.cloud.stream.binding.MessageConverterConfigurer$AbstractContentTypeInterceptor.preSend(MessageConverterConfigurer.java:292) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:469) ~[spring-integration-core-5.4.6.jar:5.4.6]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:309) ~[spring-integration-core-5.4.6.jar:5.4.6]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272) ~[spring-integration-core-5.4.6.jar:5.4.6]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.3.6.jar:5.3.6]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.3.6.jar:5.3.6]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	[...snip many many lines]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.3.6.jar:5.3.6]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:450) ~[spring-integration-core-5.4.6.jar:5.4.6]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.doProduceOutput(AbstractMessageProducingHandler.java:324) ~[spring-integration-core-5.4.6.jar:5.4.6]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:267) ~[spring-integration-core-5.4.6.jar:5.4.6]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:231) ~[spring-integration-core-5.4.6.jar:5.4.6]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:140) ~[spring-integration-core-5.4.6.jar:5.4.6]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56) ~[spring-integration-core-5.4.6.jar:5.4.6]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:1041) ~[spring-cloud-stream-3.1.2.jar:3.1.2]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56) ~[spring-integration-core-5.4.6.jar:5.4.6]

**Comment by olegz** [comment]
The EmitterProcessor has been deprecated by the reactor and we no longer advocate using it either in favor of [StreamBridge](https://docs.spring.io/spring-cloud-stream/docs/3.1.3/reference/html/spring-cloud-stream.html#_sending_arbitrary_data_to_an_output_e_g_foreign_event_driven_sources)

Can you please refactor your application and give it a try?

**Comment by jonenst** [comment]
Hi, using StreamBridge does fix the problem, thanks.

**Comment by olegz** [comment]
I am going to close this since the recommended approach appears to be working.
