### ISSUE TITLE
Per-binding error recoverer handler causes application shutdown problems

### ISSUE THREAD

**Issue by fwiersENO** [spring-cloud/spring-cloud-stream#2193]
The issue descibed at 
https://github.com/spring-cloud/spring-cloud-stream/issues/1870
now also exists for "errors.recoverer" type beans as described by Stexxen in comment
https://github.com/spring-cloud/spring-cloud-stream/issues/1870#issuecomment-797113477

I could also reproduce the issue with spring-cloud-stream 3.1.2 on shutdown:

```
2021-07-01 17:05:43.284  WARN [app-name,,] 1793 --- [extShutdownHook] o.s.c.support.DefaultLifecycleProcessor  : Failed to stop bean 'inputBindingLifecycle'

org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'my-topic.my-group.errors.recoverer' available
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.removeBeanDefinition(DefaultListableBeanFactory.java:1059)
        at org.springframework.context.support.GenericApplicationContext.removeBeanDefinition(GenericApplicationContext.java:335)
        at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.destroyBean(AbstractMessageChannelBinder.java:827)
        at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.destroyErrorInfrastructure(AbstractMessageChannelBinder.java:786)
        at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.access$300(AbstractMessageChannelBinder.java:91)
        at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$2.afterUnbind(AbstractMessageChannelBinder.java:444)
        at org.springframework.cloud.stream.binder.DefaultBinding.unbind(DefaultBinding.java:175)
        at org.springframework.cloud.stream.binding.BindingService.unbindConsumers(BindingService.java:351)
        at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.unbindInputs(AbstractBindableProxyFactory.java:156)
        at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStopWithBindable(InputBindingLifecycle.java:66)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:68)
        at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34)
        at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:85)
        at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:234)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:54)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:373)
        at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:206)
        at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:129)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1067)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:171)
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:991)
```
Other dependencies used: spring-boot 2.4.7 and spring-cloud-dependencies 2020.0.2.

The same fix as used to solve 
https://github.com/spring-cloud/spring-cloud-stream/issues/1870
might also fix this issue?

**Comment by fwiersENO** [comment]
I see the same problem is mentioned at https://github.com/spring-cloud/spring-cloud-stream/issues/2171
I will close this issue.
