### ISSUE TITLE
Suggestion: Adding binder/binding information when throwing a BinderException

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream#2203]
**Version of the framework**
spring-cloud-stream:3.1.3
spring-cloud-stream-binder-kafka:3.1.3

When starting an application with Spring Cloud Stream for the Kafka binder and the configuration of a binding is not correct, either because the target topic is not reachable or another reason, the exception and ERROR traces indicate neither the binding name, nor the binder (in case it is a multi-binder scenario) nor exception topic information in case the cause is UnknownTopicOrPartitionException.

We show an example of error trace when configuring a binding against a non-existent topic:

```
2021-07-28 13:40:52,029 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is org.springframework.cloud.stream.binder.BinderException: Cannot initialize binder:
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.inditex.ot.openfwkt.Application.main(Application.java:11)
Caused by: org.springframework.cloud.stream.binder.BinderException: Cannot initialize binder:
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.getPartitionsForTopic(KafkaTopicProvisioner.java:591)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.getPartitionInfo(KafkaMessageChannelBinder.java:1120)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.processTopic(KafkaMessageChannelBinder.java:869)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:625)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:158)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:408)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:91)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143)
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:171)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:134)
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:118)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	... 14 common frames omitted
Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
```

It would be very useful that in the exception, at least the name of the binding that is causing it is indicated.

**Comment by ferblaca** [comment]
On the other hand, regarding the information of the cause of the BinderException(UnknownTopicOrPartitionException), whose message does not show the information of the name of the topic in question that has originated the error when trying to consult its metadata, there is an issue for this in Apache: https://issues.apache.org/jira/browse/KAFKA-13144

**Comment by juliojgd** [comment]
@garyrussell   any thoughts on this? If you think the addition proposed by @ferblaca is valuable we can try to contribute the change to Spring Cloud Stream. 

In our projects a lot of teams access different topics  with different names by environment and is frequent to mistype a character or use one topic name in an environment where it is not valid. If the log showed this the troubleshooting will be instantaneous. Without this that have to increase the log level of Apache Kafka client to debug in every environment they have the problem.

What do you think?

P.D. We are aware that the complete solution would be having this change in SCS but also in the kafka client, but we have to begin with sth. 😄

**Comment by garyrussell** [comment]
@juliojgd A quick look at the code tells me it would be easy to add the topic name; adding the binding name would require more work because it is not currently available in the method that throws the exception.

A contribution would indeed be welcome; thanks.
