### ISSUE TITLE
Spring Cloud function is throwing error "Type must be one of Supplier, Function or Consumer" for non functional beans

### ISSUE THREAD

**Issue by jaiananth** [spring-cloud/spring-cloud-stream#2228]
Issue:
Spring cloud function is not exluding custom java beans  and it is expecting Supplier, Function or Consumer type.

**To Reproduce**
   @Bean
    public Function<Message<?>, Message<?>> transformFunction() {
        return msg -> {
            Message<?> resultMsg = this.transformer.apply(msg);
            return resultMsg;
        };
    }

  @Bean
    public String value() {
        return "beanValue";
    }

Caused by: java.lang.IllegalArgumentException: Type must be one of Supplier, Function or Consumer
	at org.springframework.util.Assert.isTrue(Assert.java:121) ~[spring-core-5.3.10.jar:5.3.10]
	at org.springframework.cloud.function.context.catalog.FunctionTypeUtils.discoverFunctionTypeFromClass(FunctionTypeUtils.java:149) ~[spring-cloud-function-context-3.1.3.jar:3.1.3]
	at org.springframework.cloud.function.context.catalog.FunctionTypeUtils.discoverFunctionType(FunctionTypeUtils.java:267) ~[spring-cloud-function-context-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionBindingRegistrar.filterEligibleFunctionDefinitions(FunctionConfiguration.java:907) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionBindingRegistrar.afterPropertiesSet(FunctionConfiguration.java:796) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.10.jar:5.3.10]
	... 21 common frames omitted

**Version of the framework**
spring-cloud-function-core 3.1.3
spring-cloud-function-context 3.1.3

**Comment by olegz** [comment]
Here is my app and everything works as expected 
```
@SpringBootApplication
public class DemoStreamApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoStreamApplication.class, args);
	}

	@Bean
	public Function<String, String> uppercase() {
		return v -> v.toUpperCase();
	}

	@Bean
	public String value() {
		return "hello";
	}
}
```

Please provide reproducible sample

**Comment by jaiananth** [comment]
Hi olegz,

I did deep validation and found that this issue able to recreate only  if we include header enricher function jar dependency.
In normal case, we aren't able to recreate this issue. Anything need to fix in header enricher function jar?

Please add this dependency and see able to recreate the issue.

   <dependency>
            <groupId>org.springframework.cloud.fn</groupId>
            <artifactId>header-enricher-function</artifactId>
            <version>1.0.3</version>
        </dependency>

**Comment by jaiananth** [comment]
`   <dependency>
            <groupId>org.springframework.cloud.fn</groupId>
            <artifactId>header-enricher-function</artifactId>
            <version>1.0.3</version>
        </dependency>`

**Comment by sobychacko** [comment]
@jaiananth Could you provide a small [reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) to triage this issue? With the maven config, minimal code/config to reproduce, etc.

**Comment by bono007** [comment]
Hi @jaiananth ,

I attempted to reproduce it using the provided app, but very similar as pointed out [here on #2230](https://github.com/spring-cloud/spring-cloud-stream/issues/2230#issuecomment-939398275) - this still does not repro the issue (for me anyways).
