### ISSUE TITLE
Spring Cloud function is throwing error "Type must be one of Supplier, Function or Consumer" for non functional beans

### ISSUE THREAD

**Issue by jaiananth** [spring-cloud/spring-cloud-stream#2232]
Issue:
Spring cloud function is not exluding custom java beans and it is expecting Supplier, Function or Consumer type.
related to https://github.com/spring-cloud/spring-cloud-stream/issues/2228

To Reproduce

Please find the attached sample project to recreate. 

[functiontype.zip](https://github.com/spring-cloud/spring-cloud-stream/files/7296161/functiontype.zip)

@bean
public Function<Message, Message> transformFunction() {
return msg -> {
Message<?> resultMsg = this.transformer.apply(msg);
return resultMsg;
};
}

@bean
public String value() {
return "beanValue";
}

Caused by: java.lang.IllegalArgumentException: Type must be one of Supplier, Function or Consumer
at org.springframework.util.Assert.isTrue(Assert.java:121) ~[spring-core-5.3.10.jar:5.3.10]
at org.springframework.cloud.function.context.catalog.FunctionTypeUtils.discoverFunctionTypeFromClass(FunctionTypeUtils.java:149) ~[spring-cloud-function-context-3.1.3.jar:3.1.3]
at org.springframework.cloud.function.context.catalog.FunctionTypeUtils.discoverFunctionType(FunctionTypeUtils.java:267) ~[spring-cloud-function-context-3.1.3.jar:3.1.3]
at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionBindingRegistrar.filterEligibleFunctionDefinitions(FunctionConfiguration.java:907) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionBindingRegistrar.afterPropertiesSet(FunctionConfiguration.java:796) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.10.jar:5.3.10]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.10.jar:5.3.10]
... 21 common frames omitted

Version of the framework
spring-cloud-function-core 3.1.3
spring-cloud-function-context 3.1.3

**Comment by olegz** [comment]
Any updates on this?
