### ISSUE TITLE
rocketmqException:The producer group[calcCallbackGroup] has been created before, specify another name please.

### ISSUE THREAD

**Issue by wuxingyun** [spring-cloud/spring-cloud-stream#2252]
Caused by: org.apache.rocketmq.client.exception.MQClientException: The producer group[calcCallbackGroup] has been created before, specify another name please.
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.start(DefaultMQProducerImpl.java:203)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.start(DefaultMQProducerImpl.java:183)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.start(DefaultMQProducer.java:277)
	at org.apache.rocketmq.spring.core.RocketMQTemplate.afterPropertiesSet(RocketMQTemplate.java:454)
	at com.alibaba.cloud.stream.binder.rocketmq.integration.RocketMQMessageHandler.start(RocketMQMessageHandler.java:106)
	... 12 common frames omitted

**Comment by olegz** [comment]
I don't see anything here related to spring-cloud-stream other then `com.alibaba.cloud.stream.binder.rocketmq.integration.RocketMQMessageHandler` which is not maintained by Spring team.
Please refer this issue to the maintainer of the code
