### ISSUE TITLE
Calling the actuator bindings endpoint causes infinite recursion

### ISSUE THREAD

**Issue by dbruegger** [spring-cloud/spring-cloud-stream#2253]
**Description**

With Spring Cloud Stream 3.2.1 calling the `/actuator/bindings` endpoint causes an infinite recursion (StackOverflowError):

```
java.lang.IllegalArgumentException: Infinite recursion (StackOverflowError) (through reference chain: org.springframework.core.convert.support.GenericConversionService$ConvertersForPair["converters"]->java.util.concurrent.ConcurrentLinkedDeque[0]->org.springframework.core.convert.support.ObjectToCollectionConverter["conversionService"]->org.springframework.core.convert.support.DefaultConversionService["converters"]->...)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4394) ~[jackson-databind-2.13.0.jar:2.13.0]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler org.springframework.boot.actuate.endpoint.web.reactive.AbstractWebFluxEndpointHandlerMapping$ReadOperationHandler#handle(ServerWebExchange) [DispatcherHandler]
	*__checkpoint ⇢ org.springframework.cloud.sleuth.instrument.web.TraceWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/actuator/bindings" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4394) ~[jackson-databind-2.13.0.jar:2.13.0]
		at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4325) ~[jackson-databind-2.13.0.jar:2.13.0]
		at org.springframework.cloud.stream.binding.BindingsLifecycleController.queryStates(BindingsLifecycleController.java:124) ~[spring-cloud-stream-3.2.1.jar:3.2.1]
		at org.springframework.cloud.stream.endpoint.BindingsEndpoint.queryStates(BindingsEndpoint.java:52) ~[spring-cloud-stream-3.2.1.jar:3.2.1]
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
		at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
		at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282) ~[spring-core-5.3.13.jar:5.3.13]
		at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:74) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
		at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
		at org.springframework.boot.actuate.endpoint.web.reactive.AbstractWebFluxEndpointHandlerMapping$ElasticSchedulerInvoker.lambda$invoke$0(AbstractWebFluxEndpointHandlerMapping.java:239) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
		at reactor.core.publisher.MonoCallable.call(MonoCallable.java:92) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:227) ~[reactor-core-3.4.12.jar:3.4.12]
		at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.lambda$null$6(ReactorSleuth.java:324) ~[spring-cloud-sleuth-instrumentation-3.1.0.jar:3.1.0]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.12.jar:3.4.12]
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
		at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) ...
```

**Version of the framework**

- Spring Boot 2.6.1
- Spring Cloud 2021.0.0
- Spring Cloud Stream 3.2.1
- Spring Cloud Stream Binder for Solace PubSub+ 3.2.0

**Comment by marcingrzejszczak** [comment]
If you disable Sleuth - does the problem persist? Can you create a small maven java sample that replicates the problem?

**Comment by dbruegger** [comment]
Disabling Sleuth or removing the Sleuth dependency does not help. I can create a small sample next week.

**Comment by olegz** [comment]
Yeah, please reproducible sample would help as I can not reproduce it locally. 
The part of the stack trace that looks strange is 
```
java.lang.IllegalArgumentException: Infinite recursion (StackOverflowError) (through reference chain: org.springframework.core.convert.support.GenericConversionService$ConvertersForPair["converters"]->java.util.concurrent.ConcurrentLinkedDeque[0]->org.springframework.core.convert.support.ObjectToCollectionConverter["conversionService"]->org.springframework.core.convert.support.DefaultConversionService["converters"]->...)
```
I can see the recursion, but it appears to be related to the setup of the `ConversionService` which we don't modify

We simply get `ObjectMapper` instance from Spring's ApplicationContext and 
```
return this.objectMapper.convertValue(bindings, List.class);
```
That is the line that causes the exception, so something is up with configuration of ObjectMapper in your environment.

**Comment by dbruegger** [comment]
I created a sample project: https://github.com/dbruegger/spring-cloud-stream-actuator-bug

You can run the `ActuatorBindingsTest` to reproduce the infinite recursion.

While creating the sample project I observed that the infinite recursion only occurs when the following configuration property is enabled:

```
spring.jackson.visibility.field=ANY
```

This is quite a common setting in my opinion.

The infinite recursion does not occur with Spring Cloud Streams Version 3.1.3.

**Comment by olegz** [comment]
@dbruegger thank you. Will look at it shortly

**Comment by olegz** [comment]
I am not sure how I would fix it as it has nothing to do with stream or our configuration. But let me explain what has changed between 3.1.3 and latest release. 
Basically the only difference is that we are now using Spring managed `ObjectMapper` based on https://github.com/spring-cloud/spring-cloud-stream/issues/2215. Before, we were creating a new instance of it (e.g., `new ObjectMapper()`). This is why it created an appearance that it was working regardless of `spring.jackson.visibility.field=ANY`, but in reality this property had absolutely no effect on the `ObjectMapper` since it only applies on the one managed by Spring. 

The only thing I can propose is to go back to a separate/isolated instance of `ObjectMapper`

Let me know.

**Comment by olegz** [comment]
Thinking about it some more, I am now inclined bringing isolated ObjectMapper back, given that user has no control over objects (internal list of s-c-stream Binding objects ) that are being serialized

**Comment by dbruegger** [comment]
Thanks for fixing the problem!
