### ISSUE TITLE
Not sending to DLQ. Instead throws  "messageListenerContainer$ListenerConsumer Consumer exception"

### ISSUE THREAD

**Issue by sidsamant** [spring-cloud/spring-cloud-stream#2256]
**Describe the issue**

I am testing handling of deserialization errors from input and forwarding them to DLQ.
 
Here is my configuration for Spring Cloud Stream
 ```
spring:
  cloud:
    schemaRegistryClient:
      endpoint: http://localhost:8081
    stream:
      default-binder: kafka
      function:
        definition: myFunction
      bindings:
        myFunction-in-0:
          destination: domain.input-event
          content-type: application/*+avro
          group: myService
          consumer:
            auto-bind-dlq: true
            concurrency: 5
            max-attempts: 3
            use-native-decoding: true
        myFunction-out-0:
          destination: domain.output-event
          content-type: application/*+avro
          producer:
            use-native-encoding: true
        myFunction-audit:
          destination: domain.audit-event
          content-type: application/*+avro
          producer:
            use-native-encoding: true
        myFunction-dlq:
          destination: domain.myFunction-dlq
          content-type: application/*+avro
          producer:
            use-native-encoding: true
      kafka:
        bindings:
          myFunction-in-0:
            consumer:
              auto-bind-dlq: true
              autoCommitOnError: true
              autoCommitOffset: true
              enable-dlq: true
              dlq-name: domain.myFunction-dlq
              dlq-producer-properties.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer
              dlq-producer-properties.configuration.value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
              ackMode: RECORD
              configuration:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                schema.registry.url: http://localhost:8081
                specific.avro.reader: true
                max.poll.records: 1000
                fetch.max.wait.ms: 500
                fetch.min.bytes: 40960
        binder:
          brokers: "localhost:9092"
          schema.registry.url: http://localhost:8081
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081
            errorChannelEnabled: true
```

My Spring cloud function 

```
@Configuration
public class StreamsConfig {

	@Bean
	public Function<MyServiceRegistrationEvent,MyServiceRegistrationEvent> myFunction(
			MessageProcessor messageProcessor) {
		return message -> {			
			// If registration data is good, just forward it.
			try {
                               // Check for business errors
				if(messageProcessor.process(message)) {
					return message;
				}
			} catch (Exception e) {
				throw new RuntimeException(e);
			}

                        // if the registration has business side errors, do not forward to output
			return null;
		};

	}
}

```
I keep getting these errors infinitely and no messages are sent to the dlq.
```
2021-12-15 20:33:52.334 ERROR 15108 container  messageListenerContainer$ListenerConsumer Consumer exception

java.lang.IllegalStateException: This error handler cannot process 'SerializationException's directly; please consider configuring an 'ErrorHandlingDeserializer' in the value and/or key deserializer
	at org.springframework.kafka.listener.SeekUtils.seekOrRecover(SeekUtils.java:194) ~[spring-kafka-2.7.7.jar:2.7.7]
	at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:112) ~[spring-kafka-2.7.7.jar:2.7.7]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.handleConsumerException(KafkaMessageListenerContainer.java:1604) ~[spring-kafka-2.7.7.jar:2.7.7]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1212) ~[spring-kafka-2.7.7.jar:2.7.7]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition domain.input-event-1 at offset 6. If needed, please seek past the record to continue consumption.
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 18
Caused by: org.apache.avro.AvroTypeException: Found com.myService.event.schema.MyServiceRegistrationEvent, expecting com.myService.event.schema.MyServiceRegistrationEvent, missing required field failure
	at org.apache.avro.io.ResolvingDecoder.doAction(ResolvingDecoder.java:308) ~[avro-1.10.2.jar:1.10.2]
	at org.apache.avro.io.parsing.Parser.advance(Parser.java:86) ~[avro-1.10.2.jar:1.10.2]
	at org.apache.avro.io.ResolvingDecoder.readFieldOrder(ResolvingDecoder.java:127) ~[avro-1.10.2.jar:1.10.2]
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:239) ~[avro-1.10.2.jar:1.10.2]
	at org.apache.avro.specific.SpecificDatumReader.readRecord(SpecificDatumReader.java:123) ~[avro-1.10.2.jar:1.10.2]
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:179) ~[avro-1.10.2.jar:1.10.2]
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160) ~[avro-1.10.2.jar:1.10.2]
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153) ~[avro-1.10.2.jar:1.10.2]
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:125) ~[kafka-avro-serializer-5.3.0.jar:na]
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:79) ~[kafka-avro-serializer-5.3.0.jar:na]
	at io.confluent.kafka.serializers.KafkaAvroDeserializer.deserialize(KafkaAvroDeserializer.java:55) ~[kafka-avro-serializer-5.3.0.jar:na]
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60) ~[kafka-clients-2.8.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1386) ~[kafka-clients-2.8.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:133) ~[kafka-clients-2.8.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1617) ~[kafka-clients-2.8.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1700(Fetcher.java:1453) ~[kafka-clients-2.8.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:686) ~[kafka-clients-2.8.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:637) ~[kafka-clients-2.8.1.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1276) ~[kafka-clients-2.8.1.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1237) ~[kafka-clients-2.8.1.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1210) ~[kafka-clients-2.8.1.jar:na]
	at jdk.internal.reflect.GeneratedMethodAccessor173.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.10.jar:5.3.10]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-5.3.10.jar:5.3.10]
	at com.sun.proxy.$Proxy159.poll(Unknown Source) ~[na:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doPoll(KafkaMessageListenerContainer.java:1414) ~[spring-kafka-2.7.7.jar:2.7.7]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1251) ~[spring-kafka-2.7.7.jar:2.7.7]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1163) ~[spring-kafka-2.7.7.jar:2.7.7]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Version of the framework**
Spring-cloud-stream 3.1.5 and Spring-cloud-stream-binder-kafka 3.1.5
**Expected behavior**
It should send the bad input message to DLQ and continue to next message.

**Additional context**
The actual names of topics and other objects have been replaced with dummy names.

**Comment by olegz** [comment]
The stack trace you're showing contains no references to spring-cloud-stream nor does the error. Consider creating a small project with bare minimum just enough to reproduce the issue, post it to github and raise an issue in spring-kafka

**Comment by sidsamant** [comment]
Spring-cloud-stream-binder-kafka 3.1.5 has been used along with Spring Cloud Stream. There is no explicit use of Spring Kafka.

The application processes well formatted messages and forwards to output stream.
The error shows up when a badly formatted message is input. This should been handled as per [https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.1.5/reference/html/spring-cloud-stream-binder-kafka.html#kafka-error-channels](url)

Should I still be raising issue with spring-kafka?

**Comment by olegz** [comment]
You may be right, but I don't see it from the stack trace. So if you can provide a small project that reproduces it we can certainly take a look, otherwise I have nothing to go by
