### ISSUE TITLE
Problem with spring-cloud-stream-test-support version 3.2.2

### ISSUE THREAD

**Issue by ivan-letenko** [spring-cloud/spring-cloud-stream#2346]
Hi! 

After updating spring-cloud-stream and spring-cloud-stream-test-support from version 2.1.4.RELEASE to version 3.2.2
Tests started to fail due to 
org.springframework.cloud.stream.binding.BindingsLifecycleController#queryStates throws an exception for TestSupportBinder$TestBinding 

Reason: org.springframework.cloud.stream.test.binder.TestSupportBinder.TestBinding does not implement the org.springframework.cloud.stream.binder.Binding#isInput method, but it's called by objectMapper in the org.springframework.cloud.stream.binding.BindingsLifecycleController#queryStates method.

Stack trace: 
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Binding implementation `org.springframework.cloud.stream.test.binder.TestSupportBinder$TestBinding` must implement this operation before it is called (through reference chain: java.util.ArrayList[0]->org.springframework.cloud.stream.test.binder.TestSupportBinder$TestBinding["input"])
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
    at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:782)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
    at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
    at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
    at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
    at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4371)
    ... 34 common frames omitted
Caused by: java.lang.UnsupportedOperationException: Binding implementation `org.springframework.cloud.stream.test.binder.TestSupportBinder$TestBinding` must implement this operation before it is called
    at org.springframework.cloud.stream.binder.Binding.isInput(Binding.java:130)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
    ... 41 common frames omitted

Could someone please check and suggest the fix?

**Comment by olegz** [comment]
I am closing it as it appears to be resolved
