### ISSUE TITLE
Kafka tombstone throws exception in a functional batch consumer

### ISSUE THREAD

**Issue by giovannitomasicchio** [spring-cloud/spring-cloud-stream#2355]
I have a functional batch consumer (`Consumer<Message<List<MyEntity>>>`) that throws the following exception when it receives a tombstone message:

> No serializer found for class org.springframework.kafka.support.KafkaNull and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)

If I disable the batch mode in application.properties and change the consumer accordingly (`Consumer<Message<MyEntity>>`) the tombstone message is handled properly with a KafkaNull payload.

**Comment by giovannitomasicchio** [comment]
application.properties

```
spring.cloud.function.definition=recordConsumer;batchConsumer

spring.cloud.stream.bindings.recordConsumer-in-0.destination=test
spring.cloud.stream.bindings.recordConsumer-in-0.group=recordConsumer

spring.cloud.stream.bindings.batchConsumer-in-0.destination=test
spring.cloud.stream.bindings.batchConsumer-in-0.group=batchConsumer
spring.cloud.stream.bindings.batchConsumer-in-0.consumer.batch-mode=true
```

SampleApplication.java

```
@SpringBootApplication
public class SampleApplication {

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }

    @Bean
    public ApplicationRunner runner(KafkaTemplate<byte[], byte[]> template, StreamBridge streamBridge) {
        return args -> {
            streamBridge.send("test", new MyClass(1, 10));
            streamBridge.send("test", new MyClass(2, 20));
            streamBridge.send("test", KafkaNull.INSTANCE);
        };
    }

    @Bean
    Consumer<Message<List<MyClass>>> batchConsumer() {
        return message -> message.getPayload().forEach(s -> System.out.println("Batch - " + s));
    }

    @Bean
    Consumer<Message<MyClass>> recordConsumer() {
        return s -> System.out.println("Record - " + s);
    }
}
```

MyClass.java

```
public record MyClass(int min, int max) {
}
```
Console:

```
2022-05-14 19:14:44.036 ERROR 17644 --- [container-0-C-1] plicationJsonMessageMarshallingConverter : Failed to convert payload org.springframework.kafka.support.KafkaNull@24dcf45

java.lang.IllegalArgumentException: No serializer found for class org.springframework.kafka.support.KafkaNull and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4344) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at org.springframework.cloud.stream.converter.ApplicationJsonMessageMarshallingConverter.lambda$convertParameterizedType$0(ApplicationJsonMessageMarshallingConverter.java:154) ~[spring-cloud-stream-3.2.3.jar:3.2.3]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at org.springframework.cloud.stream.converter.ApplicationJsonMessageMarshallingConverter.convertParameterizedType(ApplicationJsonMessageMarshallingConverter.java:161) ~[spring-cloud-stream-3.2.3.jar:3.2.3]
	at org.springframework.cloud.stream.converter.ApplicationJsonMessageMarshallingConverter.convertFromInternal(ApplicationJsonMessageMarshallingConverter.java:104) ~[spring-cloud-stream-3.2.3.jar:3.2.3]
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:185) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.cloud.function.context.config.SmartCompositeMessageConverter.fromMessage(SmartCompositeMessageConverter.java:67) ~[spring-cloud-function-context-3.2.4.jar:3.2.4]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertInputMessageIfNecessary(SimpleFunctionRegistry.java:1287) ~[spring-cloud-function-context-3.2.4.jar:3.2.4]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertInputIfNecessary(SimpleFunctionRegistry.java:1057) ~[spring-cloud-function-context-3.2.4.jar:3.2.4]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:696) ~[spring-cloud-function-context-3.2.4.jar:3.2.4]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:551) ~[spring-cloud-function-context-3.2.4.jar:3.2.4]
	at org.springframework.cloud.stream.function.PartitionAwareFunctionWrapper.apply(PartitionAwareFunctionWrapper.java:84) ~[spring-cloud-stream-3.2.3.jar:3.2.3]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:790) ~[spring-cloud-stream-3.2.3.jar:3.2.3]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:622) ~[spring-cloud-stream-3.2.3.jar:3.2.3]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:216) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:397) ~[spring-integration-kafka-5.5.11.jar:5.5.11]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:83) ~[spring-integration-kafka-5.5.11.jar:5.5.11]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationBatchMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:550) ~[spring-integration-kafka-5.5.11.jar:5.5.11]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationBatchMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:518) ~[spring-integration-kafka-5.5.11.jar:5.5.11]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchOnMessage(KafkaMessageListenerContainer.java:2270) ~[spring-kafka-2.8.5.jar:2.8.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessageWithRecordsOrList(KafkaMessageListenerContainer.java:2260) ~[spring-kafka-2.8.5.jar:2.8.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessage(KafkaMessageListenerContainer.java:2206) ~[spring-kafka-2.8.5.jar:2.8.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchListener(KafkaMessageListenerContainer.java:2116) ~[spring-kafka-2.8.5.jar:2.8.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchListener(KafkaMessageListenerContainer.java:1999) ~[spring-kafka-2.8.5.jar:2.8.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1978) ~[spring-kafka-2.8.5.jar:2.8.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1365) ~[spring-kafka-2.8.5.jar:2.8.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1356) ~[spring-kafka-2.8.5.jar:2.8.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1251) ~[spring-kafka-2.8.5.jar:2.8.5]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.springframework.kafka.support.KafkaNull and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:46) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:29) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4371) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	... 49 common frames omitted

Record - GenericMessage [payload=MyClass[min=1, max=10], headers={deliveryAttempt=1, kafka_timestampType=CREATE_TIME, kafka_receivedTopic=test, kafka_offset=2, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@3bfb0317, source-type=kafka, id=3d6c9b4f-0784-364a-b316-92af1ecbe2d7, kafka_receivedPartitionId=0, contentType=application/json, kafka_receivedTimestamp=1652548483674, kafka_groupId=recordConsumer, timestamp=1652548484036}]
Batch - MyClass[min=1, max=10]
Batch - MyClass[min=2, max=20]
Batch - null
Record - GenericMessage [payload=MyClass[min=2, max=20], headers={deliveryAttempt=1, kafka_timestampType=CREATE_TIME, kafka_receivedTopic=test, kafka_offset=3, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@3bfb0317, source-type=kafka, id=b411866f-1a10-90d1-b36f-699bd277d57c, kafka_receivedPartitionId=0, contentType=application/json, kafka_receivedTimestamp=1652548483689, kafka_groupId=recordConsumer, timestamp=1652548494382}]
Record - GenericMessage [payload=org.springframework.kafka.support.KafkaNull@24dcf45, headers={deliveryAttempt=1, kafka_timestampType=CREATE_TIME, kafka_receivedTopic=test, kafka_offset=4, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@3bfb0317, source-type=kafka, id=211715a5-bfc0-3a81-9105-7e335c9e762b, kafka_receivedPartitionId=0, contentType=application/json, kafka_receivedTimestamp=1652548483689, kafka_groupId=recordConsumer, timestamp=1652548524058}]

```
