### ISSUE TITLE
Kinesis Stream Error Handler

### ISSUE THREAD

**Issue by maroneal1** [spring-cloud/spring-cloud-stream#2409]
**Describe the issue**
spring-cloud-stream-binder-kinesis version 2.0.2.RELEASE does is continuing to read off the stream, when a previous record thew an error during the process function.

I see that there are error channels that are configurable, but I am not interested in using a dlq while processing messages from kinesis. I want to not checkpoint if an error was thrown. 

I am trying to use periodic checkpointing, but have checked this behavior with record as well and it is still checkpointing. 

```
spring.cloud.stream.kinesis:
  binder:
    auto-create-stream: false
    kpl-kcl-enabled: true #enables Spring to bring in KCL

  bindings:
    processEvents-in-0:
      consumer:
        maxAttempts: 10000000
        dynamoDbStreams: true
        maxRecords: 1000
        idleBetweenPolls: 500
        checkpointInterval: 10000 # ms
        listenerMode: batch
        checkpointMode: record #periodic
        shardIteratorType: TRIM_HORIZON

``` 

```
022-05-26T21:27:07,836+0000 ERROR [tr=,sp=,co=,cl=,tid=] KclMessageDrivenChannelAdapter 261 - Got an exception during sending a 'GenericMessage [payload=[[B@55c607fb], headers={aws_shard=shardId-00000001653180986878-0d405e24, id=3586cd8f-91b9-c28a-07cd-e432d52c2f22, contentType=application/json, aws_receivedPartitionKey=[null], aws_receivedStream=arn:aws:dynamodb:ddblocal:000000000000:table/outbox/stream/2022-05-20T03:08:11.147, aws_receivedSequenceNumber=[000000000000000004177], timestamp=1653600427804}]'
for the '[{SequenceNumber: 000000000000000004177,ApproximateArrivalTimestamp: Sat May 21 20:30:00 PDT 2022,Data: java.nio.HeapByteBuffer[pos=0 lim=369 cap=369],}]'.
Consider to use 'errorChannel' flow for the compensation logic. org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@544817bf]; nested exception is java.lang.RuntimeException: shoot,	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192),	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65),	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115),	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133),	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106),	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72),	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317),	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272),	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187),	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166),	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47),	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109),	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208),	at org.springframework.integration.aws.inbound.kinesis.KclMessageDrivenChannelAdapter.access$1600(KclMessageDrivenChannelAdapter.java:84),	at org.springframework.integration.aws.inbound.kinesis.KclMessageDrivenChannelAdapter$RecordProcessor.performSend(KclMessageDrivenChannelAdapter.java:520),	at org.springframework.integration.aws.inbound.kinesis.KclMessageDrivenChannelAdapter$RecordProcessor.processMultipleRecords(KclMessageDrivenChannelAdapter.java:467),	at org.springframework.integration.aws.inbound.kinesis.KclMessageDrivenChannelAdapter$RecordProcessor.processRecords(KclMessageDrivenChannelAdapter.java:424),	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.V1ToV2RecordProcessorAdapter.processRecords(V1ToV2RecordProcessorAdapter.java:42),	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.callProcessRecords(ProcessTask.java:221),	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:176),	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49),	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24),	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264),	at java.base/java.lang.Thread.run(Thread.java:834),Caused by: java.lang.RuntimeException: shoot,	at com.intuit.ceres.data.capture.stream.dynamo.stream.service.DynamoStreamService.processRecord(DynamoStream.kt:37),	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeConsumer(SimpleFunctionRegistry.java:975),	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:704),	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:550),	at org.springframework.cloud.stream.function.PartitionAwareFunctionWrapper.apply(PartitionAwareFunctionWrapper.java:84),	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:749),	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:581),	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56),	... 22 common frames omitted, 
```

```
rg.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@544817bf]; nested exception is java.lang.RuntimeException: shoot
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
	at org.springframework.integration.aws.inbound.kinesis.KclMessageDrivenChannelAdapter.access$1600(KclMessageDrivenChannelAdapter.java:84)
	at org.springframework.integration.aws.inbound.kinesis.KclMessageDrivenChannelAdapter$RecordProcessor.performSend(KclMessageDrivenChannelAdapter.java:520)
	at org.springframework.integration.aws.inbound.kinesis.KclMessageDrivenChannelAdapter$RecordProcessor.processMultipleRecords(KclMessageDrivenChannelAdapter.java:467)
	at org.springframework.integration.aws.inbound.kinesis.KclMessageDrivenChannelAdapter$RecordProcessor.processRecords(KclMessageDrivenChannelAdapter.java:424)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.V1ToV2RecordProcessorAdapter.processRecords(V1ToV2RecordProcessorAdapter.java:42)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.callProcessRecords(ProcessTask.java:221)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:176)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: shoot
	at com.intuit.ceres.data.capture.stream.dynamo.stream.service.DynamoStreamService.processRecord(DynamoStream.kt:37)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeConsumer(SimpleFunctionRegistry.java:975)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:704)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:550)
	at org.springframework.cloud.stream.function.PartitionAwareFunctionWrapper.apply(PartitionAwareFunctionWrapper.java:84)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:749)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:581)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	... 22 common frames omitted
2022-05-26T21:27:07,836+0000 INFO  [tr=,sp=,co=,cl=,tid=] KclMessageDrivenChannelAdapter 292 - Checkpointing shard shardId-00000001653180986878-0d405e24  
```

The above shows the error , and shortly after the KclMessageDrivenChannelAdapter checkpoints the shard.

**Comment by artembilan** [comment]
You probably are missing the fact that there is no correlation between record and its offset in the shard.
Even if we don't checkpoint the current one with error, the next one without is going to checkpoint its offset which is going to cover the previous one as well.

Let's consider we have records with offsets `1, 2, 3`!
We fail on the first one and don't checkpoint, then we fail again on the next one and again don't checkpoint. That's what you are asking though: there is no such a behavior.
Then we are OK with the third record and we checkpoint. But since `3` is the higher one, the rest are covered as well. So, when we restart our application the new consumer is going to start from the `offset = 3 + 1`.
As long as we don't care about record from `1` and `2` offsets, they are lost.

So, what is your idea how else the framework should take care about those failed records since their offset is going to be check-pointed eventually anyway?

**Comment by maroneal1** [comment]
Like wise if 2 failed I would expect the first record and its corresponding sequence # to update the largestPermittedCheckpointValue and not the second.

**Comment by artembilan** [comment]
Thank you for sharing your thoughts!

Do you see how that can be possible with existing KCL algorithm?
I mean it is probably just not possible from the Kinesis Binder perspective if the target library does not support the requested feature.

Thanks for understanding

**Comment by artembilan** [comment]
Sorry, still not clear what you mean.
That `autoCommitOnError` is not relevant to this subject. See its JavaDocs:
```
	/**
	 * Flag to enable auto commit on error in polled consumers.
	 */
	private Boolean autoCommitOnError;
```
`Polled consumers`. Nut we deal here with event-driven.
Similar property was removed from Spring for Apache Kafka in favor of resetting offset via seeking on errors: https://docs.spring.io/spring-kafka/docs/current/reference/html/#default-eh.

We do have `resetCheckpoint...` operations on the `KinesisMessageDrivenChannelAdapter` which can be performed externally and the current consumer is reset to start over from the provided sequence.
We also have there a way to react for `manual` not committed checkpoint to rewind the `shardIterator` for the next poll call:
```
// If using manual checkpointer, we have to make sure we are allowed to use the next shard iterator
// Because if the manual checkpointer was not set to the latest record, it means there are records to be reprocessed
// and if we use the nextShardIterator, we will be skipping records that need to be reprocessed
```
https://github.com/spring-projects/spring-integration-aws/blob/v2.5.1/src/main/java/org/springframework/integration/aws/inbound/kinesis/KinesisMessageDrivenChannelAdapter.java#L1077.

Doesn't look like there is the way somehow have an effect on the  `shardIterator` from the KCL API...

Any more details from you to determine how to proceed with your request?

**Comment by saharathkleips** [comment]
@artembilan, perhaps we are approaching the issue we're having incorrectly and maybe you could chime in for a recommendation for @maroneal1 and I. We're investigating whether or not SCSt can already or should support (with guidance for contributions) the behavior we're looking for, for an integration with consuming from Kinesis Streams and publishing to Kafka.

We need to support **at least once** and **in order** processing of messages coming in from Kinesis Streams to then be published to Kafka. We have managed to cover the failure modes for other integrations (Kafka -> Kafka, by not acknowledging the message was consumed until it has been re-published) but aren't fully comfortable (or well versed) with Kinesis -> Kafka.

---

Is the suggestion you provided in your response to reset the checkpoint after encountering an error? What if the application fails (crashes) before resetting the checkpoint? Or is the suggestion that we should do manual checkpointing and implement any sort of batch / periodic checkpointing behavior ourselves?

**Comment by saharathkleips** [comment]
Thanks for the quick responses, I think this has cleared a lot up for us 👍🏽 Feel free to close out this issue
