### ISSUE TITLE
NPE when getting stream bridge function

### ISSUE THREAD

**Issue by declan782** [spring-cloud/spring-cloud-stream#2501]
**Describe the bug**
My app has several instances (running with same code and config), but only one of them getting NPE,

Exception stack:
java.lang.NullPointerException
	at org.springframework.cloud.stream.function.StreamBridge.getStreamBridgeFunction(StreamBridge.java:246)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:215)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:170)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:150)

spring-cloud-function version we're using:
spring-cloud-function-context: 3.2.6
spring-cloud-function-core: 3.2.5
spring-cloud-stream: 3.2.4
spring-boot: 2.7.0

**Sample**
N/A

**Comment by liuxuzxx** [comment]
I am use SpringBoot, then we listener ApplicationReadyEvent load data from db use StreamBridge send to RocketMQ
