### ISSUE TITLE
Binding fails when destination contains comma-separated value

### ISSUE THREAD

**Issue by groat-mike** [spring-cloud/spring-cloud-stream#2595]
**Describe the issue**
When using spring-cloud 2022.0.0 / spring-cloud-stream 4.0.0, a binding will fail to start whenever its destination is a comma separated list of destinations; only the first topic in the list will be bound to.
Downgrading to spring-cloud 2021.0.5 / spring-cloud-stream 3.2.6 allows this configuration to start as expected with no errors.

**To Reproduce**
I can create a repo for this if needed, but just run this class using spring-boot 3.0.0 / spring-cloud 2022.0.0 & the spring-cloud-stream-binder-kafka:
```java
@SpringBootApplication
public class StreamApp {

    @Bean
    Consumer<Message<?>> logSink() { return System.out::println; }

    public static void main(String[] args) {
        SpringApplication.run(StreamApp.class, 
                "--spring.cloud.stream.bindings.logSink-in-0.destination=cats,dogs");
    }
}
```
```
ERROR [main] o.s.cloud.stream.binding.BindingService  : Failed to create consumer binding; retrying in 30 seconds

org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:528) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:103) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:144) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:184) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:137) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:98) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-6.0.2.jar:6.0.2]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:932) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:587) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.0.jar:3.0.0]
	at com.mikegroatsoft.StreamApp.main(StreamApp.java:19) ~[classes/:na]
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'kafka-1935994577.logSink-in-0.errors' defined in null: Cannot register bean definition [Generic bean: class [org.springframework.messaging.SubscribableChannel]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null] for bean 'kafka-1935994577.logSink-in-0.errors' since there is already [Generic bean: class [org.springframework.messaging.SubscribableChannel]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:1003) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.context.support.GenericApplicationContext.registerBeanDefinition(GenericApplicationContext.java:366) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.BeanDefinitionReaderUtils.registerBeanDefinition(BeanDefinitionReaderUtils.java:164) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.doRegisterBean(AnnotatedBeanDefinitionReader.java:285) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:233) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.registerBean(AnnotationConfigApplicationContext.java:198) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:773) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:705) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:716) ~[spring-cloud-stream-binder-kafka-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:159) ~[spring-cloud-stream-binder-kafka-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:474) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	... 22 common frames omitted
```

**Version of the framework**
- spring-boot 3.0.0
- spring-cloud 2022.0.2
- spring-cloud-stream 4.0.0
- spring-cloud-stream-binder-kafka 4.0.0

**Comment by Mexko** [comment]
I got the same error. But I don't think the comma is the problem. https://github.com/spring-cloud/spring-cloud-stream/issues/2599

**Comment by Mexko** [comment]
Have you find a workaround?

**Comment by sbernardo** [comment]
Hi @Mexko . I have a present for you, Merry Christmas :D . Waiting for a correct solution, you can use this property: `spring.main.allow-bean-definition-overriding=true`.

NOTE: this is a dangerous workaround

**Comment by olegz** [comment]
This has been addressed with https://github.com/spring-cloud/spring-cloud-stream/issues/2599
