### ISSUE TITLE
 "xxxx context has not been refreshed yet" on DefaultBinderFactory#propagateSharedBeans ver. 4.0.0

### ISSUE THREAD

**Issue by uakoo** [spring-cloud/spring-cloud-stream#2596]
**Issue**

Upgrading to `spring-boot:3.0.0 ` / `spring-cloud-stream:4.0.0` we are faced with the  following  exception raised on app start with suspicion of parameter valley `form / to `in `org.springframework.cloud.stream.binder#propagateSharedBeans` calling from  `org.springframework.cloud.stream.binder.propagateSharedBeans#initializeBinderContextSimple` which leads to not load of shared beans.

- stack trace

```18:32:51.331 INFO  [main      ] framework.cloud.stream.binder.DefaultBinderFactory - Creating binder: hgBinder
18:32:51.333 INFO  [main      ] framework.cloud.stream.binder.DefaultBinderFactory - Constructing binder child context for hgBinder
18:32:51.338 WARN  [main      ] framework.cloud.stream.binder.DefaultBinderFactory - Failed to propagate child beans. This may cause issues in your application
java.lang.IllegalStateException: hgBinder_context has not been refreshed yet
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1117)
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1275)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.propagateSharedBeans(DefaultBinderFactory.java:477)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.initializeBinderContextSimple(DefaultBinderFactory.java:426)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:308)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinderConventional(DefaultBinderFactory.java:253)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:163)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:153)
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:402)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:106)
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:98)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:587)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)```

- We use kafka binder with follwing config:
```spring:
  config:
    cloud:
      stream:
        binders:
          hgBinder:
            type: kafka
            environment:
              spring.cloud.stream.kafka.binder.brokers: xxx
              ...
        bindings:
          consumeXXX-in-0:
            binder: hgBinder
            destination: xxx
            content-type: application/x-protobuf
            group: ${spring.cloud.stream.bindings.consumeXXX-in-0.destination}.xxx
            consumer:
              batch-mode: true
        kafka:
          bindings:
            consumeXXX-in-0:
              consumer:
                configuration:
                  derive.type: true
                  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  value.deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer```

**To Reproduce**
Starting the app leads to above exception

**Version of the framework**

- spring-boot:3.0.0 
- spring-cloud-stream:4.0.0
- spring-cloud-stream-binder-kafka:4.0.0

**Expected behavior**
- no exceptions appears
- shared beans  are loaded in to context

Best Regards

**Comment by surendersinghssi490** [comment]
@uakoo did you get solution for above issue

**Comment by satakarn** [comment]
I encounter this issue too, however, now I face just only when I used multiple binders.
- springframework-boot: 3.0.0
- spring-cloud-starter-stream-kafka: 4.0.0
- spring-cloud-dependencies (bom): 2022.0.0

**Comment by silvio-didonna** [comment]
> I encounter this issue too, however, now I face just only when I used multiple binders.
> 
>     * springframework-boot: 3.0.0
> 
>     * spring-cloud-starter-stream-kafka: 4.0.0
> 
>     * spring-cloud-dependencies (bom): 2022.0.0

Same issue with multiple binders

**Comment by williamwjs** [comment]
Same issue with `kafka_context has not been refreshed yet`

* springframework-boot: 3.0.0

* spring-cloud-dependencies (bom): 2022.0.0    (spring-cloud-stream and spring-cloud-stream-binder-kafka)

**Comment by olegz** [comment]
Can someone please provide a reproducible sample? You can simply create a sample project and push it to github so we can take a look or attach a zip file with the project.

**Comment by fplaten** [comment]
Here is a small sample: https://github.com/fplaten/spring-cloud-stream-multi-binder

When starting it logs the error `outputBinder_context has not been refreshed yet` .

As the other have mentioned, removing the `environment` configuration fixes this.

**Comment by olegz** [comment]
This one is fixed, please give it a shot with the snapshot and let us know. The 4.0.1 release is scheduled for the end of the month

**Comment by fplaten** [comment]
It's working now for us. Thanks for the quick fix @olegz !

**Comment by sothawo** [comment]
Hm, wasn't released like it was planned. Any new info about when to get 4.0.1? 
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/8456476/214235147-439c4109-3494-401a-bfbd-66c0476f9085.png">

**Comment by zhangwei900808** [comment]
```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-rabbit</artifactId>
            <version>4.0.1</version>
        </dependency>
```
but still error
```
2023-06-18T11:25:07.771+08:00  WARN 68477 --- [           main] o.s.c.s.binder.DefaultBinderFactory      : Failed to propagate child beans. This may cause issues in your application

java.lang.IllegalStateException: kafka-binder_context has not been refreshed yet

```

**Comment by zhangwei900808** [comment]
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-stream</artifactId>
    <version>4.0.1</version>
</dependency>
```
It's Work!
