### ISSUE TITLE
BeanDefinitionOverrideException when using comma-separated destination on consumer binding

### ISSUE THREAD

**Issue by sataphat** [spring-cloud/spring-cloud-stream#2623]
**Describe the issue**
Getting the following error on application startup, failed to start.
```
org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:528) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:103) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:144) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binding.BindingService.lambda$rescheduleConsumerBinding$1(BindingService.java:209) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.3.jar:6.0.3]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'kafka-1392735791.downstreamEventsHandler-in-0.errors' defined in null: Cannot register bean definition [Root bean: class [org.springframework.messaging.SubscribableChannel]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null] for bean 'kafka-1392735791.downstreamEventsHandler-in-0.errors' since there is already [Root bean: class [org.springframework.messaging.SubscribableChannel]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:1003) ~[spring-beans-6.0.3.jar:6.0.3]
	at org.springframework.context.support.GenericApplicationContext.registerBeanDefinition(GenericApplicationContext.java:350) ~[spring-context-6.0.3.jar:6.0.3]
	at org.springframework.context.support.GenericApplicationContext.registerBean(GenericApplicationContext.java:556) ~[spring-context-6.0.3.jar:6.0.3]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:773) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:705) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:716) ~[spring-cloud-stream-binder-kafka-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:159) ~[spring-cloud-stream-binder-kafka-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:474) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	... 10 common frames omitted
```

**To Reproduce**
1. Define consumer binding with multiple (comma-separated string) `destination`, e.g.
```yaml
spring:
  cloud:
    stream:
      kafka:
        heartbeat:
          interval:
            ms: 1000
        binder:
          brokers: "kafka-dev.private.cloud:9092"
          auto-add-partitions: true
          consumer-properties:
            key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
      default:
        consumer:
          maxAttempts: 1

      function:
        definition: downstreamEventsHandler

      bindings:
        downstreamEventsHandler-in-0:
          destination: order-event.local,confirm-event.local
          contentType: application/json
          group: ${service.name}
``` 
2. Define a Consumer.
```java
@Configuration
public class StreamConfig {

    @Bean
    public Consumer<Message<?>> downstreamEventsHandler() {
        // Do something
    }
```
3. Start the application.

**Version of the framework**
Spring Boot 3.0.1
Spring Cloud 2022.0.0
Spring Cloud Stream 4.0.0
Spring Cloud Stream Binder Kafka 4.0.0
**Expected behavior**
Multiple destinations on consumer binding work without any error.

**Additional context**
This does NOT happen with Spring Boot 3.0.0/Spring Cloud 2022.0.0-RC2/Spring Cloud Stream 4.0.0-RC2

**Comment by sbernardo** [comment]
Hi @sataphat , this will be fixed in 4.0.1. There are two issues correlated with the same problem https://github.com/spring-cloud/spring-cloud-stream/issues/2599 https://github.com/spring-cloud/spring-cloud-stream/issues/2595
