### ISSUE TITLE
Kafka message no longer processed after upgrading from Spring Cloud Stream 3.2.4 to 4.0.1

### ISSUE THREAD

**Issue by gnagy** [spring-cloud/spring-cloud-stream#2662]
**Describe the issue**
I have a simple Spring Boot app in Kotlin using Spring Cloud Stream that has:

- REST endpoint that publishes a kafka message using streamBridge
- Consumer<> writing said message from same kafka topic to a database
- 2 test cases for valid and invalid messages, both passing with SCS 3.2.4 but failing with 4.0.1:
  - happy test case: message never arrives to consumer, test times out after 5sec
  - error case: Exception "Dispatcher has no subscribers for channel 'spring-example.message-saver-in-0'."

**To Reproduce**
See tests in https://github.com/vacuumlabs/spring-example/pull/1:
- `new transaction - valid`
- `new transaction - valid, nonexistent account number`

I tried debugging the issue and checking any changes from 3->4; looking at the Wiki and GitHub issues but can't see what might be the problem:

https://github.com/spring-cloud/spring-cloud-stream/wiki/4.0-Migration-guide
https://github.com/spring-cloud/spring-cloud-stream/issues/2610
https://github.com/spring-cloud/spring-cloud-stream/issues/2632

**Version of the framework**
Going from 3.2.4 to 4.0.1

**Expected behavior**
Message is published and consumed, or found on DLQ

**Comment by sobychacko** [comment]
@gnagy Could you provide a simple Java application where we can reproduce the issue easily? Also, could you include a simple README with step-by-step instructions to set up the app and the necessary components?

**Comment by gnagy** [comment]
Hi @sobychacko,

The issue occurred in the simple `spring-example` project I linked above. You can reproduce it by running the tests with `./gradlew test`. It uses testcontainers so you'll also need docker running.

https://github.com/vacuumlabs/spring-example/pull/1

**Comment by sobychacko** [comment]
I wonder if it is anything Kotlin-related? Can you compare the same setup with a Java application? If we were missing data, as you describe, it would have been a major issue on the 4.0 line, and we would have already seen it. I was unable to run your application due to some environment-related issues. If you can provide a similar Java project, I would be happy to look into it further.

**Comment by sobychacko** [comment]
@gnagy Any update on this issue?

**Comment by gnagy** [comment]
Hi, yes, I will find some time to see if I can reproduce same issue in Java.

**Comment by gnagy** [comment]
Hi @sobychacko,

I was able to reproduce with Java. 2 commits to this repo, app works with Spring Boot 2.7.0 but 2 tests fail with 3.0.5.

https://github.com/gnagy/spring-example-java/commits/master

**Comment by jamfor352** [comment]
I'm seeing this as well - specifically only when defining more than one function in spring.cloud.function.definition.

Is anybody actually looking at this?

The migration guide is pretty lacking, too.

https://github.com/spring-cloud/spring-cloud-stream/wiki/4.0-Migration-guide

No information apart from "Not SCSt directly changed but the fact that Kafka clients changed in Kafka binder there will be changes the user need to adjust to. We do not need to list them, but rather just list the version bump and point to their release notes / migration guide."

Of which there is nothing. 😕

**Comment by sobychacko** [comment]
@gnagy Apologies for not responding sooner. We somehow missed seeing the updates with the sample repo you added. I think it would be a good idea to ping us back if you are still waiting to hear from us within a week on a critical issue.  

This is your function definition.  `transaction-sender;message-saver.`  First, you do not need the `transaction-sender` in the definition since it is not a proper function but instead, using `StreamBridge` behind the scenes.  It doesn't hurt to have it there, but it unnecessarily creates superfluous bindings. However, this is not why your app is not working with Boot 3.0.5. In the latest version of Spring Cloud Stream (4.0.x line), we added a check to see if the function definition matches the actual function name. You set the function definition as `message-saver,` but your actual function name is `messageSaver.` You can fix the issue either by 

1. setting the function definition to `messageSaver` in the `application.yaml` or 
2. use a custom bean name on the function. For e.g. `@Bean(name = "message-saver")`. 

If you go with the first approach, change your bindings in the config to `messageSaver-in-0`. 
I tested both options, and both of them work for me. 

@jamfor352 Could you ensure your issues are related to what I described above? If not, please provide more details on your scenario so that we can triage it further.

**Comment by gnagy** [comment]
Hi @sobychacko, thanks for looking into this.

Good catch about `transaction-sender`,  I'll remove the function definition.

As for the naming, we tend to use kebab case in config yaml and camel case in code, and it usually works with Spring's relaxed binding: https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding

Would it be feasible to do relaxed matching for function names as well? Or maybe explicitly mention strict naming checks in the docs?

**Comment by jamfor352** [comment]
@sobychacko All good now.

**Comment by gnagy** [comment]
@sobychacko I'm making progress with setting the bean name to `message-saver`, however one test is still failing: it appears that in 3.x the message on the dead letter queue had a `x-exception-message` with the message of the exception thrown (`Account doesn't exist: ACC-654321`), whereas in 4.x the exception seems to be wrapped and the message reads:
```
error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@43ac9711]
```

Is this change intentional? Could we have the original business exception message back?

**Comment by sobychacko** [comment]
@gnagy Is your samples repo updated with that DLT failure scenario? In my local environment, all your tests are green with `message-saver`.

**Comment by gnagy** [comment]
@sobychacko yes I have pushed my change to the repo. `newTransaction_valid_nonexistentAccountNumber()` fails with:

```
Expecting actual:
  "error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@5c21b1ab]"
to end with:
  "Account doesn't exist: ACC-654321"
  ```

**Comment by sobychacko** [comment]
@gnagy Our apologies for not following up on this issue. We were quite busy with conference prep and other activities. Just checking to see if you made any resolution to this issue or are still stuck.

**Comment by gnagy** [comment]
Hi @sobychacko, thanks for getting back to me. I ran everything again with the latest dependency versions and see that the original exception in the DLT test scenario is still wrapped in a MessageHandlingException since 4.x. Is this change intentional? Before I was just getting my IllegalArgumentException.

This is the new `x-exception-stacktrace` header:

```
org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@318cf4be], failedMessage=GenericMessage [payload=byte[90], headers={kafka_offset=1, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@3ac0f181, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=0, contentType=application/json, kafka_receivedTopic=test-topic, kafka_receivedTimestamp=1695020138772, kafka_groupId=message-saver, target-protocol=kafka}]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:191)
	at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:108)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:73)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:373)
	at org.springframework.integration.channel.AbstractMessageChannel.sendWithMetrics(AbstractMessageChannel.java:344)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:324)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:297)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.lambda$sendMessage$1(MessageProducerSupport.java:262)
	at io.micrometer.observation.Observation.lambda$observe$0(Observation.java:493)
	at io.micrometer.observation.Observation.observeWithContext(Observation.java:603)
	at io.micrometer.observation.Observation.observe(Observation.java:492)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:262)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:394)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.lambda$onMessage$0(KafkaMessageDrivenChannelAdapter.java:464)
	at org.springframework.integration.kafka.inbound.KafkaInboundEndpoint.lambda$doWithRetry$0(KafkaInboundEndpoint.java:70)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:225)
	at org.springframework.integration.kafka.inbound.KafkaInboundEndpoint.doWithRetry(KafkaInboundEndpoint.java:66)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:461)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:425)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2873)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2854)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.lambda$doInvokeRecordListener$57(KafkaMessageListenerContainer.java:2772)
	at io.micrometer.observation.Observation.lambda$observe$4(Observation.java:544)
	at io.micrometer.observation.Observation.observeWithContext(Observation.java:603)
	at io.micrometer.observation.Observation.observe(Observation.java:544)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:2770)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:2622)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:2508)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:2150)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1505)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1469)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1344)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Account doesn't exist: ACC-654321
	at com.vacuumlabs.example.KafkaConfiguration.lambda$messageSaver$0(ExampleApplication.java:58)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeConsumer(SimpleFunctionRegistry.java:1029)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:731)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:577)
	at org.springframework.cloud.stream.function.PartitionAwareFunctionWrapper.apply(PartitionAwareFunctionWrapper.java:92)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:832)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:661)
	at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105)
	... 41 more
```
