### ISSUE TITLE
org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'myfunction-in-0' -> Caused by: java.lang.IllegalStateException: The [bean 'myfunction-in-0'] doesn't have subscribers to accept messages

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-stream#2679]
Hello Spring Cloud Stream team,

I would like to reach out reporting a strange issue on 4.0.3 snapshot

What I am trying to achieve:

Using spring cloud stream with reactor kafka, just take some messages from kafka, apply a transform and send it back to kafka to another topic.

In order to do so, here is some part of the code:

```
 @Bean
    public SenderOptionsCustomizer senderOptionsCustomizer(final MeterRegistry registry) {
        return (s, objectObjectSenderOptions) -> getSenderOptions(registry);
    }

    private SenderOptions<Object, Object> getSenderOptions(MeterRegistry registry) {
        final Map<String, Object> properties = new HashMap<>();
        properties.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServer);
        properties.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
        properties.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, JsonSerializer.class); //note it is json already
        final SenderOptions<Object, Object> senderOptions = SenderOptions.create(properties);
        return senderOptions.producerListener(new MicrometerProducerListener(registry));
    }
```

```
    public Function<Flux<String>, Flux<Foo>> myfunction() {
        return messages -> myReactiveRepository.saveAll(messages.map(message -> tranformMessageToFoo(message)));
    }
```

When I run this, it consumes fine, but after a while, I always meet this issue:

```
2023-03-31 12:42:23 20516 WARN  --- [boundedElastic-1] [myapp,notraceid,nospanid] o.s.i.channel.FluxMessageChannel : Error during processing event: GenericMessage [payload=[...], headers={kafka_offset=3066859395, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=2, kafka_receivedTopic=my_topic, kafka_receivedTimestamp=1677639647000, kafka_acknowledgment=my_topic-2@3066859395, contentType=application/json}]
org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'myfunction-in-0'
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInDeliveryExceptionIfNecessary(IntegrationUtils.java:166)
	at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:388)
	at org.springframework.integration.channel.AbstractMessageChannel.sendWithMetrics(AbstractMessageChannel.java:344)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:324)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:297)
	at org.springframework.integration.channel.FluxMessageChannel.lambda$subscribeTo$5(FluxMessageChannel.java:116)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableConditionalSubscriber.tryOnNext(FluxHandleFuseable.java:544)
	at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.runAsync(FluxPublishOn.java:992)
	at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.run(FluxPublishOn.java:1067)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: The [bean 'myfunction-in-0'] doesn't have subscribers to accept messages
	at org.springframework.util.Assert.state(Assert.java:97)
	at org.springframework.integration.channel.FluxMessageChannel.doSend(FluxMessageChannel.java:62)
	at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:373)
	... 14 common frames omitted
```

What is strange is that many messages of the pipeline are sent back to kafka successfully. I have evidence from downstream systems they can in their turn receive the transformed message.

Yet, some of the messages always hit this issue.

In order to rule out the message content issue, even sending one same message, this issue will be reproducible.

Could you please help on this issue?

Thank you

**Comment by olegz** [comment]
So, anything i say at this point is a wild guess, since the best way to handle this is to provide us with the way to reproduce it.
So a small sample project that reproduces the issue somewhere in Github would go a long way.

That said, I am wondering about your function and it's output.
What is this function producing? I see callback to  `saveAll` method, which appears to be the type of method that doesn't produce anything. Also, what does `all` means in this context? Is this a finite stream and you are waiting for all messages?
Anyway, I am speculating here, but wanted to give you a feel of its appearance to someone without a context.

Also, are you using regular Kafka binder or Kafka Streams binder ?

**Comment by olegz** [comment]
Also, keep in mind that since you are using reactive function you've effectively taken full control of the stream. The framework (s-c-stream) has no control over the reactive stream. That is a fundamental difference between reactive and imperative function. Imperative gets invoked by the framework on each message. Reactive gets invoked only once during the startup to connect user stream. After that we have no control over anything. That include any errors that may result in your code calling unsubscribe on the flux. So if you do (unsubscribe), that is 100% the issue.

**Comment by marcsmith57** [comment]
Hello @patpatpat123 , @olegz .. I am using 4.0.5 with reactive functions and running into the same issue occaionally. are you able to figure out the root cause of this intermittent issue ?

**Comment by dietmarweb** [comment]
I had this issue because the spring.cloud.function.definition was missing.

spring:
  cloud:
    function:
      definition: myFunction
