### ISSUE TITLE
AetherModuleResolver may not be picking up proxy settings

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#272]
As a user, I'm deploying a `stream` behind the firewall with an artifact repository that acts as a proxy; however, I'm unable to successfully deploy the stream, as the `AetherModuleResolver` resolver may not be picking up the proxy settings to resolve and download the module jar's required by the stream.

**Acceptance:**
* Module jar's are successfully resolved by `AetherModuleResolver`
* Streams successfully deploy behind the firewall with an artifact repository that acts as a proxy

**Comment by sabbyanandan** [comment]
Revisit this requirement once we have the core `spring-cloud-deployer` project in place.

**Comment by Mwea** [comment]
Still have the same problem here, we use a proxy without authentication. Any idea ?

**Comment by ngngsoftorg** [comment]
Same question here.  Looks like we are running into a similar issue.  This was closed, but it still appears to be an issue for running PCF+spring-cloud-dataflow behind a firewall+proxy.

**Comment by ngngsoftorg** [comment]
Our stack trace

```
2016-03-04T12:40:03.00-0800 [APP/0]      ERR Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.springframework.cloud.stream.module:log-sink:jar:exec:1.0.0.BUILD-SNAPSHOT from/to repository 1 (https://repo.spring.io/libs-snapshot): connect timed out
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.springframework.cloud.dataflow.app.resolver.AetherModuleResolver.resolve(AetherModuleResolver.java:253)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    ... 19 more
2016-03-04T12:40:03.00-0800 [APP/0]      ERR Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.springframework.cloud.stream.module:log-sink:jar:exec:1.0.0.BUILD-SNAPSHOT from/to repository 1 (https://repo.spring.io/libs-snapshot): connect timed out
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    ... 23 more
2016-03-04T12:40:03.00-0800 [APP/0]      ERR Caused by: java.net.SocketTimeoutException: connect timed out
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at java.net.PlainSocketImpl.socketConnect(Native Method)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at java.net.Socket.connect(Socket.java:589)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:532)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:409)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:158)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:287)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:243)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:59)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
2016-03-04T12:40:03.00-0800 [APP/0]      ERR    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
```

**Comment by ilayaperumalg** [comment]
Hi,

Since module launcher is now moved into `spring-cloud-dataflow` as `app-launcher` and the related proxy fixes are made in that repo.
While the in-process deployer proxy support was already fixed, please check if you run fine behind proxy with the changes from this fix: https://github.com/spring-cloud/spring-cloud-dataflow/pull/439 for `out-of-process` deployer.

Thanks!
