### ISSUE TITLE
BindersHealthContributor is not thread-safe

### ISSUE THREAD

**Issue by roookeee** [spring-cloud/spring-cloud-stream#2780]
**Describe the issue**
We are getting the following stack trace in our Spring Boot application which uses Spring Kafka Binders:
```
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756) ~[na:na]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateContribution(HealthEndpointSupport.java:155) ~[spring-boot-actuator-2.7.13.jar:2.7.13]
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:141)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateContribution(HealthEndpointSupport.java:156)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:141)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:110)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:78)
	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:90)
	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:85)
	at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[na:na]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282) ~[spring-core-5.3.28.jar:5.3.28]
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:74) ~[spring-boot-actuator-2.7.13.jar:2.7.13]
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)
	at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$ServletWebOperationAdapter.handle(AbstractWebMvcEndpointHandlerMapping.java:357)
	at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(AbstractWebMvcEndpointHandlerMapping.java:464)
	at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[na:na]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.28.jar:5.3.28]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
```
We checked most of the implementations of `NamedContributors<*>` and noticed that `DefaultContributorRegistry<*>` goes out of its way to guarantee thread-safety of its currently in use iterators (returned by `iterator()`) when adding or removing new contributors:
```java
@Override
public void registerContributor(String name, C contributor) {
    Assert.notNull(name, "Name must not be null");
    Assert.notNull(contributor, "Contributor must not be null");
    String adaptedName = this.nameFactory.apply(name);
    synchronized (this.monitor) {
        Assert.state(!this.contributors.containsKey(adaptedName),
            () -> "A contributor named \"" + adaptedName + "\" has already been registered");
        Map<String, C> contributors = new LinkedHashMap<>(this.contributors);
        contributors.put(adaptedName, contributor);
        this.contributors = Collections.unmodifiableMap(contributors);
    }
}
```
Already existing iterators refer to the old value of `this.contributors` so no `ConcurrentModificationException` can occur.

Thus it seems safe to assume that `NamedContributors<*>` are expected to be thread-safe in regards to currently existing iterators, which is not true for `BindersHealthContributor` (inside of `BindersHealthIndicatorAutoConfiguration`):

```java
// reduced snippet from actual code
public static class BindersHealthContributor implements CompositeHealthContributor {
    private Map<String, HealthContributor> contributors = new LinkedHashMap<>();

    void add(String binderConfigurationName, Map<String, HealthContributor> binderHealthContributors) {
        this.contributors.put(binderConfigurationName, getContributor(binderHealthContributors));
    }
    @Override
    public Iterator<NamedContributor<HealthContributor>> iterator() {
        return contributors.entrySet().stream()
            .map((entry) -> NamedContributor.of(entry.getKey(), entry.getValue())).iterator();
    }
}
```

Calling `add` while an iterator returned by `iterator()` is in use will create a `ConcurrentModificationException`.

We can't exactly pinpoint our (rarely occuring) stack trace to this `NamedContributors<*>` implementation, but there are no other concrete implementations on our class path that could produce such an exception. We didn't get into who calls `add` but it seems to be related to some internal listeners of Spring binders.

**Version of the framework**
3.2.8

**Expected behavior**
No `ConcurrentModificationException` can occur when calling `add` when an iterator returned by `iterator()` is in use

**Comment by sobychacko** [comment]
@roookeee This is now addressed via the commit mentioned above. In addition to locking the block where we modify the map, the `contributors` map is assigned a new reference, an atomic operation (the same way as in the Boot implementation). Please try it on the latest snapshot and see if you get the error again.
