### ISSUE TITLE
allTopicNames is deprecated from Admin

### ISSUE THREAD

**Issue by nabeelAtAlef** [spring-cloud/spring-cloud-stream#2784]
I am using springbboot 3.1.1
Springcloud - 2022.0.4

Issue - Getting error on publish - 
`Caused by: java.lang.NoSuchMethodError: 'org.apache.kafka.common.KafkaFuture org.apache.kafka.clients.admin.DescribeTopicsResult.allTopicNames()'
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.lambda$retrieveTopicDescriptions$1(KafkaTopicProvisioner.java:275) ~[spring-cloud-stream-binder-kafka-core-4.0.3.jar!/:4.0.3]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329) ~[spring-retry-1.3.1.jar!/:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209) ~[spring-retry-1.3.1.jar!/:na]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.retrieveTopicDescriptions(KafkaTopicProvisioner.java:267) ~[spring-cloud-stream-binder-kafka-core-4.0.3.jar!/:4.0.3]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.getPartitionsForTopic(KafkaTopicProvisioner.java:258) ~[spring-cloud-stream-binder-kafka-core-4.0.3.jar!/:4.0.3]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionProducerDestination(KafkaTopicProvisioner.java:194) ~[spring-cloud-stream-binder-kafka-core-4.0.3.jar!/:4.0.3]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionProducerDestination(KafkaTopicProvisioner.java:91) ~[spring-cloud-stream-binder-kafka-core-4.0.3.jar!/:4.0.3]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:286) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:102) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:153) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3]
	at org.springframework.cloud.stream.binding.BindingService.doBindProducer(BindingService.java:345) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3]
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:294) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3]
	at org.springframework.cloud.stream.function.StreamBridge.resolveDestination(StreamBridge.java:257) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:161) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:147) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:142) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3]
	at com.alefeducation.contentrepositoryservice.event.Publisher.publish(Publisher.kt:17) ~[classes!/:0.0.1-SNAPSHOT]
	at com.alefeducation.contentrepositoryservice.services.RepositoryService.createRepository(RepositoryService.kt:21) ~[classes!/:0.0.1-SNAPSHOT]
	at com.alefeducation.contentrepositoryservice.controller.RepositoryController.createRepository(RepositoryController.kt:22) ~[classes!/:0.0.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]`

I checked KafkaTopicProvisioner inside spring-cloud-stream-binder-kafka-core

private Map<String, TopicDescription> retrieveTopicDescriptions(String topicName, AdminClient adminClient) {
		return this.metadataRetryOperations.execute(context -> {
			try {
				if (logger.isDebugEnabled()) {
					logger.debug("Attempting to retrieve the description for the topic: " + topicName);
				}
				DescribeTopicsResult describeTopicsResult = adminClient
					.describeTopics(Collections.singletonList(topicName));
				KafkaFuture<Map<String, TopicDescription>> all = describeTopicsResult
					.allTopicNames();
				return all.get(this.operationTimeout, TimeUnit.SECONDS);
			}
			catch (Exception ex) {
				throw new ProvisioningException("Problems encountered with partitions finding for: " + topicName, ex);
			}
		});
	}
	
	allTopicNames is not an available method.

**Comment by nabeelAtAlef** [comment]
i tried the 3.0.9 springboot and 2022.x.x spring cloud, still the same issue.
