### ISSUE TITLE
postProcessResult NullPointerException

### ISSUE THREAD

**Issue by brodov** [spring-cloud/spring-cloud-stream#2867]
Hello!
I tried new functionality [runtime-error-handling](https://docs.spring.io/spring-cloud-stream/reference/kafka/kafka-streams-binder/error-handling.html#runtime-error-handling)
`spring-cloud-stream:4.1.0`
And got NullPointerException in function `org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper#postProcessResult`
because `Object result` is null.
This function called from 
`org.springframework.cloud.stream.function.StreamBridge#send(java.lang.String, java.lang.String, java.lang.Object, org.springframework.util.MimeType)`
and second part of this if statement looks suspicious, should it contain not equal?
```
		if (resultMessage == null
			&& ((Message) messageToSend).getPayload().getClass().getName().equals("org.springframework.kafka.support.KafkaNull")) {
			resultMessage = messageToSend;
		}
```

<img width="972" alt="Screenshot 2023-12-10 at 03 34 40" src="https://github.com/spring-cloud/spring-cloud-stream/assets/30843717/dcbfb8da-b15e-46c9-83f7-8b665d288b02">
<img width="969" alt="Screenshot 2023-12-10 at 03 37 51" src="https://github.com/spring-cloud/spring-cloud-stream/assets/30843717/36166b98-884f-42ff-bbd6-2f74269e15b6">

```
		synchronized (this) {
			resultMessage = (Message<byte[]>) functionToInvoke.apply(messageToSend);
		}
```

after synchronized resultMessage is null

<img width="1038" alt="Screenshot 2023-12-10 at 23 08 29" src="https://github.com/spring-cloud/spring-cloud-stream/assets/30843717/d2986329-118f-49e2-8211-fb7879192183">

```
org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000000, topic=dev.some-logs, partition=0, offset=0, stacktrace=java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "result" is null
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.doPostProcessResult(CloudEventsFunctionInvocationHelper.java:138)
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.postProcessResult(CloudEventsFunctionInvocationHelper.java:114)
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.postProcessResult(CloudEventsFunctionInvocationHelper.java:48)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:193)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:147)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:142)
	at org.springframework.cloud.stream.binder.kafka.streams.DltAwareProcessor.lambda$defaultProcessorRecordRecoverer$0(DltAwareProcessor.java:83)
	at org.springframework.cloud.stream.binder.kafka.streams.RecordRecoverableProcessor.process(RecordRecoverableProcessor.java:90)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:152)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$doProcess$1(StreamTask.java:810)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872)
	at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:810)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:741)
	at org.apache.kafka.streams.processor.internals.TaskExecutor.processTask(TaskExecutor.java:97)
	at org.apache.kafka.streams.processor.internals.TaskExecutor.process(TaskExecutor.java:78)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:1765)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:807)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:617)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:579)

	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:767) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.TaskExecutor.processTask(TaskExecutor.java:97) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.TaskExecutor.process(TaskExecutor.java:78) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:1765) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:807) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:617) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:579) ~[kafka-streams-3.6.0.jar:na]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "result" is null
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.doPostProcessResult(CloudEventsFunctionInvocationHelper.java:138) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.postProcessResult(CloudEventsFunctionInvocationHelper.java:114) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.postProcessResult(CloudEventsFunctionInvocationHelper.java:48) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:193) ~[spring-cloud-stream-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:147) ~[spring-cloud-stream-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:142) ~[spring-cloud-stream-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.binder.kafka.streams.DltAwareProcessor.lambda$defaultProcessorRecordRecoverer$0(DltAwareProcessor.java:83) ~[spring-cloud-stream-binder-kafka-streams-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.binder.kafka.streams.RecordRecoverableProcessor.process(RecordRecoverableProcessor.java:90) ~[spring-cloud-stream-binder-kafka-streams-4.1.0.jar:4.1.0]
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:152) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$doProcess$1(StreamTask.java:810) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:810) ~[kafka-streams-3.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:741) ~[kafka-streams-3.6.0.jar:na]
	... 6 common frames omitted
```

code almost the same as code from documentation
```
    @Bean
    public Function<KStream<String, MyAvro>,KStream<String, MyAvro>> process(DltPublishingContext dltPublishingContext) {
        return input -> input.process(() -> new DltAwareProcessor<>(record -> {
            throw new RuntimeException("error");
        }, "hello-dlt-1", dltPublishingContext));
    }
```

**Comment by brodov** [comment]
Found the problem `org.springframework.cloud.function.context.config.SmartCompositeMessageConverter#toMessage(java.lang.Object, org.springframework.messaging.MessageHeaders)`
there is no suitable converter and as result resultMessage is null. It was not obvious for me, and null pointer exception did not tell much :)

**Comment by imgoby** [comment]
I meet the same issue on using native-image 

<img width="974" height="218" alt="Image" src="https://github.com/user-attachments/assets/29748a99-2c33-4ef3-981a-3682da83679a" />

```
	Message<?> resultMessage;
		synchronized (this) {
			resultMessage = (Message<byte[]>) functionToInvoke.apply(messageToSend);
		}
```

resultMessage  is null.
