### ISSUE TITLE
`"Object.getClass()" because "result" is null` with spring-cloud-starter-openfeign

### ISSUE THREAD

**Issue by kper** [spring-cloud/spring-cloud-stream#2880]
I am upgrading my service from spring boot version 2.x to 3.2.1 and noticed a regression. In particular, my application stops working when I am using spring-cloud-stream and spring-cloud-starter-openfeign.
I have created a minimal example which you can find here:
https://github.com/kper/spring_cloud_bug_kafka_feign

The initial setup works without any exception.
However, if you go the `pom.xml` you can uncomment the `spring-cloud-starter-openfeign` dependency and you will get the following exception when running the app:

```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "result" is null
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.doPostProcessResult(CloudEventsFunctionInvocationHelper.java:138) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.postProcessResult(CloudEventsFunctionInvocationHelper.java:114) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.postProcessResult(CloudEventsFunctionInvocationHelper.java:48) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:193) ~[spring-cloud-stream-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:147) ~[spring-cloud-stream-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:142) ~[spring-cloud-stream-4.1.0.jar:4.1.0]
	at com.example.demo.AcceptanceKafkaTestProducer.sendAcceptanceResponse(AcceptanceKafkaTestProducer.java:28) ~[classes/:na]
	at com.example.demo.DemoApplication.run(DemoApplication.java:25) ~[classes/:na]
	at ...
```

**Comment by sobychacko** [comment]
I am closing this issue since it is a duplicate of https://github.com/spring-cloud/spring-cloud-stream/issues/2881.

**Comment by kper** [comment]
@sobychacko thank you for your response!

But I don't agree with your claim that this is a duplicate. The linked issue #2881 does not work with avro. However, this bug does not use avro.

**Comment by sobychacko** [comment]
@kper Do you need the openfeign dependency to reproduce the issue? It is currently commented out in your build configuration.

**Comment by kper** [comment]
@sobychacko yes you need it

If you clone the repo and run it (without openfeign) then it will work.
Once you uncomment the dependency then it will magically throw an exception

**Comment by sobychacko** [comment]
Could you add a getter and setter for the `data` field in your `Sensor` class? When `openfeign` is in your classpath, the underlying `JSON` serialization fails if the getters/setters are missing. I didn't get the chance to see why that's the case. However, if this is something you can add and move on, we can close this issue since I don't see any issues from a Spring Cloud Stream perspective.

**Comment by kper** [comment]
@sobychacko yes this seems to have caused it. Sadly the exception is very misleading. Thank you for your support!
