### ISSUE TITLE
`"Object.getClass()" because "result" is null` with avro

### ISSUE THREAD

**Issue by kper** [spring-cloud/spring-cloud-stream#2881]
I am upgrading my app from spring boot 2.x to 3.2 and I think that I have found another regression. In my minimal example, I try to send an avro message. This is a possible duplicate of #2880.

Working 2.7 version: https://github.com/kper/spring_cloud_bug_avro_v2.7.14
Not Working 3.2.1 version: https://github.com/kper/spring_cloud_bug_avro_v3.2.1

Differences:

```
pom.xml
<version>2.7.14</version> to <version>3.2.1</version>
<spring-cloud.version>2021.0.0</spring-cloud.version> to <spring-cloud.version>2023.0.0</spring-cloud.version>
```

Exception:
```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "result" is null
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.doPostProcessResult(CloudEventsFunctionInvocationHelper.java:138) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.postProcessResult(CloudEventsFunctionInvocationHelper.java:114) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.postProcessResult(CloudEventsFunctionInvocationHelper.java:48) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:193) ~[spring-cloud-stream-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:147) ~[spring-cloud-stream-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:142) ~[spring-cloud-stream-4.1.0.jar:4.1.0]
	at com.example.demo.AcceptanceKafkaTestProducer.sendAcceptanceResponse(AcceptanceKafkaTestProducer.java:20) ~[classes/:na]
	at com.example.demo.DemoApplication.run(DemoApplication.java:20) ~[classes/:na]
	at ....
```

**Comment by sobychacko** [comment]
@kper You are getting this exception because no proper AVRO message converters are available. The content type set is `application/avro`, but no appropriate converters are found. Starting with version `4.0.x` of the framework, we [removed](https://github.com/spring-cloud/spring-cloud-function/commit/c8109270d2bfa8c43582cc61011fbd5b66eca2c8) the AVRO message converter from Spring Cloud Function. This is because the schema registry provided by Spring Cloud moved into the core Spring Cloud Stream starting with `4.0.x`, and these AVRO converters in Spring Cloud Function were also moved since these were initially provided to support the schema registry. Since `4.0.x` was a major release, we decided to move things around and centralize all schema registry-related components within Spring Cloud Stream. To solve your problem, could you please provide an appropriate AVRO converter? If you want to stick with the implementation provided by Spring Cloud Stream, which is intended to use with schema registry, you can add these two beans in your application.
```
@Bean
public static AvroSchemaServiceManager avroSchemaServiceManager() {
	return new AvroSchemaServiceManagerImpl();
}

@Bean
public static AvroSchemaMessageConverter avroSchemaMessageConverter(AvroSchemaServiceManager avroSchemaServiceManager) {
	return new AvroSchemaMessageConverter(avroSchemaServiceManager);
}
```
And you need to add this maven dependency as well:
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream-schema-registry-client</artifactId>
</dependency>
```

**Comment by kper** [comment]
@sobychacko thank you that's works for me now :)
I am closing this issue
