### ISSUE TITLE
Function router with kafka streams not deserializing bytearray

### ISSUE THREAD

**Issue by scarm01** [spring-cloud/spring-cloud-stream#2890]
I have the following simple `messageRoutingCallback` which I'll use to route messages to the correct kafka stream according to some value in the header.
For now I kept it really simple, so all messages will be routed to the same function.

```java
@Configuration
public class MessageRoutingConfig {
    @Bean
    public MessageRoutingCallback messageRoutingCallback() {
        return new MessageRoutingCallback() {
            @Override
            public String routingResult(Message<?> message) {
                return "myFunction";
            }
        };
    }
}
```

So all messages get routed to the following function.
```java
    @Bean
    public Function<KStream<String, MyObject>,
            KStream<String, MyObject>> myFunction() {
        return myEvent -> {
            // do something with the event end publish it to another stream
        };
    }
```

The configuration I am using is the following:
```yaml
spring.cloud:
  stream:
    function.routing.enabled: true
    bindings:
      functionRouter-in-0.destination: ${myTopicName}

      myFunction-out-0.destination: ${myOtherTopicName}

    kafka.streams:
      binder:
        state-store-retry:
          max-attempts: 3
          backoff-period: 5000
        configuration:
          commit.interval.ms: 1000
          auto.offset.reset: latest
```

I am using version 4.1.0 of Spring Cloud Messaging.

The problem is that when messages get routed to `myFunction` they are not automatically converted to `MyObject`. The messages have `application/json` as content type.

I was expecting that messages will still be converted.

Spring documentation says that error might happen in conversion when using function routing, and recommends to use this property `spring.cloud.stream.kafka.streams.bindings.<process-in-0>.consumer.useConfiguredSerdeWhenRoutingEvents` (according to this page https://docs.spring.io/spring-cloud-stream/reference/kafka/kafka-streams-binder/event-type-based-routing-in-applications.html).
But even adding it, the conversion is not happening at all and `myFunction` receives an array of bytes.

Follows the full stack trace:
```
org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:2930) ~[spring-kafka-3.1.0.jar:3.1.0]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2871) ~[spring-kafka-3.1.0.jar:3.1.0]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2835) ~[spring-kafka-3.1.0.jar:3.1.0]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.lambda$doInvokeRecordListener$56(KafkaMessageListenerContainer.java:2753) ~[spring-kafka-3.1.0.jar:3.1.0]
	at io.micrometer.observation.Observation.observe(Observation.java:565) ~[micrometer-observation-1.12.0.jar:1.12.0]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:2751) ~[spring-kafka-3.1.0.jar:3.1.0]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:2604) ~[spring-kafka-3.1.0.jar:3.1.0]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:2490) ~[spring-kafka-3.1.0.jar:3.1.0]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:2132) ~[spring-kafka-3.1.0.jar:3.1.0]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1487) ~[spring-kafka-3.1.0.jar:3.1.0]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1451) ~[spring-kafka-3.1.0.jar:3.1.0]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1322) ~[spring-kafka-3.1.0.jar:3.1.0]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1804) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: org.springframework.kafka.KafkaException: Failed to execute runnable
	at org.springframework.integration.kafka.inbound.KafkaInboundEndpoint.doWithRetry(KafkaInboundEndpoint.java:82) ~[spring-integration-kafka-6.2.0.jar:6.2.0]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:457) ~[spring-integration-kafka-6.2.0.jar:6.2.0]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:422) ~[spring-integration-kafka-6.2.0.jar:6.2.0]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2857) ~[spring-kafka-3.1.0.jar:3.1.0]
	... 13 common frames omitted
Caused by: org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@393c843a]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:191) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:108) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:73) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:132) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:378) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at org.springframework.integration.channel.AbstractMessageChannel.sendWithMetrics(AbstractMessageChannel.java:349) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:329) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:302) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-6.1.1.jar:6.1.1]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-6.1.1.jar:6.1.1]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-6.1.1.jar:6.1.1]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-6.1.1.jar:6.1.1]
	at org.springframework.integration.endpoint.MessageProducerSupport.lambda$sendMessage$1(MessageProducerSupport.java:262) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.12.0.jar:1.12.0]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:262) ~[spring-integration-core-6.2.0.jar:6.2.0]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:391) ~[spring-integration-kafka-6.2.0.jar:6.2.0]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.lambda$onMessage$0(KafkaMessageDrivenChannelAdapter.java:460) ~[spring-integration-kafka-6.2.0.jar:6.2.0]
	at org.springframework.integration.kafka.inbound.KafkaInboundEndpoint.lambda$doWithRetry$0(KafkaInboundEndpoint.java:77) ~[spring-integration-kafka-6.2.0.jar:6.2.0]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329) ~[spring-retry-2.0.4.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:225) ~[spring-retry-2.0.4.jar:na]
	at org.springframework.integration.kafka.inbound.KafkaInboundEndpoint.doWithRetry(KafkaInboundEndpoint.java:70) ~[spring-integration-kafka-6.2.0.jar:6.2.0]
	... 16 common frames omitted
Caused by: java.lang.ClassCastException: class [B cannot be cast to class org.apache.kafka.streams.kstream.KStream ([B is in module java.base of loader 'bootstrap'; org.apache.kafka.streams.kstream.KStream is in unnamed module of loader 'app')
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunctionAndEnrichResultIfNecessary(SimpleFunctionRegistry.java:958) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunction(SimpleFunctionRegistry.java:904) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:740) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:580) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.context.config.RoutingFunction.route(RoutingFunction.java:196) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.context.config.RoutingFunction.apply(RoutingFunction.java:107) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:731) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:580) ~[spring-cloud-function-context-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.function.PartitionAwareFunctionWrapper.apply(PartitionAwareFunctionWrapper.java:92) ~[spring-cloud-stream-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:832) ~[spring-cloud-stream-4.1.0.jar:4.1.0]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:661) ~[spring-cloud-stream-4.1.0.jar:4.1.0]
	at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105) ~[spring-integration-core-6.2.0.jar:6.2.0]
	... 38 common frames omitted
```

**Comment by sobychacko** [comment]
@scarm01 The message routing feature you showed above (`MessageRoutingCallback`) is intended only for the regular Kafka binder that uses message channels for target binding. This cannot be applied to the Kafka Streams binder, which uses different conduits for binding. When using the Kafka Streams binder, you should remove the function router entirely from your application. The routing mechanism in the Kafka Streams binder is based on the event-type filtering feature in the binder. The ref documentation that you mentioned above has more details about it. When producing the message for your Kafka Streams function, you need to set an `event-type` header in order to activate event-based routing. Then, you need to set the `spring.cloud.stream.kafka.streams.bindings.myFunction-in-0.consumer.eventTypes` property to match what you set for the  `event-type` header. See this test for more details: https://github.com/spring-cloud/spring-cloud-stream/blob/main/binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsEventTypeRoutingTests.java

**Comment by scarm01** [comment]
Thank for your clarification. I thought that since cloud stream was using cloud function I could route functions.
I'll use headers.
