### ISSUE TITLE
KafkaBinderConfigurationProperties fails on empty string as Truststore path

### ISSUE THREAD

**Issue by babubabu** [spring-cloud/spring-cloud-stream#2911]
If an empty string is set as truststore.location, the KafkaBinderConfigurationProperties fails to copy the truststore in the current version 4.0.5

This is the case during our build integration-test setup. 
We also set ``` spring.cloud.stream.kafka.binder.configuration.security.protocol=PLAINTEXT ```. But there is no different behaviour.

**Simple patch appended**
Due to organizational restrictions, I am not allowed to push to your repo... I produced a simple patch with ``` StringUtils.hasText()``` 
Furthermore I was not able to start the tests, so I couldn't provide a useful test-example...

**To Reproduce**
1. application.yml
set property: 
```spring.cloud.stream.kafka.binder.configuration.ssl.truststore.location: ${TRUSTSTORE_PATH}```
2. Start application

**verison: 4.0.5**
Error message:
Caused by: java.lang.IllegalStateException: java.io.FileNotFoundException: class path resource [${TRUSTSTORE_PATH}] cannot be opened because it does not exist
	at org.springframework.cloud.stream.binder.kafka.properties.KafkaBinderConfigurationProperties.moveCertsToFileSystemIfNecessary(KafkaBinderConfigurationProperties.java:199)
	at org.springframework.cloud.stream.binder.kafka.properties.KafkaBinderConfigurationProperties.getKafkaConnectionString(KafkaBinderConfigurationProperties.java:183)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.normalalizeBootPropsWithBinder(KafkaTopicProvisioner.java:300)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.<init>(KafkaTopicProvisioner.java:140)
	at org.springframework.cloud.stream.binder.kafka.config.KafkaBinderConfiguration.provisioningProvider(KafkaBinderConfiguration.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 161 more
Caused by: java.io.FileNotFoundException: class path resource [${TRUSTSTORE_PATH}] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:211)
	at org.springframework.cloud.stream.binder.kafka.properties.KafkaBinderConfigurationProperties.moveCertToFileSystem(KafkaBinderConfigurationProperties.java:243)
	at org.springframework.cloud.stream.binder.kafka.properties.KafkaBinderConfigurationProperties.moveCertsIfApplicable(KafkaBinderConfigurationProperties.java:208)
	at org.springframework.cloud.stream.binder.kafka.properties.KafkaBinderConfigurationProperties.moveCertsToFileSystemIfNecessary(KafkaBinderConfigurationProperties.java:191)
	... 170 more

[Fixing_empty_truststore-config_in_Kafka_Streams_binder.patch](https://github.com/spring-cloud/spring-cloud-stream/files/14420209/Fixing_empty_truststore-config_in_Kafka_Streams_binder.patch)

**Comment by babubabu** [comment]
created PR #2912
