### ISSUE TITLE
spring-cloud-stream latest versions not compatible with  spring-boot-3.4.0 

### ISSUE THREAD

**Issue by ksanjeev9211** [spring-cloud/spring-cloud-stream#3048]
I have a spring-boot and spring-cloud-stream based app which listens to kinesis using spring-cloud-stream-kinesis-binder.
The version for different libs are as follows:

spring-boot : 3.3.5
spring-cloud.version : 2023.0.3
spring-cloud-stream-binder-kinesis : 4.0.4
spring-cloud-stream: 4.1.3

when I tried the following combination :

spring-boot : 3.4.0
spring-cloud.version : 2023.0.3
spring-cloud-stream-binder-kinesis : 4.0.4
spring-cloud-stream: 4.1.3

an error was thrown:
**java.lang.NoSuchMethodError: 'org.springframework.integration.support.MessageBuilder org.springframework.integration.support.MessageBuilder.removeHeader(java.lang.String)'**

when I tried the following , no error was thrown

spring-boot : 3.3.5
spring-cloud.version : 2024.0.0-RC1
spring-cloud-stream-binder-kinesis : 4.0.4
spring-cloud-stream: 4.2.0-RC1

 once again with the following combination, the same error was thrown

spring-boot : 3.4.0
spring-cloud.version : 2024.0.0-RC1
spring-cloud-stream-binder-kinesis : 4.0.4
spring-cloud-stream: 4.2.0-RC1

 full stack trace is here: 

Exception in thread "Consumer for [date-input-stream]-kinesis-consumer-1" java.lang.NoSuchMethodError: 'org.springframework.integration.support.MessageBuilder org.springframework.integration.support.MessageBuilder.removeHeader(java.lang.String)'
at org.springframework.cloud.stream.function.FunctionConfiguration.sanitize(FunctionConfiguration.java:395)
at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:817)
at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:657)
at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105)
at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:73)
at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:132)
at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:148)
at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:121)
at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:390)
at org.springframework.integration.channel.AbstractMessageChannel.sendWithMetrics(AbstractMessageChannel.java:361)
at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:331)
at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:304)
at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
at org.springframework.integration.endpoint.MessageProducerSupport.lambda$sendMessage$1(MessageProducerSupport.java:261)
at io.micrometer.observation.Observation.observe(Observation.java:499)
at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:261)
at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter.access$1800(KinesisMessageDrivenChannelAdapter.java:107)
at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.performSend(KinesisMessageDrivenChannelAdapter.java:1365)
at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.processSingleRecord(KinesisMessageDrivenChannelAdapter.java:1274)
at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.processRecords(KinesisMessageDrivenChannelAdapter.java:1261)
at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.lambda$processTask$8(KinesisMessageDrivenChannelAdapter.java:1098)
at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ConsumerInvoker.run(KinesisMessageDrivenChannelAdapter.java:1446)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by artembilan** [comment]
This was fixed via: https://github.com/spring-cloud/spring-cloud-stream/commit/17ac6352e4458366d9d030b95c7d569e6ca4ba6a. Will be included into `4.2.0`, but apparently has to be back-ported for the first combination of versions for compatibility.

**Comment by ksanjeev9211** [comment]
I didn't get it, do you mean it is fixed via [17ac635](https://github.com/spring-cloud/spring-cloud-stream/commit/17ac6352e4458366d9d030b95c7d569e6ca4ba6a) or  it shud work with  spring-cloud-stream 4.2.0-RC1?

**Comment by artembilan** [comment]
No, I mean the fix is in, but it is going to be released in GA in a couple weeks.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-cloud/spring-cloud-stream/commit/17ac6352e4458366d9d030b95c7d569e6ca4ba6a.
Spring Cloud `2024.0.0` has been just released and that one is fully compatible with Spring Boot `3.4.0`.
Nothing else to do here.

**Comment by songva** [comment]
Hope my question is not off topic, will spring-cloud-stream-binder-kafka-core also be updated? For instance, spring-boot-autoconfigure has removed the buildAdminProperties() in KafkaProperties.
