### ISSUE TITLE
Spring cloud stopped supporting SpEL

### ISSUE THREAD

**Issue by kucera-jan-cz** [spring-cloud/spring-cloud-stream#3056]
**Issue**
After update of Spring boot we noticed issue working with dynamic routing key, because Binder lacks conversion for Spring Expression and fails with following error:

`Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]
	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:119)
	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:101)
	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:93)
	at org.springframework.boot.context.properties.bind.Binder.bindProperty(Binder.java:463)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:407)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:350)`

**Steps To Reproduce**
```spring.cloud.stream.rabbit:
        default:
          producer:
            exchange-type: topic
            routingKeyExpression: headers['amqp_receivedRoutingKey']
```

**Version of the framework**: 
Spring: 6.3.6
Spring Cloud Stream: 4.1.4

**Previously worked with**:
Spring Boot: 6.3.4
Spring Cloud Stream: 4.1.2

Issue already mentioned at [StackOverflow](https://stackoverflow.com/questions/79257534/spring-boot-3-4-0-converternotfoundexception-for-spel-property-spring-cloud-str)

**Comment by olegz** [comment]
This has been addressed and backported to 4.1 - https://github.com/spring-cloud/spring-cloud-stream/issues/3053
Please try with 4.1.5-SNAPSHOT
