### ISSUE TITLE
Explicit content type in bindings configuration broken for redis

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#383]
If you use `spring.cloud.stream.bindings.output.content-type: application/json` (for instance) with a Redis transport, the message header gets converted to JSON in `EmbeddedHeadersMessageConverter`, and the `MimeType` is converted to a JSON object (not just the String representation). When it lands in the consumer there is an exception because it tries to convert back from JSON with no type information:

```
Caused by: java.lang.IllegalArgumentException: Unknown type for contentType header value: class java.util.LinkedHashMap
	at org.springframework.messaging.converter.DefaultContentTypeResolver.resolve(DefaultContentTypeResolver.java:69) ~[spring-messaging-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.messaging.converter.AbstractMessageConverter.getMimeType(AbstractMessageConverter.java:237) ~[spring-messaging-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.messaging.converter.AbstractMessageConverter.supportsMimeType(AbstractMessageConverter.java:224) ~[spring-messaging-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.messaging.converter.AbstractMessageConverter.canConvertFrom(AbstractMessageConverter.java:179) ~[spring-messaging-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.cloud.stream.converter.AbstractFromMessageConverter.canConvertFrom(AbstractFromMessageConverter.java:146) ~[spring-cloud-stream-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:172) ~[spring-messaging-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:167) ~[spring-messaging-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:55) ~[spring-messaging-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.convertPayloadIfNecessary(AbstractMessageChannel.java:482) [spring-integration-core-4.2.5.RELEASE.jar:na]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:426) [spring-integration-core-4.2.5.RELEASE.jar:na]
	... 30 common frames omitted
```

It works with Rabbit, I guess because the transport has explicit support for headers, so there is no coercion to JSON and back again.

**Comment by ilayaperumalg** [comment]
@dsyer It appears that the `EmbeddedHeadersMessageConverter` always [uses] (https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/EmbeddedHeadersMessageConverter.java#L65)  `String` values in headers when embedding.

I could not replicate the issue you mentioned above. Is this against a specific version of SCSt or the latest master?

**Comment by dsyer** [comment]
`EmbeddedHeadersMessageConverter` does not always use string values: it uses an `ObjectMapper` to convert them (https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/EmbeddedHeadersMessageConverter.java#L65).
