### ISSUE TITLE
Using a `PollableChannel` as the output channel on a Source is not allowed

### ISSUE THREAD

**Issue by mminella** [spring-cloud/spring-cloud-stream#410]
When creating a Source, if you configure the output channel to be a `PollableChannel` you get the exception pasted below.  

**Config**
```
@Configuration
@ConditionalOnClass({EnableBinding.class, EnableTask.class})
public class TaskEventAutoConfiguration {

	@Configuration
	@EnableBinding(TaskEventChannels.class)
	public static class ListenerConfiguration {

		@Autowired
		private TaskEventChannels taskEventChannels;

		@Bean
		public GatewayProxyFactoryBean taskEventListener() {
			GatewayProxyFactoryBean factoryBean =
					new GatewayProxyFactoryBean(TaskExecutionListener.class);

			factoryBean.setDefaultRequestChannel(taskEventChannels.taskEvents());

			return factoryBean;
		}
	}

	public interface TaskEventChannels {

		String TASK_EVENTS = "task-events";

		@Output(TASK_EVENTS)
		PollableChannel taskEvents();
	}
}
```

**Stacktrace**

```
org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.IllegalArgumentException: Object of class [org.springframework.integration.channel.QueueChannel] must be an instance of interface org.springframework.messaging.SubscribableChannel
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:852) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140) ~[spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at com.example.TaskEventListenerApplication.main(TaskEventListenerApplication.java:14) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_60-ea]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_60-ea]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_60-ea]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_60-ea]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
Caused by: java.lang.IllegalArgumentException: Object of class [org.springframework.integration.channel.QueueChannel] must be an instance of interface org.springframework.messaging.SubscribableChannel
	at org.springframework.util.Assert.isInstanceOf(Assert.java:346) ~[spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.util.Assert.isInstanceOf(Assert.java:326) ~[spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.cloud.stream.binder.redis.RedisMessageChannelBinder.bindProducer(RedisMessageChannelBinder.java:260) ~[spring-cloud-stream-binder-redis-1.0.0.BUILD-20160309.170054-280.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.redis.RedisMessageChannelBinder.bindProducer(RedisMessageChannelBinder.java:71) ~[spring-cloud-stream-binder-redis-1.0.0.BUILD-20160309.170054-280.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.ChannelBindingService.bindProducer(ChannelBindingService.java:87) ~[spring-cloud-stream-1.0.0.BUILD-20160309.170054-297.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:266) ~[spring-cloud-stream-1.0.0.BUILD-20160309.170054-297.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:57) ~[spring-cloud-stream-1.0.0.BUILD-20160309.170054-297.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	... 19 common frames omitted
```

**Comment by mbogoevici** [comment]
See: https://github.com/spring-cloud/spring-cloud-stream/issues/436#issuecomment-205430607

**Comment by mbogoevici** [comment]
Closing this based on the resolution of https://github.com/spring-cloud/spring-cloud-stream/issues/436
