### ISSUE TITLE
Use BinderAwareChannelResolver with Kafka Binder encountered a ClassCastException

### ISSUE THREAD

**Issue by sunnykaka** [spring-cloud/spring-cloud-stream#483]
I'am using spring cloud stream with kafka.  

I wan't to use `BinderAwareChannelResolver ` to create message channel in code.  

here is my code:
```Java
public class EventActivator {

    @Autowired
    private BinderAwareChannelResolver binderAwareChannelResolver;

    public boolean sendMessage(String message, String destination) {

        MessageChannel messageChannel = binderAwareChannelResolver.resolveDestination(destination);
        //...
    }

}

```

my configration:
```Java
    @Bean
    public BinderAwareChannelResolver binderAwareChannelResolver(BinderFactory<MessageChannel> binderFactory,
                                                                 ChannelBindingServiceProperties channelBindingServiceProperties,
                                                                 DynamicDestinationsBindable dynamicDestinationsBindable,
                                                                 BindableChannelFactory bindableChannelFactory) {

        return new BinderAwareChannelResolver(binderFactory, channelBindingServiceProperties,
                dynamicDestinationsBindable, bindableChannelFactory);
    }

```

If I call `binderAwareChannelResolver.resolveDestination(destination);`, a ClassCastException occurred.  Here is the stack trace:

```
java.lang.ClassCastException: org.springframework.cloud.stream.binder.ProducerProperties cannot be cast to org.springframework.cloud.stream.binder.ExtendedProducerProperties
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.doBindProducer(KafkaMessageChannelBinder.java:104) ~[spring-cloud-stream-binder-kafka-1.0.0.RC1.jar:1.0.0.RC1]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:163) ~[spring-cloud-stream-1.0.0.RC1.jar:1.0.0.RC1]
	at org.springframework.cloud.stream.binding.BinderAwareChannelResolver.resolveDestination(BinderAwareChannelResolver.java:115) ~[spring-cloud-stream-1.0.0.RC1.jar:1.0.0.RC1]
	at com.akkafun.common.event.service.EventActivator.sendMessage(EventActivator.java:49) ~[classes/:na]
```

I look into the `BinderAwareChannelResolver` source code,  found the exception was raise by this code:
```Java
					this.dynamicDestinationsBindable.addOutputBinding(beanName,
							binder.bindProducer(destinationName, channel, producerProperties));				
```
The `binder` is `KafkaMessageChannelBinder`, `binder.bindProducer` method need a `ExtendedProducerProperties`, but the type of `producerProperties` is `ProducerProperties`.
So a `ClassCastException` was thrown.

To solve the problem, I have to use a custom `BinderAwareChannelResolver `. I find the code in `ChannelBindingService` to obtain `ExtendedPropertiesBinder`:
```Java
		if (binder instanceof ExtendedPropertiesBinder) {
			ExtendedPropertiesBinder extendedPropertiesBinder = (ExtendedPropertiesBinder) binder;
			Object extension = extendedPropertiesBinder.getExtendedProducerProperties(outputChannelName);
			ExtendedProducerProperties extendedProducerProperties = new ExtendedProducerProperties<>(extension);
			BeanUtils.copyProperties(producerProperties, extendedProducerProperties);
			producerProperties = extendedProducerProperties;
		}

```

I think it is a general purpose.  

Are there another more elegant way to solve the problem?

**Comment by mbogoevici** [comment]
Hi @sunnykaka,

Thanks for reporting. Looks like a bug on our side. Will investigate and fix before GA.
