### ISSUE TITLE
Rabbit binder: correct typo in configuration

### ISSUE THREAD

**Issue by detached** [spring-cloud/spring-cloud-stream#570]
When configuring the admin addresses for the rabbit binder as [documented](http://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_rabbit_specific_settings) the following error occurs:

`````
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[...]
Caused by: java.lang.IllegalStateException: 'addresses', 'adminAddresses', and 'nodes' properties must have equal length
    at org.springframework.util.Assert.state(Assert.java:392)
    at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.onInit(RabbitMessageChannelBinder.java:192)
    at org.springframework.cloud.stream.binder.AbstractBinder.afterPropertiesSet(AbstractBinder.java:142)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
`````

application.properties
`````
spring.cloud.stream.rabbit.binder.adminAddresses=http://rabbit1:15672,http://rabbit2:15672,http://rabbit3:15672
spring.cloud.stream.rabbit.binder.nodes=rabbit1:5672,rabbit2:5672,rabbit3:5672
spring.rabbitmq.addresses=rabbit1:5672,rabbit2:5672,rabbit3:5672
`````

Because `adminAddresses` was misspelled `adminAdresses` in  `RabbitBinderConfigurationProperties` the property can't be injected properly.

As a workaround `spring.cloud.stream.rabbit.binder.adminAdresses` can be used in application.properties.

Pull request #567 solves this issue.

**Comment by mbogoevici** [comment]
Hi Simon - thanks for opening the issue and for the contribution. Will merge this into our 1.0.2.RELEASE which is scheduled for today.

**Comment by mbogoevici** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-stream/pull/567

**Comment by detached** [comment]
Thanks for the fast response Marius!
