### ISSUE TITLE
KafkaBinderHealthIndicator - KafKaConsumer properties problem - spring-cloud-stream-binder-kafka version 1.1.0.BUILD-SNAPSHOT 

### ISSUE THREAD

**Issue by justcoon** [spring-cloud/spring-cloud-stream#606]
spring-cloud-stream-binder-kafka version 1.1.0.BUILD-SNAPSHOT

Kafka health check crashing on:

Caused by: org.apache.kafka.common.config.ConfigException: Missing required configuration "value.deserializer" which has no default value.
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:148)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:49)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:56)
	at org.apache.kafka.clients.consumer.ConsumerConfig.<init>(ConsumerConfig.java:336)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:512)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:494)
	at org.springframework.cloud.stream.binder.kafka.KafkaBinderHealthIndicator.health(KafkaBinderHealthIndicator.java:58)

in KafkaBinderHealthIndicator

	@Override
	public Health health() {
		Map<String, String> properties = new HashMap<>();
		properties.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, this.configurationProperties
				.getKafkaConnectionString());
		properties.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, ByteArrayDeserializer.class.getName());
		KafkaConsumer metadataConsumer = new KafkaConsumer(properties);

probably missing configuration for ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG

**Comment by mbogoevici** [comment]
Hi @justcoon - thanks for reporting! moving this to https://github.com/spring-cloud/spring-cloud-stream-binder-kafka (All post 1.0 binders have their own repositories).

**Comment by mbogoevici** [comment]
Also, contributions are always welcome!

**Comment by mbogoevici** [comment]
Moved to https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/17
