### ISSUE TITLE
Performance issue with aggregated app

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-stream#759]
Looks like `direct binding` aka short circuiting channels does a bit too much with messages as can be seen from a hotstop from a profiler which lead into a Runnable. It seems that class parsing happens with every message.

```
"pool-6-thread-1" #28 prio=5 os_prio=0 tid=0x00007f70ed1f4800 nid=0xc38 runnable [0x00007f70e6c6b000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.reflect.Array.$$YJP$$newArray(Native Method)
	at java.lang.reflect.Array.newArray(Array.java)
	at java.lang.reflect.Array.newInstance(Array.java:75)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:179)
	at sun.reflect.annotation.AnnotationParser.toArray(AnnotationParser.java:865)
	at java.lang.reflect.Executable.getDeclaredAnnotations(Executable.java:588)
	at java.lang.reflect.Method.getDeclaredAnnotations(Method.java:630)
	at org.springframework.core.annotation.AnnotationUtils.findAnnotation(AnnotationUtils.java:522)
	at org.springframework.core.annotation.AnnotationUtils.findAnnotation(AnnotationUtils.java:504)
	at org.springframework.core.annotation.AnnotationUtils.findAnnotation(AnnotationUtils.java:570)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.invoke(BindableProxyFactory.java:88)
	- locked <0x00000003d4bae320> (a org.springframework.cloud.stream.binding.BindableProxyFactory)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy102.output(Unknown Source)
	at org.springframework.cloud.stream.app.load.generator.source.LoadGeneratorSourceConfiguration$Producer.run(LoadGeneratorSourceConfiguration.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by mbogoevici** [comment]
As a note - this is caused by the direct use of `Source.output()` for each message as the proxy method invocation is not efficient (apps that inject the channel or retrieve it only once will not be affected).

**Comment by jvalkeal** [comment]
I quickly added method caching to `BindableProxyFactory` but it actually didn't contribute that much. Got message rate up from 130K to 180K. Looking stacktrace it now spends most time in spel
```
"pool-6-thread-1" #28 prio=5 os_prio=0 tid=0x00007ff23f45f800 nid=0x4ea4 runnable [0x00007ff2c9c69000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.reflect.Array.$$YJP$$newArray(Native Method)
	at java.lang.reflect.Array.newArray(Array.java)
	at java.lang.reflect.Array.newInstance(Array.java:75)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:179)
	at sun.reflect.annotation.AnnotationParser.toArray(AnnotationParser.java:865)
	at java.lang.reflect.Executable.getDeclaredAnnotations(Executable.java:588)
	at java.lang.reflect.Method.getDeclaredAnnotations(Method.java:630)
	at java.lang.reflect.AccessibleObject.getAnnotations(AccessibleObject.java:207)
	at org.springframework.core.MethodParameter.getMethodAnnotations(MethodParameter.java:454)
	at org.springframework.core.convert.TypeDescriptor.<init>(TypeDescriptor.java:89)
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:114)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:102)
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49)
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:347)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:330)
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:169)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:317)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:155)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:93)
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:89)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:148)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:121)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:423)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373)
	at org.springframework.cloud.stream.app.load.generator.source.LoadGeneratorSourceConfiguration$Producer.run(LoadGeneratorSourceConfiguration.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Didn't yet dick it further but if spel compilation is not enabled, we take a bit hit from there as well.

**Comment by artembilan** [comment]
I wonder if you have bumped to something like this: https://jira.spring.io/browse/SPR-15060.
Quoting Juergen if that:
> Ok, that clarifies it indeed: You're going through SpEL's generic resolution algorithm there which indeed recreates MethodParameter instances every time... I'll sort this out through an Annotation.equals fallback in TypeDescriptor. So your present approach will work properly again as of Spring Framework 4.3.6.

> As a side note, I have no idea why Method.getParameterAnnotations() creates fresh Annotation instances on every call. Annotations on a Method and Constructor itself and also on a Field are cached by the JVM and therefore prepared for identity comparisons. Just parameter-level annotations aren't

**Comment by jvalkeal** [comment]
ok, thx guys. Marius, I'll try to PR this caching change tomorrow. Hopefully that's all we need when core 4.3.6 is out.

**Comment by mbogoevici** [comment]
Thanks, Janne - I'll keep an eye on it - I need to release today, but this can be in M2/SR3.
