### ISSUE TITLE
Register PartitionKeyExtractorStrategy Instance Failed

### ISSUE THREAD

**Issue by tangrui** [spring-cloud/spring-cloud-stream#772]
After the application bootstrap, there are multiple thread to send messages through the MessageChannel. Then exception thrown:

```
2017-01-23 16:25:02.024  INFO 18635 --- [http-nio-8080-exec-1] o.a.c.c.C.[.[.[/]                        : Initializing Spring FrameworkServlet 'dispatcherServlet'
Exception in thread "consumer-pool-thread-6" Exception in thread "consumer-pool-thread-4" Exception in thread "consumer-pool-thread-2" Exception in thread "consumer-pool-thread-8" org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'output'; nested exception is org.springframework.cloud.stream.binder.BinderException: Failed to instantiate class: com.xxx.holstein.gateway.stream.DeviceIdPartitionKeyExtractorStrategy
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:449)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373)
        at com.xxx.holstein.gateway.consumer.impl.KafkaGatewayConsumerImpl.process(KafkaGatewayConsumerImpl.java:38)
        at com.xxx.holstein.gateway.service.impl.DefaultQueueServiceImpl$ConsumerWorker.run(DefaultQueueServiceImpl.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.cloud.stream.binder.BinderException: Failed to instantiate class: com.xxx.holstein.gateway.stream.DeviceIdPartitionKeyExtractorStrategy
        at org.springframework.cloud.stream.binder.PartitionHandler.getBean(PartitionHandler.java:158)
        at org.springframework.cloud.stream.binder.PartitionHandler.invokeKeyExtractor(PartitionHandler.java:119)
        at org.springframework.cloud.stream.binder.PartitionHandler.extractKey(PartitionHandler.java:108)
        at org.springframework.cloud.stream.binder.PartitionHandler.determinePartition(PartitionHandler.java:88)
        at org.springframework.cloud.stream.binding.MessageConverterConfigurer$PartitioningInterceptor.preSend(MessageConverterConfigurer.java:222)
        at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:538)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:415)
        ... 6 more
Caused by: java.lang.IllegalStateException: Could not register object [com.xxx.holstein.gateway.stream.DeviceIdPartitionKeyExtractorStrategy@753b160f] under bean name 'com.xxx.holstein.gateway.stream.DeviceIdPartitionKeyExtractorStrategy': there is already object [com.xxx.holstein.gateway.stream.DeviceIdPartitionKeyExtractorStrategy@4fc3375a] bound
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.registerSingleton(DefaultSingletonBeanRegistry.java:130)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerSingleton(DefaultListableBeanFactory.java:934)
        at org.springframework.cloud.stream.binder.PartitionHandler.getBean(PartitionHandler.java:154)
        ... 12 more
org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'output'; nested exception is org.springframework.cloud.stream.binder.BinderException: Failed to instantiate class: com.xxx.holstein.gateway.stream.DeviceIdPartitionKeyExtractorStrategy
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:449)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373)
        at com.xxx.holstein.gateway.consumer.impl.KafkaGatewayConsumerImpl.process(KafkaGatewayConsumerImpl.java:38)
        at com.xxx.holstein.gateway.service.impl.DefaultQueueServiceImpl$ConsumerWorker.run(DefaultQueueServiceImpl.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.cloud.stream.binder.BinderException: Failed to instantiate class: com.xxx.holstein.gateway.stream.DeviceIdPartitionKeyExtractorStrategy
        at org.springframework.cloud.stream.binder.PartitionHandler.getBean(PartitionHandler.java:158)
        at org.springframework.cloud.stream.binder.PartitionHandler.invokeKeyExtractor(PartitionHandler.java:119)
        at org.springframework.cloud.stream.binder.PartitionHandler.extractKey(PartitionHandler.java:108)
        at org.springframework.cloud.stream.binder.PartitionHandler.determinePartition(PartitionHandler.java:88)
        at org.springframework.cloud.stream.binding.MessageConverterConfigurer$PartitioningInterceptor.preSend(MessageConverterConfigurer.java:222)
        at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:538)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:415)
        ... 6 more
Caused by: java.lang.IllegalStateException: Could not register object [com.xxx.holstein.gateway.stream.DeviceIdPartitionKeyExtractorStrategy@936ba1a] under bean name 'com.xxx.holstein.gateway.stream.DeviceIdPartitionKeyExtractorStrategy': there is already object [com.xxx.holstein.gateway.stream.DeviceIdPartitionKeyExtractorStrategy@4fc3375a] bound
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.registerSingleton(DefaultSingletonBeanRegistry.java:130)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerSingleton(DefaultListableBeanFactory.java:934)
        at org.springframework.cloud.stream.binder.PartitionHandler.getBean(PartitionHandler.java:154)
        ... 12 more
org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'output'; nested exception is org.springframework.cloud.stream.binder.BinderException: Failed to instantiate class: com.xxx.holstein.gateway.stream.DeviceIdPartitionKeyExtractorStrategy
```

Digging into the source, I found that in `PartitioningInterceptor.preSend()` method, every thread call will construct a new `PartitionHandler`, but in `PartitionHandler.getBean()` method, when the `PartitionKeyExtractorStrategy` instance is not in `beanFactory`, then it's been registered as singleton. But in the `else` section, this method `synchronized(this)`, here seems to be some problem, because PartitionHandler instance is not shared between thread call, so `synchronized(this)` may not sync the method call between threads, then cause the above exception. I think `synchronized(this)` should be changed to `synchronized(this.getClass())` or something similar to make the lock work.

**Comment by mbogoevici** [comment]
Thanks @tangrui for reporting. This might have already been alleviated by https://github.com/spring-cloud/spring-cloud-stream/commit/2ff48a9367e3ad29a4be0a04986af43645a964ac - where a single `PartitionHandler` instance is constructed per partition interceptor.

But agreed with the comment on the lock. At a first glance, I suppose the correct lock would be the `beanFactory` instance - since the critical section needs to have exclusive access to it anyway.
