### ISSUE TITLE
AggregateApplicationBuilder shouldn't use binder

### ISSUE THREAD

**Issue by japanbhatt** [spring-cloud/spring-cloud-stream#876]
when we implement spring cloud stream using AggregateApplicationBuilder, it mandates you to provide either kafka binder or rabbit binder. There should be a way to not to provide any of the binders and the stream should use inmemory queue to bind sources and sinks via AggregateApplicationBuilder.

**Comment by mbogoevici** [comment]
Aggregate applications don't use a binder, they communicate directly via Spring Integration `DirectChannel` instances (in-memory). What version are you using? There used to be an issue where a binder was required, but that has been closed since `Brooklyn.RELEASE`. See #576  . What version are you using?

**Comment by japanbhatt** [comment]
I wasnt using Brooklyn release, however, I moved to Brooklyn release, it is still asking me to define binders 
Caused by: org.springframework.beans.factory.BeanCreationException: Cannot create binder factory, no `META-INF/spring.binders` resources found on the classpath

not sure, what to put in direct channel. i dont see any documentation in spring cloud stream in these lines.

**Comment by mbogoevici** [comment]
Can you share your code, please? 

You don't need to do anything to use `DirectChannel`s, the aggregate application will use them automatically.  

In any case, here is an example of a self-contained application that does not require a binder: 
https://github.com/spring-cloud/spring-cloud-stream-samples/tree/Brooklyn/double

You can also take a look at same example with the Chelsea (latest) release:
https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master

**Comment by japanbhatt** [comment]
https://github.com/japanbhatt/test-japan123
here is the sample, which doesnt work for me. Let me know, what i am missing?

**Comment by mbogoevici** [comment]
In the example you posted, you still use 1.0.3. After upgrading to Brooklyn.RELEASE (I would recommend Chelsea.SR1 but wanted to show the first version where this is fixed) and removing the Kafka binder it works as expected.

Here are the changes I made.

* pom.xml https://gist.github.com/mbogoevici/1b0ae94e009aa895828f67ac69e04149/revisions#diff-600376dffeb79835ede4a0b285078036R4
* StreamApplication.java (switching to System out since log4j was not on the CP)
https://gist.github.com/mbogoevici/9345245f81d9f38cea34138bc7d001f2

**Comment by japanbhatt** [comment]
I used your changes and got below error

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-04-21 12:54:31.377 ERROR 12856 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.IllegalStateException: A default binder has been requested, but there there is no binder available
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.cloud.stream.aggregate.AggregateApplication.createParentContext(AggregateApplication.java:60) [spring-cloud-stream-1.1.0.RELEASE.jar:1.1.0.RELEASE]
	at org.springframework.cloud.stream.aggregate.AggregateApplicationBuilder.run(AggregateApplicationBuilder.java:152) [spring-cloud-stream-1.1.0.RELEASE.jar:1.1.0.RELEASE]
	at org.springframework.cloud.stream.aggregate.AggregateApplicationBuilder$AppConfigurer.run(AggregateApplicationBuilder.java:259) [spring-cloud-stream-1.1.0.RELEASE.jar:1.1.0.RELEASE]
	at com.capitalone.coaf_cs.ls_streams.consumer.StreamApplication.main(StreamApplication.java:26) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
Caused by: java.lang.IllegalStateException: A default binder has been requested, but there there is no binder available
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:97) ~[spring-cloud-stream-1.1.0.RELEASE.jar:1.1.0.RELEASE]
	at org.springframework.cloud.stream.binding.ChannelBindingService.getBinderForChannel(ChannelBindingService.java:142) ~[spring-cloud-stream-1.1.0.RELEASE.jar:1.1.0.RELEASE]
	at org.springframework.cloud.stream.binding.ChannelBindingService.bindProducer(ChannelBindingService.java:104) ~[spring-cloud-stream-1.1.0.RELEASE.jar:1.1.0.RELEASE]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:208) ~[spring-cloud-stream-1.1.0.RELEASE.jar:1.1.0.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:57) ~[spring-cloud-stream-1.1.0.RELEASE.jar:1.1.0.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 21 common frames omitted

**Comment by mbogoevici** [comment]
I can't exactly say what is wrong on your end, but this version of your example works for me:
https://github.com/mbg-scratchpad/scst-gh-876

**Comment by mbogoevici** [comment]
Please reopen if issue persists.
