### ISSUE TITLE
NullPointerException with sleuth and aspect

### ISSUE THREAD

**Issue by gbogaert** [spring-cloud/spring-cloud-stream#881]
I have one test in my project which send a message to kafka.
I have one aspect which add some log to my project executing before sending a message to kafka.

```
 @Before("execution(* org.springframework.messaging.MessageChannel.send(..)) && args(org.springframework.messaging.Message)")
  public void logBefore(JoinPoint joinPoint) throws JsonProcessingException {

    System.out.println("hello");
  }
```

The test ran successuffly when sleuth is not on the classpath (commented in pom.xml) but when i add sleuth i get the following error : 

```
org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'null'; nested exception is java.lang.NullPointerException
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:449)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373)
	at com.example.ChannelTest.exampleTest(ChannelTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NullPointerException
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:406)
	... 31 more
```
[test.zip](https://github.com/spring-cloud/spring-cloud-stream/files/873780/test.zip)

**Comment by artembilan** [comment]
Would you mind to explain, first of all, why `org.springframework.messaging.support.ChannelInterceptor` doesn't work for you: http://docs.spring.io/spring-integration/reference/html/messaging-channels-section.html#channel-interceptors?

I mean you don't need the AspectJ since there is more robust, non-proxying mechanism to interact with the `MessageChannel`. 

BTW, you can't proxy `AbstractMessageChannel.send()` method because it is `final`.

OTOH the Sleuth really just adds a global `ChannelInterceptor`...

**Comment by artembilan** [comment]
OK. I found the problem. 
And it is here: 
```
TraceEnvironmentPostProcessor
...
map.put("spring.aop.proxyTargetClass", "true");
```
When we don't use the CGLib class proxying,  but just interface-based JDK Proxy mechanism, everything works well.

Unfortunately, I don't know how to override that. Maybe one more `EnvironmentPostProcessor` with `Ordered` impl 😄 

See more info here: https://github.com/spring-cloud/spring-cloud-sleuth/issues/51

Please, move this issue to the Spring Cloud Sleuth. Nothing to do from the Stream perspective.

**Comment by artembilan** [comment]
This issue will be fixed via https://jira.spring.io/browse/INT-4270 in Spring Integration `4.3.10`: https://github.com/spring-projects/spring-integration/pull/2145

Since Spring Boot `2.0` makes `proxyTargetClass = true` by default, we don't have choice unless make `MessageChannel` classes compatible with CGLib.

Therefore this issue is aimed to track upgrade to SI-4.3.10.

Respective Spring Cloud Sleuth issue to track: https://github.com/spring-cloud/spring-cloud-sleuth/issues/584

**Comment by mbogoevici** [comment]
@gbogaert @artembilan - closing this as this will be fixed in Sleuth/SI.
