### ISSUE TITLE
Runtime errors with Boot 2.x

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-stream#935]
Mostly for heads up but boot is starting to break a lot of things
```
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/bind/RelaxedDataBinder
	at org.springframework.cloud.stream.binding.BindingService.validate(BindingService.java:174)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:96)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.bindInputs(BindableProxyFactory.java:221)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:55)
```
`RelaxedDataBinder` is gone, see https://github.com/spring-projects/spring-boot/issues/9000

I think we need to create `2.x` so that we start to see what issues spring5/boot2 brings in.

**Comment by mbogoevici** [comment]
@jvalkeal Yes, the plan is to get started on a 2.x branch in May.

**Comment by davidwadden** [comment]
Is there a build snapshot maven repository tracking the `2.x` branch anywhere?  I don't see one at http://repo.spring.io/libs-snapshot/org/springframework/cloud/spring-cloud-stream/

**Comment by mbogoevici** [comment]
Not yet, will have one next week once the binders are upgraded as well.

**Comment by mbogoevici** [comment]
Closing this after merging @jvalkeal 's PR in the `2.0.x` branch and making respective branches for all binders.

@davidwadden To your question - the BOM for `Elmhurst` release train (Based on 2.0) is CI-built now and available here https://repo.spring.io/libs-snapshot-local/org/springframework/cloud/spring-cloud-stream-dependencies/Elmhurst.BUILD-SNAPSHOT/
