### ISSUE TITLE
MessageDeliveryException in a @StreamListener method

### ISSUE THREAD

**Issue by franck54730** [spring-cloud/spring-cloud-stream#978]
Hi 
There is something we don't understand, we have a multi modules project. When I launch them separately with one embedded tomcat for each one, it's working well. 

However, when we run them on the same tomcat with a launcher module which have others modules as dependency (non executable jar (84.5 in springboot reference guide)), an Exception is thrown.

We have two modules which produce event on a single kafka channel and another one which is the only module consuming on this channel.

Here is the exception :
```
org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'unknown.channel.name'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload={"idUser":"faudiger","message":"<font size=\"3\" color=\"red\"><b>Error in argument number. \nSee '/help' command or -help argument to get some help</b></font>"}, headers={kafka_offset=9, id=986268ef-0135-ca50-c110-b5a9b6fb8f51, kafka_receivedPartitionId=0, contentType=application/json;charset=UTF-8, kafka_receivedTopic=em-mt, timestamp=1496412158037}]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:93) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:423) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) ~[spring-messaging-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) ~[spring-messaging-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) ~[spring-messaging-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:292) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:212) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:129) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:115) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:70) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:64) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) ~[spring-messaging-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) ~[spring-messaging-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) ~[spring-messaging-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:171) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$000(KafkaMessageDrivenChannelAdapter.java:54) ~[spring-integration-kafka-2.1.0.RELEASE.jar:na]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:288) ~[spring-integration-kafka-2.1.0.RELEASE.jar:na]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:279) ~[spring-integration-kafka-2.1.0.RELEASE.jar:na]
	at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter$1.doWithRetry(RetryingAcknowledgingMessageListenerAdapter.java:77) ~[spring-kafka-1.1.4.RELEASE.jar:na]
	at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter$1.doWithRetry(RetryingAcknowledgingMessageListenerAdapter.java:72) ~[spring-kafka-1.1.4.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:286) ~[spring-retry-1.2.0.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:179) ~[spring-retry-1.2.0.RELEASE.jar:na]
	at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter.onMessage(RetryingAcknowledgingMessageListenerAdapter.java:72) ~[spring-kafka-1.1.4.RELEASE.jar:na]
	at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter.onMessage(RetryingAcknowledgingMessageListenerAdapter.java:39) ~[spring-kafka-1.1.4.RELEASE.jar:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:771) [spring-kafka-1.1.4.RELEASE.jar:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:715) [spring-kafka-1.1.4.RELEASE.jar:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.access$2600(KafkaMessageListenerContainer.java:231) [spring-kafka-1.1.4.RELEASE.jar:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer$ListenerInvoker.run(KafkaMessageListenerContainer.java:1004) [spring-kafka-1.1.4.RELEASE.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]
Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:154) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:121) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:89) ~[spring-integration-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 32 common frames omitted 
```

We listened on this kafka channel with a kafka consumer to check if this two producer modules work and they effectively do.
We suppose that the consumer module has an issue ..

There is our launcher application.properties : 

```
server.port=${JARVIS_PORT}

spring.cloud.stream.kafka.binder.brokers=${JARVIS_KAFKA_IP}
spring.cloud.stream.kafka.binder.zkNodes=${JARVIS_ZOOKEEPER_IP}
spring.cloud.stream.kafka.binder.defaultBrokerPort=${JARVIS_KAFKA_PORT}
spring.cloud.stream.kafka.binder.defaultZkPort=${JARVIS_ZOOKEEPER_PORT}

spring.cloud.stream.kafka.binder.autoAddPartitions=true

spring.cloud.stream.bindings.chan.destination=chan
spring.cloud.stream.bindings.chan.contentType=application/json
```

PS : we noticed that the first sent event is well consumed.

**Comment by artembilan** [comment]
Looks like you consume record by the `KafkaMessageListenerContainer` and send a message to the `MessageChannel`, but there is no subscriber for that anonymous channel.

Since that `MessageChannel` has a name like `unknown.channel.name`. That clearly says that the channel isn't managed by the application context.

We can't help without more context.

Thanks

**Comment by franck54730** [comment]
Thanks for your reply, I don't have the code of the application on my personnal PC. I can give you that on tuesday. if I give you code of the application.property, the @EnableBinding class and the channel interface they bind is it enought to help us ? thanks again for your fast reply.

**Comment by artembilan** [comment]
Thank you, @franck54730 , for being in touch!

Well, yes, please, share your `@EnableBinding` configuration class. I really would like to see how you are wired to the `Source` message channel.

@mbg, 
Please, pay attention to the error:

> Dispatcher has no subscribers for channel 'unknown.channel.name'.;

Since we don't register some internal `MessageChannel`s as beans during binding that would be great to specify them at least some artificial `componentName` to identify their belonging to particular binding.

Thanks

**Comment by mbogoevici** [comment]
@artembilan Thanks for pointing it out. I've created https://github.com/spring-cloud/spring-cloud-stream/issues/983 for tracking `NamedComponent` fixes.

**Comment by franck54730** [comment]
Good morning, so there is our @EnableBinding classes, called CommunicationManager in each module.
For two producer modules :  
- mf module which contains 3 communication manager (these ones works and produce well on channel they also have @StreamListener but for readability I don't give it here but they works) : 
first one :

```
@EnableBinding(MessageFormatterChannel.class)
@Component(value="mf.CommunicationManagerHelp")
public class CommunicationManagerHelp {

	final static Logger logger = Logger.getLogger(CommunicationManagerHelp.class);
	
	private MessageFormatterChannel messageFormatterChannel;

	@Autowired
	public CommunicationManagerHelp(MessageFormatterChannel messageFormatterChannelWido) {
		this.messageFormatterChannel = messageFormatterChannelWido;
	}
	
	public void sendToMT(HubotEvent event){
		this.messageFormatterChannel.publish().send(MessageBuilder.withPayload(event).build());
	}
} 
```

second one :

```
@EnableBinding(MessageFormatterChannel.class)
@Component(value="mf.CommunicationManagerWid")
public class CommunicationManagerWid {

	final static Logger logger = Logger.getLogger(CommunicationManagerWid.class);

	private MessageFormatterChannel messageFormatterChannel;

	private WidFormatter formatter;

	@Autowired
	public CommunicationManagerWid(MessageFormatterChannel messageFormatterChannelWido, WidFormatter formatter) {
		this.messageFormatterChannel = messageFormatterChannelWido;
		this.formatter = formatter;
	}

	public void sendToMT(HubotEvent event){
		this.messageFormatterChannel.publish().send(MessageBuilder.withPayload(event).build());
	}
}
```

third one : 

```
@EnableBinding(MessageFormatterChannel.class)
@Component(value="mf.CommunicationManagerWido")
public class CommunicationManagerWido {

	final static Logger logger = Logger.getLogger(CommunicationManagerWido.class);
	
	private MessageFormatterChannel messageFormatterChannel;

	private WidoFormatter formatter;
	
	@Autowired
	public CommunicationManagerWido(MessageFormatterChannel messageFormatterChannelWido, WidoFormatter formatter) {
		this.messageFormatterChannel = messageFormatterChannelWido;
		this.formatter = formatter;
	}

	public void sendToMT(HubotEvent event){
		this.messageFormatterChannel.publish().send(MessageBuilder.withPayload(event).build());
	}
}
```
and the channel interface :

```
@Component(value="mf.MessageFormatterChannel")
public interface MessageFormatterChannel {

    String XLM_MF = "xlm-mf";
    
    String CLM_MF = "clm-mf";

    String MT_INPUT = "mt-input";

    @Input(XLM_MF)
    SubscribableChannel subscribeXLM();
    
    @Input(CLM_MF)
    SubscribableChannel subscribeCLM();

    @Output(MT_INPUT)
    MessageChannel publish();
}
```

they have the same method to send event on mt-input channel, following the code of the second module which produce message on the mt-input channel : 

```
@EnableBinding(ErrorManagerChannel.class)
@Component(value="em.CommunicationManager")
public class CommunicationManager {

    final static Logger logger = Logger.getLogger(CommunicationManager.class);

    private ErrorManagerChannel errorManagerChannel;

    private ErrorFormatter formatter;

    @Autowired
    public CommunicationManager(ErrorManagerChannel errorManagerChannel, ErrorFormatter formatter) {
        this.errorManagerChannel = errorManagerChannel;
        this.formatter = formatter;
    }

    public void errorSender(ErrorEvent error, String message, ErrorCode e){
        logger.info("JARVIS:EM -> EM receive following event from " + e + " : \n" + error);
        HubotEvent he = new HubotEvent(error.getIdUser(), this.formatter.getFormatError(message));
        sendErrorToEM(he);
        logger.info("JARVIS:EM -> EM send following event to MT : \n" + he);
    }

    public void sendErrorToEM(HubotEvent event) {
        this.errorManagerChannel.publish().send(MessageBuilder.withPayload(event).build());
    }
}
```

channel interface : 
```
@Component(value="em.ErrorManagerChannel")
public interface ErrorManagerChannel {

	String ERROR= "error";
    
    String MT_INPUT = "mt-input";

    @Input(ERROR)
    SubscribableChannel subscribeErrorCLM();

    @Output(MT_INPUT)
    MessageChannel publish();
}
```

Now a cli which run a kafka consumer on mt-input channel only the first message of this following events is consumed : 
```
λ kafka-console-consumer.bat --bootstrap-server 192.168.56.100:8183 --topic mt-input
 ☻♂contentType   ♀"text/plain"‼originalContentType    "application/json;charset=UTF-8"{"idUser":"faudiger ☻♂contentType   ♀"text/plain"‼originalContentType    "application/json;charset=UTF-8"{"idUser":"faudiger ☻♂contentType   ♀"text/plain"‼originalContentType    "application/json;charset=UTF-8"{"idUser":"faudiger","message":"<div><b>Usage : <font size=\"3\" color=\"green\">'/wido [ENV]'</font> where ENV is an environment (E2E, PPR, PRD, ..)</b> </div>"}
 ☻♂contentType   ♀"text/plain"‼originalContentType    "application/json;charset=UTF-8"{"idUser":"faudiger","message":"<font size=\"3\" color=\"red\"><b>XLDeploy server is probably down.</b></font>"}
 ☻♂contentType   ♀"text/plain"‼originalContentType    "application/json;charset=UTF-8"{"idUser":"faudiger","message":"<font size=\"3\" color=\"red\"><b>Error in argument number. \nSee '/help' command or -help argument to get some help</b></font>"}
```
And finally the modules which consume : 

```
@EnableBinding(MessageTransmitterChannel.class)
@Component(value="mt.CommunicationManager")
public class CommunicationManager {

	final static Logger logger = Logger.getLogger(CommunicationManager.class);
	
	private HubotExpressApiCaller caller;
	
    @Autowired
    public CommunicationManager(HubotExpressApiCaller caller) {
    	this.caller = caller;
    }

    @StreamListener(MessageTransmitterChannel.MT_INPUT)
    public void receive(@Payload HubotEvent event){
    	logger.info("JARVIS:MT -> MT receive following event from MF and send it to hubot : \n"+event);
        caller.sendToHubot(event);
    }
}
```
channel interface : 
```
@Component(value="mt.MessageTransmitterChannel")
public  interface MessageTransmitterChannel {

    String MT_INPUT="mt-input";

    @Input(MT_INPUT)
    SubscribableChannel subscribe();
}
```

and application properties : 
```
server.port=${JARVIS_CBA_PORT}

spring.cloud.stream.kafka.binder.brokers=${JARVIS_KAFKA_IP}
spring.cloud.stream.kafka.binder.zkNodes=${JARVIS_ZOOKEEPER_IP}
spring.cloud.stream.kafka.binder.defaultBrokerPort=${JARVIS_KAFKA_PORT}
spring.cloud.stream.kafka.binder.defaultZkPort=${JARVIS_ZOOKEEPER_PORT}

spring.cloud.stream.kafka.binder.autoAddPartitions=true

spring.cloud.stream.kafka.binder.headers=command,errorCode

spring.cloud.stream.bindings.cba-clm.destination=cba-clm
spring.cloud.stream.bindings.cba-clm.contentType=application/json

spring.cloud.stream.bindings.clm-xlm.destination=clm-xlm
spring.cloud.stream.bindings.clm-xlm.contentType=application/json

spring.cloud.stream.bindings.clm-mf.destination=clm-mf
spring.cloud.stream.bindings.clm-mf.contentType=application/json

spring.cloud.stream.bindings.mt-input.destination=mt-input
spring.cloud.stream.bindings.mt-input.contentType=application/json

spring.cloud.stream.bindings.xlm-mf.destination=xlm-mf
spring.cloud.stream.bindings.xlm-mf.contentType=application/json

spring.cloud.stream.bindings.error.destination=error
spring.cloud.stream.bindings.error.contentType=application/json
```

I think you almost have the entire context now, if you have any other question or if you want any precision, please feel free to ask.

**Comment by franck54730** [comment]
fixed but I don't know why, can you explain it to me, i change my properties like that : 
```
spring.cloud.stream.bindings.mt-input1.destination=mt-input
spring.cloud.stream.bindings.mt-input1.contentType=application/json

spring.cloud.stream.bindings.mt-input2.destination=mt-input
spring.cloud.stream.bindings.mt-input2.contentType=application/json
```

and my channel interfaces to : 
```
@Component(value="em.ErrorManagerChannel")
public interface ErrorManagerChannel {

	String ERROR= "error";
    
    String MT_INPUT = "mt-input1";

    @Input(ERROR)
    SubscribableChannel subscribeErrorCLM();

    @Output(MT_INPUT)
    MessageChannel publish();
}
```
and

```
@Component(value="mf.MessageFormatterChannel")
public interface MessageFormatterChannel {

    String XLM_MF = "xlm-mf";
    
    String CLM_MF = "clm-mf";

    String MT_INPUT2 = "mt-input2";

    @Input(XLM_MF)
    SubscribableChannel subscribeXLM();
    
    @Input(CLM_MF)
    SubscribableChannel subscribeCLM();

    @Output(MT_INPUT2)
    MessageChannel publish();
}
```

and it's finally works but I don't totally understand why, thanks for your help

**Comment by ilayaperumalg** [comment]
Hi @franck54730,

The binding target name (here the subscribable message channel name) has to be unique inside the application context and you can't have multiple message channels binding with the same name. 

Earlier, you were using the same message channel name for two subscribable channels and now it worked with distinct inbound target (message channel) names.

**Comment by franck54730** [comment]
okok thanks for your explication, and thank you all for your help, sorry for disturb
