### ISSUE TITLE
Can use INPUT only for receiving kafka message

### ISSUE THREAD

**Issue by michael8335** [spring-cloud/spring-cloud-stream#991]
hi:
 I have a lot of producers,which write message into kafka,I can not control those producers,I am only a comuser ,Can use INPUT only for receiving kafka message,I have test use kafka shell write message "hello" into kafka , the receiver throw exception:org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Unrecognized token 'hello': was expecting ('true', 'false' or 'null')
 at [Source: [B@48b6ea96; line: 1, column: 11]; nested exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'hello': was expecting ('true', 'false' or 'null')
 at [Source: [B@48b6ea96; line: 1, column: 11]
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:224) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:175) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:167) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:55) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]

SO I want to know is there any way to  only receiving kafka message  by spring cloud stream

Thanks

**Comment by mbogoevici** [comment]
@michael8335 You can use the `raw` `headerMode` setting on the consumer when receiving messages from external applications. See http://docs.spring.io/autorepo/docs/spring-cloud-stream-docs/Chelsea.SR2/reference/htmlsingle/#_consumer_properties . You can also set up a custom Kafka deserializer via the `configuration` property of the consumer - see http://docs.spring.io/autorepo/docs/spring-cloud-stream-docs/Chelsea.SR2/reference/htmlsingle/#_kafka_consumer_properties .

**Comment by michael8335** [comment]
@mbogoevici Dear ,My mistake,I did not point my idear,what I want is that,spring cloud stream subscribe kafka topic whatever the message is,is this possible?any  demo ?? thanks
best wishes from china developer

**Comment by mbogoevici** [comment]
@michael8335 can you provide an example reproducing the error, please? Thank you.

**Comment by viniciusccarvalho** [comment]
Closing this, we could not reproduce what the user has described and there's no activity for the past 30 days
